"""Build the TC2000 parity golden — Phase 0.14 packet V1, item 1.

Decision 0016 answer 9 makes the trader's own TC2000 scan the SPECIFICATION for
the Strength Board. This fixture is what "parity" means in numbers: five
symbols, sixteen sessions of M5 bars each, and the relative strength and relative
volume computed **by hand here** — from the formulas as the trader wrote them,
not by calling the module the test is checking.

That is the whole point. A golden generated by the code under test pins whatever
the code does, including its mistakes. These values are produced by a second,
deliberately naive implementation written straight from the trader's two lines:

    relative strength = AVG(((C/O) - 1) * 100, 12) * ((C + C50) / 2) / ATR50
    relative volume   = AVG(V / mean(V at the same bar offset over the prior
                              15 sessions), 12)

R4 A7 corrected the second line here as well as in the module. It read
`AVG(V / mean(V78, V156, ... V1170), 12)` - a flat positional stride - and that
is only the same thing as the trader's line on a series with no short sessions.
Two symbols now carry the cases where it is not: `FFF` has one early close and
`GGG` has one missing bar.

Run with `--write` to regenerate, and READ THE DIFF: a change here is a change to
the trader's scan, not a refresh.

The bars are synthetic and deterministic. Real bars would make the fixture a
snapshot of one afternoon's tape and would need re-acquiring; synthetic bars with
a stated generator make every number reproducible by hand.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tests" / "fixtures" / "tc2000_parity_v1.json"

SESSION_BARS = 78
SESSIONS = 16
BODY_BARS = 12
ATR_PERIOD = 50
RVOL_PRIOR_SESSIONS = 15

#: Seven deliberately different shapes. The generator is a plain arithmetic walk
#: so every bar is reproducible from these numbers alone.
SYMBOLS = {
    #        base   drift    range  vol_base  vol_today
    "AAA": (100.0, 0.010, 0.30, 1000.0, 3000.0),
    "BBB": (50.0, 0.004, 0.20, 2000.0, 2200.0),
    "CCC": (250.0, -0.006, 0.90, 800.0, 400.0),
    "DDD": (12.5, 0.020, 0.08, 5000.0, 15000.0),
    "EEE": (7.5, 0.000, 0.05, 300.0, 300.0),
    # R4 A7. Both of these have a volume series that depends ONLY on the bar's
    # offset inside its session and is identical on every session INCLUDING
    # today, so the honest relative volume is exactly 1.00 and any deviation is
    # the alignment, never the data.
    "FFF": (60.0, 0.002, 0.15, 1000.0, 0.0),
    "GGG": (60.0, 0.002, 0.15, 1000.0, 0.0),
}

#: Bars in an EARLY-CLOSE session: 3.25 hours. `{symbol: {session: bars}}`.
#: One of these anywhere in the window shifts every positional offset past it by
#: 39 bars, which is how a 10:00 bar ends up compared with a 13:00 one.
EARLY_CLOSE_BARS = 39
SHORT_SESSIONS = {"FFF": {7: EARLY_CLOSE_BARS}}

#: One bar dropped from the middle of a prior session. The session still exists
#: and still reaches most of the day; it is one offset that has no bar, and that
#: offset must contribute NOTHING rather than a zero. `{symbol: {session: index}}`
MISSING_BARS = {"GGG": {4: 30}}

#: Volume that is a pure function of the time of day. Used by FFF and GGG so the
#: expected relative volume is exactly 1.00 under session-relative alignment.
TIME_OF_DAY_VOLUME = {"FFF", "GGG"}


def _session_length(symbol: str, session: int) -> int:
    return SHORT_SESSIONS.get(symbol, {}).get(session, SESSION_BARS)


def build_bars(symbol: str) -> list[dict]:
    """Sixteen sessions of M5 bars. Deterministic, no randomness anywhere."""
    base, drift, span, vol_base, vol_today = SYMBOLS[symbol]
    bars: list[dict] = []
    price = base
    start = datetime(2026, 6, 1, 6, 30)
    dropped = MISSING_BARS.get(symbol, {})
    for session in range(SESSIONS):
        day = start + timedelta(days=session)
        today = session == SESSIONS - 1
        for index in range(_session_length(symbol, session)):
            if dropped.get(session) == index:
                continue
            stamp = day + timedelta(minutes=5 * index)
            open_price = price
            # A repeating body pattern, so the 12-bar average is a real average
            # over different bars rather than the same one twelve times.
            step = drift * (1.0 + ((index % 5) - 2) * 0.25)
            close_price = open_price * (1.0 + step)
            high = max(open_price, close_price) + span / 2.0
            low = min(open_price, close_price) - span / 2.0
            if symbol in TIME_OF_DAY_VOLUME:
                # A volume curve that RISES across the session, so a misaligned
                # offset compares a late bar with a middling one and the error
                # is visible. The repeating (index % 7) pattern the other five
                # use is nearly flat under a 39-bar shift, which would have made
                # this fixture agree with the defect to within 1%.
                volume = vol_base * (1.0 + index * 0.05)
            else:
                volume = vol_today if today else vol_base * (1.0 + (index % 7) * 0.05)
            bars.append(
                {
                    "dt": stamp.isoformat(),
                    "open": round(open_price, 6),
                    "high": round(high, 6),
                    "low": round(low, 6),
                    "close": round(close_price, 6),
                    "volume": round(volume, 6),
                }
            )
            price = close_price
    return bars


# ---------------------------------------------------------------------------
# The hand implementation. Written from the trader's two lines, not from the
# module under test.
# ---------------------------------------------------------------------------


def hand_strength(bars: list[dict]) -> float:
    closes = [bar["close"] for bar in bars]
    opens = [bar["open"] for bar in bars]

    body = sum(
        ((closes[-1 - step] / opens[-1 - step]) - 1.0) * 100.0
        for step in range(BODY_BARS)
    ) / BODY_BARS

    # C50 is the close FIFTY BARS AGO - a single historical price, never an SMA.
    c50 = closes[-1 - ATR_PERIOD]

    true_range = []
    for index in range(1, len(bars)):
        high = bars[index]["high"]
        low = bars[index]["low"]
        previous_close = bars[index - 1]["close"]
        true_range.append(
            max(high - low, abs(high - previous_close), abs(low - previous_close))
        )
    atr50 = sum(true_range[-ATR_PERIOD:]) / ATR_PERIOD

    return body * ((closes[-1] + c50) / 2.0) / atr50


def hand_rvol(bars: list[dict]) -> float:
    """The trader's line, session-relative, written out the slow obvious way.

    Group the bars by their own date, take the last twelve, and for each one
    average the volume at the SAME OFFSET INSIDE A SESSION over the fifteen
    sessions before it. A session that never reached that offset simply is not
    in the average - it is a day that closed early, not a day with no volume.
    """
    sessions: list[list[dict]] = []
    seen = None
    for bar in bars:
        day = bar["dt"][:10]
        if day != seen:
            sessions.append([])
            seen = day
        sessions[-1].append(bar)

    positions = [
        (session_index, offset)
        for session_index, session in enumerate(sessions)
        for offset in range(len(session))
    ]
    ratios = []
    for session_index, offset in positions[-BODY_BARS:]:
        prior = [
            sessions[session_index - back][offset]["volume"]
            for back in range(1, RVOL_PRIOR_SESSIONS + 1)
            if offset < len(sessions[session_index - back])
        ]
        ratios.append(sessions[session_index][offset]["volume"] / (sum(prior) / len(prior)))
    return sum(ratios) / len(ratios)


def build_payload() -> dict:
    bars = {symbol: build_bars(symbol) for symbol in SYMBOLS}
    expected = {
        symbol: {
            "strength": round(hand_strength(rows), 6),
            "rvol": round(hand_rvol(rows), 6),
        }
        for symbol, rows in bars.items()
    }
    payload = {
        "schema": "tc2000_parity_v1",
        "feature_version": "strength_scan.v1_names_first",
        "universe_version": "synthetic-5",
        "provider_assumptions": (
            "Synthetic M5 bars generated by tests/build_tc2000_parity_fixture.py. "
            "16 sessions each. AAA-EEE are 78 bars per session with no gaps and "
            "no half days, so for them the positional offsets V78..V1170 ARE the "
            "same time of day and the two readings agree - which is what keeps "
            "their pinned values comparable across R4 A7. FFF carries one "
            "early-close session of 39 bars and GGG one missing bar, and both "
            "have a volume series that depends only on the time of day, so their "
            "honest relative volume is exactly 1.00."
        ),
        "intentional_difference": (
            "None. This is a parity fixture: the expected values are computed by a "
            "second naive implementation in the builder, written from the trader's "
            "two formula lines rather than from strength_scan.py."
        ),
        "acquired_at": "2026-09-02T00:00:00+00:00",
        "as_of": "2026-06-16T13:00:00+00:00",
        "raw_input_keys": ["bars"],
        "expected_keys": ["expected"],
        "numeric_tolerance": 1e-4,
        "configuration": {
            "session_bars": SESSION_BARS,
            "sessions": SESSIONS,
            "body_bars": BODY_BARS,
            "atr_period": ATR_PERIOD,
            "rvol_prior_sessions": RVOL_PRIOR_SESSIONS,
            "early_close_bars": EARLY_CLOSE_BARS,
            "short_sessions": {
                symbol: {str(k): v for k, v in mapping.items()}
                for symbol, mapping in SHORT_SESSIONS.items()
            },
            "missing_bars": {
                symbol: {str(k): v for k, v in mapping.items()}
                for symbol, mapping in MISSING_BARS.items()
            },
        },
        "bars": bars,
        "expected": expected,
    }
    # A SINGLE `raw_input_key` hashes the VALUE, not `{key: value}` - see
    # `FixtureContract.raw_input`. Hashing the wrapper is the mistake the
    # contract's own loader catches on the first read.
    payload["raw_input_sha256"] = hashlib.sha256(
        json.dumps(bars, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate the fixture")
    args = parser.parse_args()
    payload = build_payload()
    if not args.write:
        print(json.dumps(payload["expected"], indent=1, sort_keys=True))
        return 0
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    # COMPACT, not pretty. Five symbols x 1,182 bars indented is a megabyte
    # of whitespace, and nobody reads a bar series by eye. What a reviewer
    # reads is the `expected` block, which is printed below on every write.
    FIXTURE.write_text(
        json.dumps(payload, sort_keys=True, separators=(",", ":")) + chr(10),
        encoding="utf-8",
    )
    print(f"wrote {FIXTURE} ({FIXTURE.stat().st_size} bytes)")
    print(json.dumps(payload["expected"], indent=1, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
