"""Build the TC2000 parity golden — Phase 0.14 packet V1, item 1.

Decision 0016 answer 9 makes the trader's own TC2000 scan the SPECIFICATION for
the Strength Board. This fixture is what "parity" means in numbers: five
symbols, sixteen sessions of M5 bars each, and the relative strength and relative
volume computed **by hand here** — from the formulas as the trader wrote them,
not by calling the module the test is checking.

That is the whole point. A golden generated by the code under test pins whatever
the code does, including its mistakes. These values are produced by a second,
deliberately naive implementation written straight from the trader's two lines:

    relative strength = AVG(((C/O) - 1) * 100, 12) * ((C + C50) / 2) / ATR50
    relative volume   = AVG(V / mean(V78, V156, ... V1170), 12)

Run with `--write` to regenerate, and READ THE DIFF: a change here is a change to
the trader's scan, not a refresh.

The bars are synthetic and deterministic. Real bars would make the fixture a
snapshot of one afternoon's tape and would need re-acquiring; synthetic bars with
a stated generator make every number reproducible by hand.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tests" / "fixtures" / "tc2000_parity_v1.json"

SESSION_BARS = 78
SESSIONS = 16
BODY_BARS = 12
ATR_PERIOD = 50
RVOL_PRIOR_SESSIONS = 15

#: Five deliberately different shapes. The generator is a plain arithmetic walk
#: so every bar is reproducible from these five numbers alone.
SYMBOLS = {
    #        base   drift    range  vol_base  vol_today
    "AAA": (100.0, 0.010, 0.30, 1000.0, 3000.0),
    "BBB": (50.0, 0.004, 0.20, 2000.0, 2200.0),
    "CCC": (250.0, -0.006, 0.90, 800.0, 400.0),
    "DDD": (12.5, 0.020, 0.08, 5000.0, 15000.0),
    "EEE": (7.5, 0.000, 0.05, 300.0, 300.0),
}


def build_bars(symbol: str) -> list[dict]:
    """Sixteen sessions of M5 bars. Deterministic, no randomness anywhere."""
    base, drift, span, vol_base, vol_today = SYMBOLS[symbol]
    bars: list[dict] = []
    price = base
    start = datetime(2026, 6, 1, 6, 30)
    for session in range(SESSIONS):
        day = start + timedelta(days=session)
        today = session == SESSIONS - 1
        for index in range(SESSION_BARS):
            stamp = day + timedelta(minutes=5 * index)
            open_price = price
            # A repeating body pattern, so the 12-bar average is a real average
            # over different bars rather than the same one twelve times.
            step = drift * (1.0 + ((index % 5) - 2) * 0.25)
            close_price = open_price * (1.0 + step)
            high = max(open_price, close_price) + span / 2.0
            low = min(open_price, close_price) - span / 2.0
            volume = vol_today if today else vol_base * (1.0 + (index % 7) * 0.05)
            bars.append(
                {
                    "dt": stamp.isoformat(),
                    "open": round(open_price, 6),
                    "high": round(high, 6),
                    "low": round(low, 6),
                    "close": round(close_price, 6),
                    "volume": round(volume, 6),
                }
            )
            price = close_price
    return bars


# ---------------------------------------------------------------------------
# The hand implementation. Written from the trader's two lines, not from the
# module under test.
# ---------------------------------------------------------------------------


def hand_strength(bars: list[dict]) -> float:
    closes = [bar["close"] for bar in bars]
    opens = [bar["open"] for bar in bars]

    body = sum(
        ((closes[-1 - step] / opens[-1 - step]) - 1.0) * 100.0
        for step in range(BODY_BARS)
    ) / BODY_BARS

    # C50 is the close FIFTY BARS AGO - a single historical price, never an SMA.
    c50 = closes[-1 - ATR_PERIOD]

    true_range = []
    for index in range(1, len(bars)):
        high = bars[index]["high"]
        low = bars[index]["low"]
        previous_close = bars[index - 1]["close"]
        true_range.append(
            max(high - low, abs(high - previous_close), abs(low - previous_close))
        )
    atr50 = sum(true_range[-ATR_PERIOD:]) / ATR_PERIOD

    return body * ((closes[-1] + c50) / 2.0) / atr50


def hand_rvol(bars: list[dict]) -> float:
    volumes = [bar["volume"] for bar in bars]
    ratios = []
    for step in range(BODY_BARS):
        index = len(volumes) - 1 - step
        prior = [
            volumes[index - SESSION_BARS * back]
            for back in range(1, RVOL_PRIOR_SESSIONS + 1)
        ]
        ratios.append(volumes[index] / (sum(prior) / RVOL_PRIOR_SESSIONS))
    return sum(ratios) / len(ratios)


def build_payload() -> dict:
    bars = {symbol: build_bars(symbol) for symbol in SYMBOLS}
    expected = {
        symbol: {
            "strength": round(hand_strength(rows), 6),
            "rvol": round(hand_rvol(rows), 6),
        }
        for symbol, rows in bars.items()
    }
    payload = {
        "schema": "tc2000_parity_v1",
        "feature_version": "strength_scan.v1_names_first",
        "universe_version": "synthetic-5",
        "provider_assumptions": (
            "Synthetic M5 bars generated by tests/build_tc2000_parity_fixture.py. "
            "78 bars per session, 16 sessions, no gaps and no half days - so the "
            "positional offsets V78..V1170 are also the same time of day, which "
            "is what makes the hand computation checkable."
        ),
        "intentional_difference": (
            "None. This is a parity fixture: the expected values are computed by a "
            "second naive implementation in the builder, written from the trader's "
            "two formula lines rather than from strength_scan.py."
        ),
        "acquired_at": "2026-09-02T00:00:00+00:00",
        "as_of": "2026-06-16T13:00:00+00:00",
        "raw_input_keys": ["bars"],
        "expected_keys": ["expected"],
        "numeric_tolerance": 1e-4,
        "configuration": {
            "session_bars": SESSION_BARS,
            "sessions": SESSIONS,
            "body_bars": BODY_BARS,
            "atr_period": ATR_PERIOD,
            "rvol_prior_sessions": RVOL_PRIOR_SESSIONS,
        },
        "bars": bars,
        "expected": expected,
    }
    # A SINGLE `raw_input_key` hashes the VALUE, not `{key: value}` - see
    # `FixtureContract.raw_input`. Hashing the wrapper is the mistake the
    # contract's own loader catches on the first read.
    payload["raw_input_sha256"] = hashlib.sha256(
        json.dumps(bars, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate the fixture")
    args = parser.parse_args()
    payload = build_payload()
    if not args.write:
        print(json.dumps(payload["expected"], indent=1, sort_keys=True))
        return 0
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    # COMPACT, not pretty. Five symbols x 1,182 bars indented is a megabyte
    # of whitespace, and nobody reads a bar series by eye. What a reviewer
    # reads is the `expected` block, which is printed below on every write.
    FIXTURE.write_text(
        json.dumps(payload, sort_keys=True, separators=(",", ":")) + chr(10),
        encoding="utf-8",
    )
    print(f"wrote {FIXTURE} ({FIXTURE.stat().st_size} bytes)")
    print(json.dumps(payload["expected"], indent=1, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
