"""Packet ST7 - the trader's three decisions become the tracker's defaults.

Written RED, on `main` at 68762909, before any of the flips exist.

ST3 and ST4 built `gap_aware_v2` / `prior_session_v2` / `first_actionable_v2`
as OPT-IN evidence with the shipped policy still the default. The trader took
the three decisions on 2026-09-06 (~21:15 PT): *"Yes a trade not yet completed
should say pending. A second entry after a first close is its own trade yes.
3. This one is up to your discretion."* - and the lead's discretion on (3) made
both execution repairs the default. ST7 is that flip and nothing wider.

What this file pins, item by item (ST7.1 / ST7.2):

1. ``selection_policy.DEFAULT_SELECTION_POLICY`` is ``first_actionable_v2``;
   ``execution_convention.DEFAULT_EXECUTION_CONVENTION`` is ``gap_aware_v2``
   and ``DEFAULT_LEVEL_KNOWLEDGE`` is ``prior_session_v2``. The v1 names keep
   their values and stay selectable.
2. A DEFAULT `build_recent_tracker_setup_family_rows` leaves a pending
   representative in ``n_pending`` and never grades it from `avg_closed_r`,
   and a re-entry after a closed attempt is its own episode.
3. A DEFAULT `recompute_tracker_setup_record` / `_evaluate_tracker_scenario_bar`
   books the gap OPEN, and does not book a target off a band that only its own
   close could have known.
4. The old policies CALLED BY NAME still reproduce the ST3 and ST4 goldens,
   and the default reproduces the new v2 goldens pinned here from `main`.
5. Every record carries ``execution_convention`` / ``level_knowledge`` and
   every family row carries ``selection_policy`` under the default - a default
   run no longer POPS the stamps (`legacy.py` `:7301-7308`), because a record
   that does not say which policy produced it is unreadable after a flip.
6. The ST4 cache rule survives the flip: a compact scoring projection written
   under the OLD default carries no policy stamp and is still read AS-IS, so
   the live scoring population does not collapse to zero.

**Nothing here is generated by the code under test.** The two new goldens
(`st7_v2_default_golden.json`, `st7_family_rows_v2_default_golden.csv`) were
pinned on `main` through the EXPLICIT v2 keyword arguments that already ship -
the same numbers the flip must produce by default - not from a branch that had
already flipped. `ST7_REGEN_GOLDEN=1` re-pins them; the door exists for the
tester and the reviewer and no build may use it.

The ST3 and ST4 fixture builders are IMPORTED rather than copied: a fixture
this file re-typed could drift away from the one the goldens were pinned on,
and then "the old policy still reproduces the golden" would prove nothing.
"""

from __future__ import annotations

import copy
import csv
import hashlib
import io
import json
import os
import sys
from datetime import date
from pathlib import Path

import pytest

ROOT_DIR = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT_DIR / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import master_avwap as m  # noqa: E402

from conftest import FIXTURES_DIR, load_fixture_contract  # noqa: E402

# --- the ST3 fixtures, by import (packet ST7's instruction) -----------------
from test_st3_execution_convention import (  # noqa: E402
    _band_move_setup,
    _band_moves_inside_its_own_bar_frame,
    _bar,
    _build_golden_daily_bars,
    _build_golden_setup,
    _canonical,
    _expected_r,
    _golden_frame,
    _json_plain,
    _reasons,
    _scenario as _st3_scenario,
    GOLDEN_GAP_IDX,
)

# --- the ST4 fixtures, by import -------------------------------------------
from test_st4_first_actionable import (  # noqa: E402
    _golden_setups,
    _rows_to_csv_text,
    _scenario as _st4_scenario,
    _setup as _st4_setup,
    GOLDEN_LOOKBACK_DAYS,
    GOLDEN_REFERENCE_DATE,
)

ST3_GOLDEN_NAME = "st3_replay_golden"
ST4_GOLDEN_CSV = FIXTURES_DIR / "st4_family_rows_golden.csv"

V2_RECORD_GOLDEN_NAME = "st7_v2_default_golden"
V2_FAMILY_ROWS_GOLDEN_CSV = FIXTURES_DIR / "st7_family_rows_v2_default_golden.csv"

#: Set to "1" to re-pin the two ST7 goldens. A door for the tester and the
#: reviewer; with it unset the golden tests assert, and no build sets it.
REGEN_ENV = "ST7_REGEN_GOLDEN"

#: The three stamps ST7.1 makes unconditional. They are compared BY NAME in
#: every golden test and excluded from the byte-identity comparison, so the
#: builder is free to stamp a record with all three or with the two a replay
#: actually chooses - and no stamp escapes assertion either way.
POLICY_STAMP_KEYS = ("execution_convention", "level_knowledge", "selection_policy")


def _sp():
    from master_avwap_lib import selection_policy

    return selection_policy


def _ec():
    from master_avwap_lib import execution_convention

    return execution_convention


def _without_stamps(record: dict) -> dict:
    stripped = dict(record)
    for key in POLICY_STAMP_KEYS:
        stripped.pop(key, None)
    return stripped


# ---------------------------------------------------------------------------
# 1 (ST7.1) - the three defaults ARE the v2 policies, and v1 keeps its name.
# ---------------------------------------------------------------------------
def test_the_tracker_defaults_are_the_repaired_policies_and_v1_keeps_its_name():
    policy = _sp()
    ec = _ec()

    assert policy.DEFAULT_SELECTION_POLICY == policy.SELECTION_FIRST_ACTIONABLE_V2
    assert ec.DEFAULT_EXECUTION_CONVENTION == ec.EXECUTION_GAP_AWARE_V2
    assert ec.DEFAULT_LEVEL_KNOWLEDGE == ec.LEVEL_KNOWLEDGE_PRIOR_SESSION_V2

    # The values themselves never move - a stamp written last month must still
    # mean what it meant.
    assert policy.SELECTION_CLOSED_FIRST_V1 == "closed_first_v1"
    assert policy.SELECTION_FIRST_ACTIONABLE_V2 == "first_actionable_v2"
    assert ec.EXECUTION_LITERAL_LEVEL_V1 == "literal_level_v1"
    assert ec.EXECUTION_GAP_AWARE_V2 == "gap_aware_v2"
    assert ec.LEVEL_KNOWLEDGE_SAME_SESSION_V1 == "same_session_v1"
    assert ec.LEVEL_KNOWLEDGE_PRIOR_SESSION_V2 == "prior_session_v2"

    # The old arm the comparison CLIs call "old" is still selectable by name.
    assert policy.resolve_policy(policy.SELECTION_CLOSED_FIRST_V1) == "closed_first_v1"
    assert ec.is_gap_aware(ec.EXECUTION_LITERAL_LEVEL_V1) is False
    assert ec.is_gap_aware(ec.EXECUTION_GAP_AWARE_V2) is True
    assert ec.uses_prior_session_levels(ec.LEVEL_KNOWLEDGE_SAME_SESSION_V1) is False
    assert ec.uses_prior_session_levels(ec.LEVEL_KNOWLEDGE_PRIOR_SESSION_V2) is True

    # ...and an EMPTY policy still resolves to the default rather than raising,
    # so an old row whose stamp is present and empty reads as the default.
    assert policy.resolve_policy("") == policy.SELECTION_FIRST_ACTIONABLE_V2

    # The compatibility entrypoint every caller actually imports moved too.
    assert m.DEFAULT_EXECUTION_CONVENTION == ec.EXECUTION_GAP_AWARE_V2
    assert m.DEFAULT_LEVEL_KNOWLEDGE == ec.LEVEL_KNOWLEDGE_PRIOR_SESSION_V2


# ---------------------------------------------------------------------------
# 2 (ST7.1) - pending stays pending, and a real second entry is its own trade.
# ---------------------------------------------------------------------------
PENDING_FAMILY = "avwape_bounce"
REENTRY_FAMILY = "post_earnings_52w_break"


def _pending_and_reentry_population() -> dict[str, dict]:
    """One thesis still running, one thesis entered twice.

    The pending thesis is the ST4 shape that made this decision necessary: the
    representative exit plan (`full_band2` on the primary stop) is still OPEN
    while an ALTERNATE plan on the same stop closed at -1.00R. Today the family
    row reports that -1.00R as the trade's result, so a position still on the
    books is counted as a realized loss.
    """
    pending = _st4_setup(
        symbol="NVDA", side="LONG", anchor_date="2026-01-02", scan_date="2026-01-05",
        setup_family=PENDING_FAMILY, setup_status="OPEN",
        scenarios=[
            _st4_scenario(scenario_id="a", stop_label="LOWER_1", exit_template_id="full_band2",
                          status="OPEN", total_r=0.4),
            _st4_scenario(scenario_id="b", stop_label="LOWER_1", exit_template_id="full_band3",
                          status="STOPPED", total_r=-1.0, exit_date="2026-01-13"),
        ],
    )
    first_attempt = _st4_setup(
        symbol="AMD", side="LONG", anchor_date="2026-01-02", scan_date="2026-01-05",
        setup_family=REENTRY_FAMILY, setup_status="CLOSED",
        scenarios=[
            _st4_scenario(scenario_id="c", stop_label="LOWER_1", exit_template_id="full_band2",
                          status="TARGET_HIT", total_r=2.0, exit_date="2026-01-09"),
        ],
    )
    # The first attempt was OUT on 01-09; this is a declared re-entry, not the
    # rescan of a live position.
    second_attempt = _st4_setup(
        symbol="AMD", side="LONG", anchor_date="2026-01-02", scan_date="2026-01-13",
        setup_family=REENTRY_FAMILY, setup_status="CLOSED",
        scenarios=[
            _st4_scenario(scenario_id="d", stop_label="LOWER_1", exit_template_id="full_band2",
                          status="TARGET_HIT", total_r=1.0, exit_date="2026-01-16"),
        ],
    )
    return {
        "pending": pending,
        "attempt_1": first_attempt,
        "attempt_2": second_attempt,
    }


def _row_for(rows, family):
    return next(row for row in rows if str(row.get("setup_family")) == family)


def test_a_default_family_build_leaves_a_pending_representative_ungraded_and_counts_the_reentry():
    population = _pending_and_reentry_population()

    # THE DEFAULT CALL - no policy keyword anywhere.
    rows = m.build_recent_tracker_setup_family_rows(
        population, reference_date=date(2026, 1, 20), lookback_days=45
    )

    pending_row = _row_for(rows, PENDING_FAMILY)
    assert int(pending_row["n_pending"] or 0) == 1
    assert int(pending_row["n_losses"] or 0) == 0, "a trade still on is not a loss"
    assert int(pending_row["n_wins"] or 0) == 0
    assert int(pending_row["n_flats"] or 0) == 0
    assert int(pending_row["closed_setups"] or 0) == 0
    assert pending_row["representative_closed_r"] is None
    assert pending_row["win_rate_closed_unweighted"] is None
    assert str(pending_row["selection_policy"]) == _sp().SELECTION_FIRST_ACTIONABLE_V2

    reentry_row = _row_for(rows, REENTRY_FAMILY)
    assert int(reentry_row["n_episodes"] or 0) == 2, "a second entry after a close is its own trade"
    assert int(reentry_row["n_observations"] or 0) == 2
    assert int(reentry_row["n_wins"] or 0) == 2
    assert int(reentry_row["n_losses"] or 0) == 0
    assert int(reentry_row["n_entry_sessions"] or 0) == 2

    # The old policy, BY NAME, still answers the way the desk answered
    # yesterday - the characterization the decision was taken against.
    old = m.build_recent_tracker_setup_family_rows(
        population,
        reference_date=date(2026, 1, 20),
        lookback_days=45,
        selection_policy=_sp().SELECTION_CLOSED_FIRST_V1,
    )
    old_pending = _row_for(old, PENDING_FAMILY)
    assert int(old_pending["n_losses"] or 0) == 1
    assert int(old_pending["n_pending"] or 0) == 0
    assert old_pending["representative_closed_r"] == pytest.approx(-1.0)
    old_reentry = _row_for(old, REENTRY_FAMILY)
    assert int(old_reentry["n_episodes"] or 0) == 1
    assert int(old_reentry["n_observations"] or 0) == 2


# ---------------------------------------------------------------------------
# 3 (ST7.1) - the default replay books reachable prices off known levels.
# ---------------------------------------------------------------------------
def test_a_default_replay_books_the_gap_open_and_refuses_a_same_session_band():
    ec = _ec()

    # (a) the review fixture, through the bar evaluator's SHIPPED signature:
    # entry 100, risk 5, hard stop 95, next bar O80/H85/L79/C82. The bar never
    # traded at 95; -4.014R is derived from the shipped cost constants.
    gap_bar = _bar(open_=80, high=85, low=79, close=82)
    scenario = _st3_scenario(hard_stop_r_multiple=1.0)
    events = m._evaluate_tracker_scenario_bar(
        scenario, "LONG", "2026-01-05", gap_bar, None, None, is_entry_day=False, bar_index=2
    )
    assert _reasons(events) == ["HARD_STOP"]
    assert events[0]["price"] == pytest.approx(80.0)
    assert events[0]["fill_basis"] == ec.FILL_BASIS_GAP_OPEN
    assert events[0]["execution_convention"] == ec.EXECUTION_GAP_AWARE_V2
    assert scenario["realized_r"] == pytest.approx(_expected_r(100.0, 80.0, 100, 1.0, 500.0))
    assert scenario["realized_r"] == pytest.approx(-4.014)

    # (b) the same repair through the whole record replay, on the ST3 golden
    # setup whose bar 32 gaps clean through the stop.
    bars = _build_golden_daily_bars()
    setup = _build_golden_setup(bars)
    record = m.recompute_tracker_setup_record(copy.deepcopy(setup), _golden_frame(bars))
    booked = record["scenarios"]["full_band3"]["events"]
    stops = [event for event in booked if event["reason"] == "HARD_STOP"]
    assert stops, "the gap bar still stops the scenario out"
    gap_open = float(bars[GOLDEN_GAP_IDX]["open"])
    assert stops[0]["price"] == pytest.approx(gap_open)
    assert stops[0]["fill_basis"] == ec.FILL_BASIS_GAP_OPEN

    # (c) the same-session band: day D's UPPER_3 is inside D's own range only
    # because D's own bar was folded into the cumulative sums. The default no
    # longer books that target.
    df, anchor, prev_key = _band_moves_inside_its_own_bar_frame()
    day_key = df.iloc[-1]["datetime"].date().isoformat()
    history = m.calc_anchored_vwap_band_history(df, anchor)
    assert (
        float(history[day_key]["bands"]["UPPER_3"])
        < float(df.iloc[-1]["high"])
        < float(history[prev_key]["bands"]["UPPER_3"])
    ), "the fixture's premise: today's band is reachable, yesterday's is not"

    band_setup = _band_move_setup(df, anchor, prev_key)
    replayed = m.recompute_tracker_setup_record(copy.deepcopy(band_setup), df)
    repaired = replayed["scenarios"]["s1"]
    assert _reasons(repaired["events"]) == []
    assert m._scenario_is_open(repaired["status"])

    # The old convention, BY NAME, still books both - the arm the comparison
    # CLIs call "old" is reproducible forever.
    old_band = m.recompute_tracker_setup_record(
        copy.deepcopy(band_setup),
        df,
        level_knowledge=ec.LEVEL_KNOWLEDGE_SAME_SESSION_V1,
    )
    assert _reasons(old_band["scenarios"]["s1"]["events"]) == ["FINAL_TARGET"]
    old_scenario = _st3_scenario(hard_stop_r_multiple=1.0)
    old_events = m._evaluate_tracker_scenario_bar(
        old_scenario, "LONG", "2026-01-05", _bar(open_=80, high=85, low=79, close=82),
        None, None, is_entry_day=False, bar_index=2,
        execution_convention=ec.EXECUTION_LITERAL_LEVEL_V1,
    )
    assert old_events[0]["price"] == pytest.approx(95.0)
    assert old_scenario["realized_r"] == pytest.approx(-1.014)


# ---------------------------------------------------------------------------
# 4 (ST7.2) - v1 by name reproduces the old goldens; the default reproduces
#             the new ones, pinned here from `main` through the explicit v2
#             keywords that already ship.
# ---------------------------------------------------------------------------
def _v2_record() -> dict:
    """The record the flip must produce, computed the way `main` can already
    compute it: the explicit v2 keywords."""
    ec = _ec()
    bars = _build_golden_daily_bars()
    setup = _build_golden_setup(bars)
    return m.recompute_tracker_setup_record(
        copy.deepcopy(setup),
        _golden_frame(bars),
        execution_convention=ec.EXECUTION_GAP_AWARE_V2,
        level_knowledge=ec.LEVEL_KNOWLEDGE_PRIOR_SESSION_V2,
    )


def _write_v2_record_golden(path: Path) -> None:  # pragma: no cover - tester door
    bars = _build_golden_daily_bars()
    setup = _build_golden_setup(bars)
    payload = {
        "schema": "st7_v2_default_golden/1",
        "feature_version": "tracker_replay_gap_aware_v2_prior_session_v2",
        "raw_input_keys": ["daily_bars", "setup"],
        "raw_input_sha256": "",
        "acquired_at": "2026-09-06T00:00:00-07:00",
        "universe_version": "synthetic-single-symbol-STTEST",
        "provider_assumptions": (
            "No provider. The SAME synthetic daily bars as st3_replay_golden, "
            "replayed on `main` at 68762909 through the EXPLICIT "
            "execution_convention=gap_aware_v2 / level_knowledge=prior_session_v2 "
            "keywords that already shipped - never from a branch that had "
            "already flipped the defaults."
        ),
        "as_of": "2026-09-06T00:00:00-07:00",
        "expected_keys": ["record"],
        "numeric_tolerance": 0.0,
        "intentional_difference": (
            "This IS the intentional difference from st3_replay_golden: the "
            "hard stop books the gap open instead of a level the bar never "
            "traded, and intrabar band tests read the prior session. Packet "
            "ST7 makes it the default; decision 00NN, 2026-09-06."
        ),
        "daily_bars": bars,
        "setup": _json_plain(setup),
        "record": _json_plain(_without_stamps(_v2_record())),
    }
    digest_payload = {key: payload[key] for key in payload["raw_input_keys"]}
    payload["raw_input_sha256"] = hashlib.sha256(
        json.dumps(digest_payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _v2_family_rows() -> list[dict]:
    return m.build_recent_tracker_setup_family_rows(
        _golden_setups(),
        reference_date=GOLDEN_REFERENCE_DATE,
        lookback_days=GOLDEN_LOOKBACK_DAYS,
        selection_policy=_sp().SELECTION_FIRST_ACTIONABLE_V2,
    )


def _write_v2_family_rows_golden(path: Path) -> None:  # pragma: no cover - tester door
    rows = _v2_family_rows()
    columns = list(rows[0].keys())
    path.write_text(_rows_to_csv_text(rows, columns), encoding="utf-8")


def test_the_old_policies_by_name_reproduce_the_goldens_and_the_default_matches_the_new_pin():
    if os.environ.get(REGEN_ENV) == "1":  # pragma: no cover - tester/reviewer door
        _write_v2_record_golden(FIXTURES_DIR / f"{V2_RECORD_GOLDEN_NAME}.json")
        _write_v2_family_rows_golden(V2_FAMILY_ROWS_GOLDEN_CSV)

    policy = _sp()
    ec = _ec()

    # ---- (a) the ST3 replay golden, under the OLD convention BY NAME -------
    st3 = load_fixture_contract(ST3_GOLDEN_NAME)
    bars = st3["daily_bars"]
    st3_setup = st3["setup"]
    frame = _golden_frame(bars)

    old_record = m.recompute_tracker_setup_record(
        copy.deepcopy(st3_setup),
        frame,
        execution_convention=ec.EXECUTION_LITERAL_LEVEL_V1,
        level_knowledge=ec.LEVEL_KNOWLEDGE_SAME_SESSION_V1,
    )
    assert _canonical(_without_stamps(old_record)) == _canonical(_without_stamps(st3["record"]))
    # ...and the record NAMES the policy that produced it (ST7.1: the stamps
    # are no longer popped, so v1 is legible after the flip).
    assert old_record["execution_convention"] == ec.EXECUTION_LITERAL_LEVEL_V1
    assert old_record["level_knowledge"] == ec.LEVEL_KNOWLEDGE_SAME_SESSION_V1

    # ---- (b) the ST4 family-rows golden, under the OLD policy BY NAME ------
    st4_golden_text = ST4_GOLDEN_CSV.read_text(encoding="utf-8")
    st4_columns = next(csv.reader(io.StringIO(st4_golden_text)))
    old_rows = m.build_recent_tracker_setup_family_rows(
        _golden_setups(),
        reference_date=GOLDEN_REFERENCE_DATE,
        lookback_days=GOLDEN_LOOKBACK_DAYS,
        selection_policy=policy.SELECTION_CLOSED_FIRST_V1,
    )
    assert _rows_to_csv_text(old_rows, st4_columns) == st4_golden_text

    # ---- (c) the DEFAULT now reproduces the new v2 pins --------------------
    v2 = load_fixture_contract(V2_RECORD_GOLDEN_NAME)
    assert _canonical(v2["daily_bars"]) == _canonical(bars)
    assert _canonical(v2["setup"]) == _canonical(st3_setup)
    # The pin is worth having: it really differs from the v1 golden.
    assert _canonical(v2["record"]) != _canonical(_without_stamps(st3["record"]))

    default_record = m.recompute_tracker_setup_record(copy.deepcopy(st3_setup), frame)
    assert _canonical(_without_stamps(default_record)) == _canonical(v2["record"])
    assert default_record["execution_convention"] == ec.EXECUTION_GAP_AWARE_V2
    assert default_record["level_knowledge"] == ec.LEVEL_KNOWLEDGE_PRIOR_SESSION_V2

    v2_csv_text = V2_FAMILY_ROWS_GOLDEN_CSV.read_text(encoding="utf-8")
    v2_columns = next(csv.reader(io.StringIO(v2_csv_text)))
    assert v2_csv_text != st4_golden_text, "the new default really moves the rows"
    default_rows = m.build_recent_tracker_setup_family_rows(
        _golden_setups(),
        reference_date=GOLDEN_REFERENCE_DATE,
        lookback_days=GOLDEN_LOOKBACK_DAYS,
    )
    assert _rows_to_csv_text(default_rows, v2_columns) == v2_csv_text

    # ---- (d) no residue: the old arm is still the old arm afterwards -------
    again = m.recompute_tracker_setup_record(
        copy.deepcopy(st3_setup),
        frame,
        execution_convention=ec.EXECUTION_LITERAL_LEVEL_V1,
        level_knowledge=ec.LEVEL_KNOWLEDGE_SAME_SESSION_V1,
    )
    assert _canonical(_without_stamps(again)) == _canonical(_without_stamps(st3["record"]))


# ---------------------------------------------------------------------------
# 5 (ST7.1) - every record and every row says which policy produced it.
# ---------------------------------------------------------------------------
def test_every_record_and_family_row_carries_its_policy_stamps_under_the_default():
    ec = _ec()
    policy = _sp()

    bars = _build_golden_daily_bars()
    setup = _build_golden_setup(bars)
    frame = _golden_frame(bars)

    # A DEFAULT replay no longer pops the two execution stamps.
    default_record = m.recompute_tracker_setup_record(copy.deepcopy(setup), frame)
    assert default_record["execution_convention"] == ec.EXECUTION_GAP_AWARE_V2
    assert default_record["level_knowledge"] == ec.LEVEL_KNOWLEDGE_PRIOR_SESSION_V2

    # ...and neither does an explicit OLD-policy replay: after the flip a
    # record with no stamp is ambiguous, so v1 has to say so too.
    old_record = m.recompute_tracker_setup_record(
        copy.deepcopy(setup),
        frame,
        execution_convention=ec.EXECUTION_LITERAL_LEVEL_V1,
        level_knowledge=ec.LEVEL_KNOWLEDGE_SAME_SESSION_V1,
    )
    assert old_record["execution_convention"] == ec.EXECUTION_LITERAL_LEVEL_V1
    assert old_record["level_knowledge"] == ec.LEVEL_KNOWLEDGE_SAME_SESSION_V1

    # Every family row carries the selection policy under the default.
    rows = m.build_recent_tracker_setup_family_rows(
        _pending_and_reentry_population(),
        reference_date=date(2026, 1, 20),
        lookback_days=45,
    )
    assert rows
    for row in rows:
        assert row["selection_policy"] == policy.SELECTION_FIRST_ACTIONABLE_V2

    # And the summary the scoring projection freezes into the snapshot says it
    # too - that projection is the ONLY copy of the answer for the live
    # scoring path, so an unstamped one cannot be told apart from an old one.
    summary = m._summarize_tracker_setup_outcome(
        _pending_and_reentry_population()["pending"]
    )
    assert summary["selection_policy"] == policy.SELECTION_FIRST_ACTIONABLE_V2
    assert summary["representative_status"] == "pending"

    scoring_payload = m.build_setup_tracker_scoring_payload(
        {"setups": _pending_and_reentry_population()}
    )
    projected = scoring_payload["setups"]["pending"]["_scoring_outcome_summary"]
    assert projected["selection_policy"] == policy.SELECTION_FIRST_ACTIONABLE_V2
    assert projected["representative_status"] == "pending"


# ---------------------------------------------------------------------------
# 6 (ST7.1) - the ST4 cache rule survives the flip.
# ---------------------------------------------------------------------------
def _old_compact_projection(stamp_shape: str) -> dict:
    """A record as `master_avwap_tracker_scoring_snapshot.json` holds it.

    No `scenarios` key AT ALL - the projection is compact - and a summary
    written BEFORE ST4 existed, so its policy stamp is either absent (the
    column did not exist) or present and empty (a row half-migrated). Both
    shapes are on disk somewhere; neither may cause a recompute, because the
    recompute finds no scenarios and drops the setup (32 recent family rows ->
    0, measured 2026-09-06).
    """
    source = _st4_setup(
        symbol="NVDA", side="LONG", anchor_date="2026-01-02", scan_date="2026-01-05",
        setup_family=PENDING_FAMILY, setup_status="CLOSED",
        scenarios=[
            _st4_scenario(scenario_id="a", stop_label="LOWER_1", exit_template_id="full_band2",
                          status="TARGET_HIT", total_r=2.0, exit_date="2026-01-09"),
        ],
    )
    projection = m._tracker_scoring_setup_projection(source)
    assert "scenarios" not in projection
    summary = projection["_scoring_outcome_summary"]
    for key in ("selection_policy", "as_of_session"):
        if stamp_shape == "absent":
            summary.pop(key, None)
        else:
            summary[key] = ""
    return projection


@pytest.mark.parametrize("stamp_shape", ["absent", "present_and_empty"])
def test_a_compact_projection_without_a_policy_stamp_is_still_read_as_is(stamp_shape):
    policy = _sp()
    projection = _old_compact_projection(stamp_shape)
    cached = copy.deepcopy(projection["_scoring_outcome_summary"])

    # The default read takes the cache UNCONDITIONALLY - the ST4 rule, now
    # exercised under the NEW default, which is the policy that used to take
    # the `unknown_compact` bypass.
    default_summary = m._summarize_tracker_setup_outcome(projection)
    assert default_summary == cached
    assert default_summary.get("representative_status") != "unknown_compact"

    # Naming the new default explicitly is the same read.
    named = m._summarize_tracker_setup_outcome(
        projection, policy=policy.SELECTION_FIRST_ACTIONABLE_V2
    )
    assert named == cached

    # And the population does not collapse: the family build still counts it.
    rows = m.build_recent_tracker_setup_family_rows(
        {"compact": copy.deepcopy(projection)},
        reference_date=date(2026, 1, 20),
        lookback_days=45,
    )
    assert len(rows) == 1
    row = rows[0]
    assert int(row["n_episodes"] or 0) == 1
    assert "unknown_compact" not in str(row["excluded_reasons"])
    assert int(row["n_excluded"] or 0) == 0

    # The bypass itself is NOT removed - it is what a read that cannot be
    # answered from the cache still says. An `as_of` replay of a compact
    # record has to look at scenarios that are not there, and names that
    # rather than grading a trade it could not have seen.
    replayed = m._summarize_tracker_setup_outcome(projection, as_of_session="2026-01-07")
    assert replayed["representative_status"] == "unknown_compact"
