"""TJ-17D -- a kept idea becomes one measured weekly change.  RED first.

The fixtures are hand-written.  They deliberately keep the old state shape,
then exercise the public writer/read seams that the card will use.
"""

from __future__ import annotations

import json
import os
import sys
import threading
import time
from dataclasses import replace
from datetime import datetime, timezone
from pathlib import Path

import pytest


ROOT_DIR = Path(__file__).resolve().parents[1]
for _extra in (ROOT_DIR / "scripts", ROOT_DIR / "tests"):
    if str(_extra) not in sys.path:
        sys.path.insert(0, str(_extra))

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

import tj6_support as fx  # noqa: E402


SESSION = "2026-09-18"  # Friday; the next exchange session is Monday the 21st.
NEXT_SESSION = "2026-09-21"
ENVIRONMENT = "trending_up"
MEASURABLE = "read_accuracy_rest_of_day"
SECOND_MEASURABLE = "trade_win_rate_day"
NOW = datetime(2026, 9, 19, 18, 0, tzinfo=timezone.utc)


def _reading(name, *, start_session=None, end_session="", scope=None, **_kwargs):
    """A known owner reading: 30 of 40 before, 35 of 50 after.

    These are counts, not a number generated by the feature under test.  The
    explicit scope and source ids make a future reader prove it did not guess
    an environment from an idea sentence.
    """
    after = bool(start_session)
    hits, total = (35, 50) if after else (30, 40)
    return {
        "measurable": str(name),
        "value": hits / total,
        "hits": hits,
        "n": total,
        "measured": True,
        "unit": "fraction",
        "better": "higher",
        "scope": dict(scope or {"environment": "all"}),
        "start_session": str(start_session or "2026-08-24"),
        "end_session": str(end_session or SESSION),
        "source": {"read_ids": ["read-1", "read-2"], "trade_ids": ["trade-9"]},
    }


def _install_kept_process_ideas(monkeypatch, tmp_path):
    """Two real stored process rows and their ordinary Keep records."""
    from ai_jobs import improvement_ideas

    paths = fx.install_stores(monkeypatch, tmp_path, write_the_week=False)
    monkeypatch.setattr(
        improvement_ideas, "measure", _reading,
    )
    first = fx.stored_idea_row(
        "Wait for a confirmed D1 turn before acting.",
        session=SESSION,
        measurable=MEASURABLE,
    )
    second = fx.stored_idea_row(
        "Write the exit reason before reviewing the next chart.",
        session=SESSION,
        measurable=SECOND_MEASURABLE,
    )
    fx.write_ideas(paths["ideas"], [first, second])
    improvement_ideas.keep_idea(first["idea_id"], end_session=SESSION, now=NOW)
    improvement_ideas.keep_idea(second["idea_id"], end_session=SESSION, now=NOW)
    return paths, first, second


def test_named_weekly_measurables_preserve_counts_units_direction_and_scope(monkeypatch):
    """Four explicit readers must remain closed and report their own counts.

    The old two TJ-6 readers remain.  A missing owner is unmeasured rather than
    0%, while a measured scoped reading retains 35/50 = 0.70 and its source.
    """
    from ai_jobs import improvement_ideas

    names = set(improvement_ideas.measurable_names())
    assert {
        "read_accuracy_rest_of_day",
        "read_accuracy_next_5_sessions",
        "trade_win_rate_day",
        "trade_win_rate_swing",
    } <= names

    # The B-owned window reader is deliberately a boundary stub on this branch.
    # Its output is what the public measurement must preserve, never invent.
    monkeypatch.setattr(improvement_ideas, "_resolve", lambda _reader: object())
    item = improvement_ideas.measurable_named("read_accuracy_rest_of_day")
    monkeypatch.setattr(
        improvement_ideas, "MEASURABLES", (replace(item, read=_reading),), raising=False
    )
    reading = improvement_ideas.measure(
        "read_accuracy_rest_of_day",
        end_session=SESSION,
        sessions=5,
        start_session=NEXT_SESSION,
        scope={"environment": ENVIRONMENT},
    )
    assert reading["value"] == 0.70
    assert (reading["hits"], reading["n"]) == (35, 50)
    assert reading["unit"] == "fraction"
    assert reading["better"] == "higher"
    assert reading["scope"] == {"environment": ENVIRONMENT}
    assert reading["source"]["read_ids"] == ["read-1", "read-2"]


def test_weekly_choice_refuses_second_active_change_and_keeps_original_baseline_bytes(monkeypatch, tmp_path):
    """One exchange week permits one active choice; the same click is harmless.

    The first normal Keep baseline is 30/40.  Choosing one change freezes a
    separate scope-aware baseline, but attempting a different choice leaves the
    entire state file byte-for-byte as it stood before that rejected click.
    """
    from ai_jobs import improvement_ideas

    paths, first, second = _install_kept_process_ideas(monkeypatch, tmp_path)
    original = json.dumps(
        improvement_ideas.read_state()[first["idea_id"]]["baseline"], sort_keys=True
    ).encode("utf-8")

    chosen = improvement_ideas.choose_weekly_change(
        first["idea_id"], end_session=SESSION, environment=ENVIRONMENT, now=NOW
    )
    assert chosen["choice_baseline"]["value"] == 0.75
    assert chosen["choice_baseline"]["scope"] == {"environment": ENVIRONMENT}
    assert chosen["observation_start"] == NEXT_SESSION
    assert (
        json.dumps(improvement_ideas.read_state()[first["idea_id"]]["baseline"], sort_keys=True)
        .encode("utf-8")
        == original
    )
    assert improvement_ideas.choose_weekly_change(
        first["idea_id"], end_session=SESSION, environment=ENVIRONMENT, now=NOW
    ) == chosen

    before_conflict = paths["state"].read_bytes()
    with pytest.raises(improvement_ideas.WeeklyChoiceConflict):
        improvement_ideas.choose_weekly_change(second["idea_id"], end_session=SESSION, now=NOW)
    assert paths["state"].read_bytes() == before_conflict


def test_follow_through_is_append_only_correctable_and_absent_sessions_are_unknown(monkeypatch, tmp_path):
    """A late correction appends a second event and never turns absence into no.

    Hand-counted for this choice: Monday yes, Tuesday first no then corrected
    to yes, Wednesday absent.  The latest reader therefore reports 2 yes, 0
    no, and 1 unknown across three distinct requested sessions.
    """
    import project_paths
    from ai_jobs import improvement_ideas

    paths, first, _second = _install_kept_process_ideas(monkeypatch, tmp_path)
    follow_path = tmp_path / "follow_through.jsonl"
    monkeypatch.setattr(project_paths, "IDEA_FOLLOW_THROUGH_FILE", follow_path, raising=False)
    improvement_ideas.choose_weekly_change(first["idea_id"], end_session=SESSION, now=NOW)

    improvement_ideas.record_follow_through(first["idea_id"], "2026-09-21", True, now=NOW)
    improvement_ideas.record_follow_through(first["idea_id"], "2026-09-22", False, now=NOW)
    initial = follow_path.read_bytes()
    improvement_ideas.record_follow_through(first["idea_id"], "2026-09-22", True, note="fixed", now=NOW)
    assert follow_path.read_bytes().startswith(initial)

    row = next(item for item in improvement_ideas.checked_ideas(end_session="2026-09-23") if item["idea_id"] == first["idea_id"])
    follow = row["current_choice"]["follow_through"]
    assert follow["by_session"]["2026-09-21"] == "yes"
    assert follow["by_session"]["2026-09-22"] == "yes"
    assert follow["by_session"]["2026-09-23"] == "unknown"
    assert follow["counts"] == {"yes": 2, "no": 0, "unknown": 1}
    assert len(follow_path.read_text(encoding="utf-8").splitlines()) == 3


def test_checked_choice_compares_only_after_start_in_the_same_horizon_and_environment(monkeypatch, tmp_path):
    """The comparison must never overlap its frozen before sample.

    The checked row carries its exact date windows, same environment and named
    horizon.  A pending/missing after sample says waiting, never 0% or caused.
    """
    from ai_jobs import improvement_ideas

    _paths, first, _second = _install_kept_process_ideas(monkeypatch, tmp_path)
    improvement_ideas.choose_weekly_change(
        first["idea_id"], end_session=SESSION, environment=ENVIRONMENT, now=NOW
    )
    row = next(item for item in improvement_ideas.checked_ideas(end_session="2026-09-23") if item["idea_id"] == first["idea_id"])
    current = row["current_choice"]
    assert current["before"]["dates"]
    assert current["after"]["dates"]
    assert set(current["before"]["dates"]).isdisjoint(current["after"]["dates"])
    assert min(current["after"]["dates"]) >= NEXT_SESSION
    assert current["before"]["scope"] == current["after"]["scope"] == {"environment": ENVIRONMENT}
    assert current["before"]["measurable"] == current["after"]["measurable"] == MEASURABLE
    assert current["comparison"] in {"higher", "lower", "no clear change", "waiting", "too few to call"}
    assert "caused" not in current["comparison"].lower()


pytestmark = pytest.mark.qt
pytest.importorskip("PySide6", reason="the ideas card is a PySide6 widget")
from PySide6.QtWidgets import QApplication, QPushButton  # noqa: E402


@pytest.fixture(scope="module")
def qapp():
    return QApplication.instance() or QApplication([])


def test_active_idea_row_has_explicit_actions_and_disables_every_new_action_while_writing(qapp):
    """The same row is the write surface on Day and Week Review.

    A real Keep write is held open.  An active row arriving during it must show
    Use/Followed/Did not follow/Not sure/Finish and every one is grey until the
    off-Qt write ends.
    """
    from ui.widgets.ideas_card import IdeasCard

    gate = threading.Event()
    started = threading.Event()

    def writer(_idea_id, _status):
        started.set()
        gate.wait(5.0)

    card = IdeasCard(writer=writer)
    try:
        card.show_ideas([{"idea_id": "a", "kind": "process", "text": "First", "status": ""}])
        card.rows[0].keep_button.click()
        assert started.wait(5.0)
        card.show_ideas(
            [{
                "idea_id": "a",
                "kind": "process",
                "text": "First",
                "status": "kept",
                "current_choice": {"observation_start": NEXT_SESSION, "week": "2026-W39"},
            }]
        )
        labels = {button.text(): button for button in card.findChildren(QPushButton)}
        expected = {"Use this week", "Followed today", "Did not follow", "Not sure", "Finish this change"}
        assert expected <= set(labels)
        assert all(labels[label].isEnabled() is False for label in expected)
    finally:
        gate.set()
        deadline = time.perf_counter() + 5.0
        while card.is_writing() and time.perf_counter() < deadline:
            qapp.processEvents()
            time.sleep(0.01)
        card.shutdown()
        card.deleteLater()
        qapp.processEvents()
