"""WS-SN3 - one RRS pass per cycle (WISHLIST item 4, required result 3).

These tests are written BEFORE the fix and must fail on the pre-SN3 code.

Today ``run_strategy`` enters ``run_rrs_scan`` FOUR times a cycle (5m, 15m, 1h
and then the GUI's selected timeframe, which is one of the three).  Each entry
walks the whole universe, re-aggregates the same 5-minute bars and rebuilds
``_build_intraday_rrs_profile`` for every symbol from scratch - 275 s of pure
CPU per cycle on 2026-09-08, on the same interpreter lock the GUI needs.

What SN3 has to deliver, and therefore what these tests pin:

1. ONE walk of the universe produces the 5m, 15m and 1h results, and each of
   them is BYTE-IDENTICAL to what the four-pass code produced from the same
   bars.  The recorded four-pass output lives in
   ``tests/fixtures/ws_sn3_rrs_four_pass.json``, generated from the PRE-FIX
   code at the commit pinned in ``PINNED_SOURCE_COMMIT`` below.  The fixture
   carries that commit, and the fixture-provenance test refuses any fixture
   regenerated by the code it is meant to pin.
2. ``run_rrs_scan`` is entered ONCE per scan cycle.
3. The GUI's selected timeframe REUSES the matching timeframe's result - the
   same payload OBJECT, not a recomputed equal one - and is still handed to
   the GUI under the ``rrs_snapshot`` tag, which is what ``bounce_service``
   turns into ``rrsSnapshotChanged`` for the RS Window tab.
4. ``_build_intraday_rrs_profile`` is cached per symbol, keyed on that symbol's
   last bar dt: a moved dt rebuilds, an unmoved one does not.

The seam the builder is expected to add (used by tests 1, 3, 4 and 5):
``BounceBot.rrs_payload_for(timeframe_key)`` returns the payload that
timeframe produced in the current cycle, and ``bot.latest_rrs_payload`` IS
``bot.rrs_payload_for(bot.rrs_timeframe_key)``.

Nothing here touches a live store: every bar is synthetic, every file-reading
and IB-touching seam is stubbed, and ``request_historical_bars`` raises if the
RRS pass ever reaches for a bar.
"""

from __future__ import annotations

import json
import os
import random
import sys
import threading
from datetime import date, datetime, timedelta
from pathlib import Path
from unittest.mock import Mock

import pytest

ROOT_DIR = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT_DIR / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import bounce_bot  # noqa: E402

FIXTURE_PATH = Path(__file__).resolve().parent / "fixtures" / "ws_sn3_rrs_four_pass.json"

# The commit the fixture was recorded at - the LAST commit before any SN3 code
# change.  A fixture regenerated by the fix is a self-portrait, so this literal
# is the guard: change the code, not the pin.
PINNED_SOURCE_COMMIT = "204f464071e5a0892fffdd23e9d4c1ef5d64c3ad"

# --- the recorded synthetic universe -------------------------------------

SESSION_DATES = (date(2026, 6, 1), date(2026, 6, 2), date(2026, 6, 3))
SESSION_OPEN_HOUR = 6  # market-local (Pacific) naive, as the desk's bars are
SESSION_OPEN_MINUTE = 30
BARS_PER_SESSION = 78  # 06:30 .. 12:55 inclusive, 5-minute bars

SPY_SYMBOL = "SPY"
SECTOR_ETF_MAP = {
    "technology": "XLK",
    "financial-services": "XLF",
    "energy": "XLE",
}
INDUSTRY_ETF_MAP_FILE = {
    "yahoo_industryKey_to_ref": {
        "semiconductors": {"sectorKey": "technology", "etf": "SMH"},
        "banks-regional": {"sectorKey": "financial-services", "etf": "KRE"},
        "oil-gas-equipment-services": {"sectorKey": "energy", "etf": "OIH"},
    }
}
CLASSIFICATIONS = {
    "NVDA": ("technology", "Technology", "semiconductors", "Semiconductors"),
    "AMD": ("technology", "Technology", "semiconductors", "Semiconductors"),
    "MU": ("technology", "Technology", "semiconductors", "Semiconductors"),
    "WFC": ("financial-services", "Financial Services", "banks-regional", "Banks - Regional"),
    "RF": ("financial-services", "Financial Services", "banks-regional", "Banks - Regional"),
    "SLB": ("energy", "Energy", "oil-gas-equipment-services", "Oil & Gas Equipment & Services"),
}
LONGS = ["NVDA", "MU", "WFC"]
SHORTS = ["AMD", "RF", "SLB"]
ETF_SYMBOLS = ("XLK", "XLF", "XLE", "SMH", "KRE", "OIH")

# seed, start price, per-bar drift in price units
SERIES_RECIPE = {
    SPY_SYMBOL: (11, 500.0, 0.004),
    "NVDA": (21, 120.0, 0.030),
    "AMD": (22, 150.0, -0.028),
    "MU": (23, 95.0, 0.018),
    "WFC": (24, 60.0, 0.012),
    "RF": (25, 22.0, -0.014),
    "SLB": (26, 44.0, -0.020),
    "XLK": (31, 240.0, 0.010),
    "XLF": (32, 48.0, 0.003),
    "XLE": (33, 92.0, -0.006),
    "SMH": (41, 270.0, 0.014),
    "KRE": (42, 58.0, 0.002),
    "OIH": (43, 310.0, -0.009),
}

GROUP_STRENGTH_STUB = {"M5": {"sectors": [], "industries": []}}
MARKET_INTERNALS_STUB = {"as_of": "2026-06-03T12:55", "rows": []}
GUI_TIMEFRAME_KEY = "15m"
CYCLE_TIMEFRAMES = ("5m", "15m", "1h")


def _session_bar_times(session_date, count=BARS_PER_SESSION):
    start = datetime(
        session_date.year,
        session_date.month,
        session_date.day,
        SESSION_OPEN_HOUR,
        SESSION_OPEN_MINUTE,
    )
    return [start + timedelta(minutes=5 * i) for i in range(count)]


def _build_series(symbol, *, sessions=SESSION_DATES, extra_bars=0):
    """A deterministic OHLC walk that respects low <= open, close <= high."""
    seed, price, drift = SERIES_RECIPE[symbol]
    rng = random.Random(seed)
    times = []
    for session_date in sessions:
        times.extend(_session_bar_times(session_date))
    if extra_bars:
        last = times[-1]
        times.extend(last + timedelta(minutes=5 * (i + 1)) for i in range(extra_bars))
    bars = []
    for index, dt in enumerate(times):
        open_ = price
        step = drift + rng.uniform(-0.35, 0.35) * (open_ * 0.002)
        close = round(open_ + step, 4)
        span = abs(open_ * 0.0012) + abs(step) * 0.6 + 0.01
        high = round(max(open_, close) + rng.uniform(0.05, 1.0) * span, 4)
        low = round(min(open_, close) - rng.uniform(0.05, 1.0) * span, 4)
        bars.append(
            bounce_bot.IbBar(
                dt=dt,
                open=round(open_, 4),
                high=high,
                low=low,
                close=close,
                volume=float(10_000 + index),
            )
        )
        price = close
    return bars


def _recorded_universe(extra_bars_for=None):
    """symbol -> bars.  ``extra_bars_for`` grows only the named symbols."""
    extra = dict(extra_bars_for or {})
    universe = {}
    for symbol in (SPY_SYMBOL, *LONGS, *SHORTS, *ETF_SYMBOLS):
        universe[symbol] = _build_series(symbol, extra_bars=extra.get(symbol, 0))
    return universe


def _fake_session_open_naive(reference=None, local_timezone_name=None):
    ref = reference if isinstance(reference, datetime) else datetime(2026, 6, 1, 9, 0)
    return datetime(ref.year, ref.month, ref.day, SESSION_OPEN_HOUR, SESSION_OPEN_MINUTE)


def set_universe(bot, universe):
    """Seed the bar cache exactly the way ``_get_cached_bars`` keys it."""
    bot.latest_bars = {}
    for symbol, bars in universe.items():
        bot.latest_bars[f"{symbol}|5 D|5 mins"] = bars
        bot.latest_bars.setdefault(symbol, bars)


def _make_bot(universe, *, monkeypatch):
    """A BounceBot whose RRS path is REAL and whose I/O is not.

    Real: get_rrs_settings, _get_cached_bars / get_cached_5m_bars (served from
    the seeded bar cache), _aggregate_bars_timeframe, _align_bars_with_map,
    real_relative_strength, _calc_move_ratio, _build_intraday_rrs_profile,
    get_scan_symbol_set, get_symbol_direction, get_symbol_classification,
    resolve_sector_etf, resolve_industry_ref_etf, _build_spy_context_windows,
    _summarize_environment_scan and the whole payload assembly.
    """
    monkeypatch.setattr(bounce_bot, "get_market_session_open_naive", _fake_session_open_naive)
    monkeypatch.setattr(
        bounce_bot, "_load_industry_etf_map_file", lambda: INDUSTRY_ETF_MAP_FILE
    )
    monkeypatch.setattr(
        bounce_bot,
        "load_and_update_industry_etf_map",
        lambda *args, **kwargs: INDUSTRY_ETF_MAP_FILE,
    )

    bot = object.__new__(bounce_bot.BounceBot)

    bot.rrs_lock = threading.Lock()
    bot.rrs_threshold = bounce_bot.RRS_DEFAULT_THRESHOLD
    bot.rrs_length = bounce_bot.RRS_LENGTH
    bot.rrs_bar_size = bounce_bot.RRS_TIMEFRAMES[GUI_TIMEFRAME_KEY]["bar_size"]
    bot.rrs_duration = bounce_bot.RRS_TIMEFRAMES[GUI_TIMEFRAME_KEY]["duration"]
    bot.rrs_timeframe_key = GUI_TIMEFRAME_KEY

    bot.longs = list(LONGS)
    bot.shorts = list(SHORTS)
    bot.auto_longs = []
    bot.auto_shorts = []
    bot.master_avwap_d1_watchlist = {}
    bot.master_avwap_d1_upgrade_alerts = {}
    bot.master_avwap_focus_map = {}
    bot.sector_etf_map = dict(SECTOR_ETF_MAP)
    bot.industry_map_data = INDUSTRY_ETF_MAP_FILE
    bot.symbol_classification_cache = {
        symbol: {
            "symbol": symbol,
            "sectorKey": sector_key,
            "sector": sector,
            "industryKey": industry_key,
            "industry": industry,
        }
        for symbol, (sector_key, sector, industry_key, industry) in CLASSIFICATIONS.items()
    }
    bot.latest_scan_extremes = {}
    bot.latest_rrs_payload = None
    bot.earnings_reaction_filter_cache = {}

    set_universe(bot, universe)

    # I/O and evidence seams: stubbed, never reached by the RRS maths.
    bot.request_historical_bars = Mock(
        side_effect=AssertionError("the RRS pass must not fetch bars in this test")
    )
    bot.load_master_avwap_focus = Mock()
    bot.load_master_avwap_d1_watchlist = Mock()
    bot.load_master_avwap_d1_upgrade_alerts = Mock()
    bot.load_master_avwap_d1_zone_arms = Mock()
    bot.get_master_avwap_d1_watch_symbols = Mock(return_value=[])
    bot._human_focus_symbols = Mock(return_value=set())
    bot._human_focus_side_for_symbol = Mock(return_value="")
    bot._chart_watch_symbols = Mock(return_value=set())
    bot._load_earnings_reaction_symbols = Mock(return_value=set())
    bot._symbol_matches_alias_set = Mock(return_value=False)
    bot._environment_scan_is_active = Mock(return_value=True)
    bot._record_environment_focus_history = Mock()
    bot._log_scan_extremes = Mock()
    bot._emit_master_avwap_focus_rrs_alerts = Mock()
    bot.get_market_environment = Mock(return_value="bullish_weak")
    bot.compute_group_strengths = Mock(return_value=GROUP_STRENGTH_STUB)
    bot.compute_market_internals = Mock(return_value=MARKET_INTERNALS_STUB)

    bot.decorated = []

    def _decorate(payload):
        bot.decorated.append(payload)
        return {"decorated_from": payload.get("timeframe_key")}

    bot._decorate_snapshot = _decorate

    bot.gui_messages = []
    bot.gui_callback = lambda message, tag: bot.gui_messages.append((tag, message))
    return bot


class ProfileCounter:
    """Counts real ``_build_intraday_rrs_profile`` calls per symbol per cycle."""

    def __init__(self, bot):
        self._real = bot._build_intraday_rrs_profile
        self._bot = bot
        self.cycles = []
        self._current = None
        bot._build_intraday_rrs_profile = self

    def __call__(self, symbol_bars, spy_bars, length=bounce_bot.IMPULSE_RRS_PROFILE_LENGTH):
        if self._current is not None and symbol_bars:
            key = self._symbol_for(symbol_bars)
            self._current[key] = self._current.get(key, 0) + 1
        return self._real(symbol_bars, spy_bars, length=length)

    def _symbol_for(self, symbol_bars):
        for key, bars in self._bot.latest_bars.items():
            if "|" in key:
                continue
            if bars is symbol_bars:
                return key
        return "?"

    def start_cycle(self):
        self._current = {}
        self.cycles.append(self._current)

    def counts(self, symbol):
        return tuple(cycle.get(symbol, 0) for cycle in self.cycles)


# --- canonical serialization ---------------------------------------------


def _json_default(value):
    if isinstance(value, datetime):
        return {"__datetime__": value.isoformat()}
    if isinstance(value, date):
        return {"__date__": value.isoformat()}
    if isinstance(value, (set, frozenset)):
        return sorted(value)
    raise TypeError("not serializable: %r" % (type(value),))


def canonical(payload):
    """The byte-for-byte form.  ``timestamp`` is wall-clock and is excluded."""
    body = {key: value for key, value in dict(payload).items() if key != "timestamp"}
    return json.dumps(body, sort_keys=True, separators=(",", ":"), default=_json_default)


def canonical_extremes(extremes):
    return json.dumps(extremes, sort_keys=True, separators=(",", ":"), default=_json_default)


def _load_fixture():
    if not FIXTURE_PATH.exists():  # pragma: no cover - only before generation
        pytest.fail("golden fixture missing: %s" % (FIXTURE_PATH,))
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


# --- the golden recording (four passes, pre-fix code) ---------------------


def _record_four_passes(monkeypatch):
    """Run the four passes exactly as ``run_strategy`` does today."""
    bot = _make_bot(_recorded_universe(), monkeypatch=monkeypatch)
    passes = {}
    for timeframe_key in CYCLE_TIMEFRAMES:
        bot.run_rrs_scan(timeframe_key_override=timeframe_key, emit_gui=False)
        passes[timeframe_key] = canonical(bot.latest_rrs_payload)
    bot.run_rrs_scan()
    passes["gui"] = canonical(bot.latest_rrs_payload)
    return {
        "passes": passes,
        "scan_extremes": canonical_extremes(bot.latest_scan_extremes),
        "gui_timeframe_key": GUI_TIMEFRAME_KEY,
    }


@pytest.mark.skipif(
    not os.environ.get("WS_SN3_WRITE_FIXTURE"),
    reason="fixture recording is a one-off on the PRE-FIX code (WS_SN3_WRITE_FIXTURE=1)",
)
def test_record_the_four_pass_golden_fixture(monkeypatch):
    """One-off recorder.  Never part of the red/green loop."""
    import subprocess

    commit = subprocess.check_output(
        ["git", "rev-parse", "HEAD"], cwd=str(ROOT_DIR), text=True
    ).strip()
    recorded = _record_four_passes(monkeypatch)
    recorded["generated_from_commit"] = commit
    recorded["universe_version"] = "ws_sn3_synthetic_v1"
    recorded["provider_assumptions"] = (
        "Synthetic 5-minute bars, no provider call; market-local session open pinned to 06:30."
    )
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_PATH.write_text(
        json.dumps(recorded, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def test_the_golden_fixture_was_recorded_before_the_fix():
    """A fixture regenerated by the code it pins is a self-portrait."""
    fixture = _load_fixture()
    assert fixture["generated_from_commit"] == PINNED_SOURCE_COMMIT
    assert sorted(fixture["passes"]) == sorted([*CYCLE_TIMEFRAMES, "gui"])
    # The four-pass code's GUI pass is a fourth full walk of the universe that
    # reproduces one of the three.  That is exactly the waste SN3 removes.
    assert fixture["passes"]["gui"] == fixture["passes"][GUI_TIMEFRAME_KEY]


# --- the packet's five tests ---------------------------------------------


def test_one_pass_reproduces_the_recorded_four_pass_outputs(monkeypatch):
    """ONE run_rrs_scan produces 5m, 15m and 1h byte-identical to the fixture."""
    fixture = _load_fixture()
    bot = _make_bot(_recorded_universe(), monkeypatch=monkeypatch)

    bot.run_rrs_scan()

    for timeframe_key in CYCLE_TIMEFRAMES:
        produced = canonical(bot.rrs_payload_for(timeframe_key))
        assert produced == fixture["passes"][timeframe_key], (
            "%s payload differs from the recorded four-pass output" % (timeframe_key,)
        )
    assert canonical_extremes(bot.latest_scan_extremes) == fixture["scan_extremes"]


def test_run_rrs_scan_is_entered_once_per_cycle(monkeypatch):
    """The scan cycle enters run_rrs_scan once, not four times."""

    class _CycleReachedRegimePause(BaseException):
        """Unwinds run_strategy after the RRS stage, past its ``except Exception``."""

    class _FakeCycleClock:
        def __init__(self):
            self.marks = []

        def mark(self, name):
            self.marks.append(name)
            if name == "regime_pause":
                raise _CycleReachedRegimePause()

        def summary(self):  # pragma: no cover - never reached
            return ""

    clocks = []

    def _clock_factory(*args, **kwargs):
        clock = _FakeCycleClock()
        clocks.append(clock)
        return clock

    monkeypatch.setattr(bounce_bot, "ScanCycleClock", _clock_factory)
    monkeypatch.setattr(bounce_bot, "read_tickers", lambda *args, **kwargs: [])

    bot = _make_bot(_recorded_universe(), monkeypatch=monkeypatch)
    bot._stop_event = threading.Event()
    bot.is_scanning_enabled = Mock(return_value=True)
    bot.ensure_connected = Mock(return_value=True)
    bot.warned_symbols = set()
    bot.alerted_symbols = set()
    bot.bounce_type_toggles = {}
    bot._maybe_refresh_learning_after_close = Mock()
    bot._maybe_refresh_auto_regime_while_paused = Mock()
    bot.load_human_focus_picks = Mock()
    bot.update_watchlists_from_master_avwap = Mock()
    bot.emit_master_avwap_d1_flags = Mock()
    bot.get_priority_scan_symbols = Mock(return_value=set())
    bot._is_background_refresh_cycle = Mock(return_value=False)
    bot._prune_latest_bars_for_cycle = Mock()
    bot.build_atr_cache = Mock()
    bot.update_auto_market_environment = Mock()
    bot._scan_human_focus_fast_lane = Mock(return_value=set())
    bot.check_regime_pause_setups = Mock()
    bot.run_rrs_scan = Mock()

    with pytest.raises(_CycleReachedRegimePause):
        bot.run_strategy()

    assert bot.run_rrs_scan.call_count == 1, (
        "the cycle walked the universe %s times; RRS marks were %s"
        % (
            bot.run_rrs_scan.call_count,
            [mark for mark in clocks[0].marks if mark.startswith("rrs")],
        )
    )


def test_the_gui_timeframe_reuses_the_cached_result(monkeypatch):
    """The GUI pass hands out the SAME payload object, not a recomputed one."""
    bot = _make_bot(_recorded_universe(), monkeypatch=monkeypatch)

    bot.run_rrs_scan()

    gui_payload = bot.rrs_payload_for(GUI_TIMEFRAME_KEY)
    assert bot.latest_rrs_payload is gui_payload
    assert bot.decorated == [gui_payload]
    snapshots = [message for tag, message in bot.gui_messages if tag == "rrs_snapshot"]
    assert snapshots == [{"decorated_from": GUI_TIMEFRAME_KEY}]


def _run_three_cycles(monkeypatch):
    """Cycle 1: SPY and every name end at T.  Cycle 2: SPY and AMD gain one
    bar (AMD's last dt MOVES, WFC's does not).  Cycle 3: nothing moves.

    The payloads collected are the 5m ones: one extra 5-minute bar only opens
    a PARTIAL 15m/1h bucket, which ``_aggregate_bars_timeframe`` drops, so 5m
    is the timeframe where a moved last bar is visible in the output.
    """
    bot = _make_bot(_recorded_universe(), monkeypatch=monkeypatch)
    counter = ProfileCounter(bot)
    payloads = []

    grown = {SPY_SYMBOL: 1, "AMD": 1}
    for cycle_index in range(3):
        if cycle_index == 1:
            set_universe(bot, _recorded_universe(extra_bars_for=grown))
        counter.start_cycle()
        bot.run_rrs_scan()
        payloads.append(bot.rrs_payload_for("5m"))
    return bot, counter, payloads


def test_a_moved_last_bar_dt_invalidates_the_profile_cache(monkeypatch):
    """AMD gains a bar in cycle 2: rebuilt once there, reused in cycle 3."""
    bot, counter, payloads = _run_three_cycles(monkeypatch)

    assert counter.counts("AMD") == (1, 1, 0)
    # The new bar reached the output, so this is a real rebuild and not a
    # stale cache handed back under a new key.
    assert payloads[1]["rrs_all"]["AMD"] != payloads[0]["rrs_all"]["AMD"]
    assert payloads[2]["rrs_all"]["AMD"] == payloads[1]["rrs_all"]["AMD"]


def test_a_symbol_with_no_new_bar_is_not_reprofiled(monkeypatch):
    """WFC never gains a bar, so it is profiled once across three cycles."""
    bot, counter, payloads = _run_three_cycles(monkeypatch)

    assert counter.counts("WFC") == (1, 0, 0)
    assert payloads[1]["rrs_all"]["WFC"] == payloads[0]["rrs_all"]["WFC"]
    assert payloads[2]["rrs_all"]["WFC"] == payloads[0]["rrs_all"]["WFC"]
