"""Golden results for every DAILY relative-strength site before the rolling RRS.

Recorded on the UNCHANGED code (``PINNED_SOURCE_COMMIT``) from fixed synthetic
bars: the RS Window daily strength map, the Master AVWAP D1 RS / industry RS
path (score, bonus, notes) and the rs_engine_v1 cohort ranking on M5 bars.
With ``TRADINGBOTV3_RRS_ENGINE=desk`` the converted code must reproduce this
fixture to 1e-9 relative. A fixture regenerated by the converted code is a
self-portrait: change the code, never the pin.

Record (only at the pinned commit): ``python tests/test_rrs_daily_golden.py``.
"""

from __future__ import annotations

import inspect
import json
import math
import subprocess
import sys
from datetime import date, datetime, timedelta
from pathlib import Path

import pandas as pd

ROOT_DIR = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT_DIR / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

FIXTURE_PATH = Path(__file__).resolve().parent / "fixtures" / "rrs_daily_golden.json"
PINNED_SOURCE_COMMIT = "237f3acee783e216c998f5d7ca02018c95841edf"

# --- fixed synthetic daily bars ------------------------------------------------

DAILY_DAYS = 90
DAILY_START = date(2026, 3, 2)


def business_days(count: int, start: date = DAILY_START) -> list[date]:
    out: list[date] = []
    day = start
    while len(out) < count:
        if day.weekday() < 5:
            out.append(day)
        day += timedelta(days=1)
    return out


def daily_closes() -> dict[str, list[float]]:
    n = DAILY_DAYS
    burst = []
    for i in range(n):
        base = 100.0 + 0.5 * math.sin(i * 1.1)
        burst.append(base + (10.0 if i >= 80 else 0.0))
    return {
        "SPY": [500.0 + 0.25 * i + 1.0 * math.sin(i * 0.7) for i in range(n)],
        "STRONG": [100.0 + 1.0 * i + 0.3 * math.sin(i * 0.9) for i in range(n)],
        "WEAK": [100.0 - 0.6 * i + 0.3 * math.sin(i * 0.8) for i in range(n)],
        "BURST": burst,
        "FLAT": [100.0 + 0.4 * math.sin(i * 1.3) for i in range(n)],
        "XLK": [200.0 + 0.45 * i + 0.5 * math.sin(i * 0.6) for i in range(n)],
        "XLE": [80.0 - 0.25 * i + 0.3 * math.sin(i * 0.5) for i in range(n)],
        # Only the last 28 sessions: too short for a full rolling read.
        "NEWCO": [50.0 + 0.2 * i for i in range(28)],
    }


SPREADS = {"SPY": 1.5, "XLK": 1.0, "XLE": 0.6}


def daily_frame(symbol: str, closes: list[float] | None = None) -> pd.DataFrame:
    closes = closes if closes is not None else daily_closes()[symbol]
    days = business_days(DAILY_DAYS)[-len(closes):]
    spread = SPREADS.get(symbol, 0.8)
    rows = []
    prev = closes[0]
    for i, (day, close) in enumerate(zip(days, closes, strict=True)):
        wiggle = spread * (1.0 + 0.3 * math.sin(i * 0.37))
        rows.append(
            {
                "datetime": pd.Timestamp(day),
                "open": prev,
                "high": max(prev, close) + wiggle,
                "low": min(prev, close) - wiggle,
                "close": close,
                "volume": 1_000_000.0 + 1000.0 * i,
            }
        )
        prev = close
    return pd.DataFrame(rows)


def daily_frames() -> dict[str, pd.DataFrame]:
    return {symbol: daily_frame(symbol) for symbol in daily_closes()}


STOCKS = ("STRONG", "WEAK", "BURST", "FLAT", "NEWCO")
INDUSTRY_OF = {"STRONG": "XLK", "BURST": "XLK", "WEAK": "XLE", "FLAT": "XLE", "NEWCO": "XLK"}


def spy_benchmark(frame: pd.DataFrame) -> dict:
    """The regime snapshot's SPY entry, as ``legacy`` builds it."""
    closes = [float(c) for c in frame["close"]]
    one = (closes[-1] - closes[-2]) / closes[-2] * 100
    five = (closes[-1] - closes[-6]) / closes[-6] * 100
    return {"one_day_return_pct": round(one, 3), "five_day_return_pct": round(five, 3)}


# --- fixed synthetic M5 bars for rs_engine_v1 ----------------------------------

M5_SESSIONS = (date(2026, 7, 6), date(2026, 7, 7), date(2026, 7, 8), date(2026, 7, 9), date(2026, 7, 10))
M5_BARS_PER_SESSION = 78


def m5_closes(symbol: str) -> list[float]:
    out: list[float] = []
    total = len(M5_SESSIONS) * M5_BARS_PER_SESSION
    for k in range(total):
        session, j = divmod(k, M5_BARS_PER_SESSION)
        if symbol == "SPY":
            out.append(500.0 + 0.01 * k + 0.1 * math.sin(k * 0.21))
        elif symbol == "A":  # steady leader
            out.append(100.0 + 0.02 * k + 0.03 * math.sin(k * 0.3))
        elif symbol == "B":  # flat
            out.append(100.0 + 0.03 * math.sin(k * 0.4))
        elif symbol == "C":  # steady laggard
            out.append(100.0 - 0.02 * k + 0.03 * math.sin(k * 0.33))
        elif symbol == "D":  # bursts at the last session's open, then flat
            last = session == len(M5_SESSIONS) - 1
            out.append(100.0 + 0.03 * math.sin(k * 0.4) + (3.0 if last and j >= 2 else 0.0))
        else:
            raise KeyError(symbol)
    return out


def m5_bars(symbol: str):
    from market_state import M5Bar

    closes = m5_closes(symbol)
    bars = []
    prev = closes[0]
    for k, close in enumerate(closes):
        session, j = divmod(k, M5_BARS_PER_SESSION)
        day = M5_SESSIONS[session]
        ts = datetime(day.year, day.month, day.day, 6, 35) + timedelta(minutes=5 * j)
        pad = 0.05 * (1.0 + 0.5 * math.sin(k * 0.17)) * (5.0 if symbol == "SPY" else 1.0)
        bars.append(
            M5Bar(
                ts=ts,
                open=prev,
                high=max(prev, close) + pad,
                low=min(prev, close) - pad,
                close=close,
                volume=100_000.0,
            )
        )
        prev = close
    return bars


ENGINE_CANDIDATES = (
    # symbol, bars, side_sign, d1 excess %
    ("A", "A", 1, 2.5),
    ("B", "B", 1, 0.0),
    ("C", "C", 1, -3.0),
    ("CS", "C", -1, -3.0),
    ("D", "D", 1, None),
)


# --- the golden record -----------------------------------------------------------

def _kw(fn, **kwargs):
    """Only the keyword arguments ``fn`` accepts (the pinned code predates some)."""
    accepted = inspect.signature(fn).parameters
    return {k: v for k, v in kwargs.items() if k in accepted}


def _clean(value):
    if isinstance(value, float):
        return None if math.isnan(value) else value
    if isinstance(value, dict):
        return {str(k): _clean(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_clean(v) for v in value]
    if hasattr(value, "item") and not isinstance(value, (str, bytes)):
        return _clean(value.item())
    return value


UNIVERSE_FIELDS = (
    "symbol",
    "side",
    "daily_relative_strength_score",
    "daily_relative_strength_bonus",
    "daily_relative_strength_note",
    "symbol_one_day_return_pct",
    "symbol_five_day_return_pct",
    "industry_etf",
    "rs_vs_industry",
    "rs_vs_industry_1d",
    "rs_vs_industry_5d",
)
ENRICHED_FIELDS = (
    "symbol",
    "side",
    "score",
    "daily_relative_strength_score",
    "industry_relative_strength_score",
    "industry_daily_relative_strength_score",
    "rs_vs_industry_1d",
    "rs_vs_industry_5d",
    "industry_rs_consistent",
    "industry_relative_strength_bonus",
    "industry_relative_strength_note",
)


def build_golden(tmp_dir: Path) -> dict:
    import setup_playbook_study
    from master_avwap_lib import legacy
    from relative_strength import CandidateInput, RelativeStrengthEngine
    from ui.services import rs_window_feed

    frames = daily_frames()
    spy_frame = frames["SPY"]
    benchmark = spy_benchmark(spy_frame)
    spy_rows = legacy._daily_frame_to_rows(spy_frame)
    out: dict = {"source_commit": PINNED_SOURCE_COMMIT}

    # 1. RS Window daily strength map (d1_rs_5d / d1_rs_20d).
    original_loader = setup_playbook_study._load_daily_frame
    original_dir = legacy.MASTER_AVWAP_DAILY_BARS_DIR
    setup_playbook_study._load_daily_frame = lambda symbol: frames.get(symbol)
    legacy.MASTER_AVWAP_DAILY_BARS_DIR = tmp_dir
    rs_window_feed._daily_strength_cache.clear()
    try:
        strength = rs_window_feed.daily_strength_map(list(STOCKS) + ["XLK", "XLE"])
    finally:
        setup_playbook_study._load_daily_frame = original_loader
        legacy.MASTER_AVWAP_DAILY_BARS_DIR = original_dir
        rs_window_feed._daily_strength_cache.clear()
    out["daily_strength_map"] = {symbol: _clean(strength[symbol]) for symbol in sorted(strength)}

    # 2. Master AVWAP D1 RS vs SPY, per side.
    assess = {}
    for symbol in STOCKS:
        rows = legacy._daily_frame_to_rows(frames[symbol])
        last = date.fromisoformat(rows[-1]["date"])
        for side in ("LONG", "SHORT"):
            result = legacy.assess_daily_relative_strength(
                rows, last, side, benchmark, **_kw(legacy.assess_daily_relative_strength, spy_daily_rows=spy_rows)
            )
            assess[f"{symbol}|{side}"] = _clean(result)
    out["assess_daily"] = assess

    # 3. Universe rows (stock vs SPY and vs its industry ETF), industry ETF rows.
    contexts = {
        symbol: {"sector": "S", "industry": f"I-{INDUSTRY_OF[symbol]}", "industry_etf": INDUSTRY_OF[symbol]}
        for symbol in STOCKS
    }
    industry_frames = {"XLK": frames["XLK"], "XLE": frames["XLE"]}
    universe = legacy.build_universe_strength_rows(
        {symbol: frames[symbol] for symbol in STOCKS},
        benchmark,
        sides_by_symbol={symbol: "LONG" for symbol in STOCKS},
        industry_context_by_symbol=contexts,
        industry_daily_frames_by_etf=industry_frames,
        **_kw(legacy.build_universe_strength_rows, spy_daily_rows=spy_rows),
    )
    out["universe_rows"] = [
        {field: _clean(row.get(field)) for field in UNIVERSE_FIELDS} for row in universe
    ]
    industry = legacy.build_industry_strength_rows(
        industry_frames,
        benchmark,
        industry_context_by_symbol=contexts,
        **_kw(legacy.build_industry_strength_rows, spy_daily_rows=spy_rows),
    )
    out["industry_rows"] = [
        {
            field: _clean(row.get(field))
            for field in ("symbol", "daily_relative_strength_score", "symbol_five_day_return_pct")
        }
        for row in industry
    ]

    # 4. Industry RS bonus on active priority rows, both sides.
    priority = [
        {"symbol": symbol, "side": side, "score": 100.0, "has_favorite_signal": True, "setup_family": "x"}
        for symbol in STOCKS
        for side in ("LONG", "SHORT")
    ]
    legacy.enrich_priority_rows_with_industry_relative_strength(
        priority, universe, industry, scoring_enabled=True
    )
    out["enriched"] = [{field: _clean(row.get(field)) for field in ENRICHED_FIELDS} for row in priority]

    # 5. rs_engine_v1 cohort ranking on fixed M5 bars.
    spy_m5 = m5_bars("SPY")
    candidates = [
        CandidateInput(symbol=name, side_sign=sign, stock_bars=m5_bars(bars), d1_excess_return_pct=d1)
        for name, bars, sign, d1 in ENGINE_CANDIDATES
    ]
    ranks = RelativeStrengthEngine().rank(spy_m5, candidates)
    out["engine"] = [
        {
            "symbol": r.symbol,
            "side_sign": r.side_sign,
            "tier": r.tier,
            "composite": r.composite,
            "percentile": r.percentile,
            "components": _clean(r.components),
            "penalties": _clean(r.penalties),
            "coverage": r.coverage,
            "data_ok": r.data_ok,
            "engine_version": r.engine_version,
        }
        for r in ranks
    ]
    return out


def _assert_same(actual, expected, path="root"):
    if isinstance(expected, dict):
        assert isinstance(actual, dict), path
        assert sorted(actual) == sorted(expected), f"{path}: keys {sorted(actual)} != {sorted(expected)}"
        for key in expected:
            _assert_same(actual[key], expected[key], f"{path}.{key}")
    elif isinstance(expected, list):
        assert isinstance(actual, list) and len(actual) == len(expected), path
        for index, (a, e) in enumerate(zip(actual, expected, strict=True)):
            _assert_same(a, e, f"{path}[{index}]")
    elif isinstance(expected, float) and not isinstance(expected, bool):
        assert isinstance(actual, (int, float)), f"{path}: {actual!r} != {expected!r}"
        assert math.isclose(actual, expected, rel_tol=1e-9, abs_tol=1e-12), f"{path}: {actual!r} != {expected!r}"
    else:
        assert actual == expected, f"{path}: {actual!r} != {expected!r}"


def _fixture() -> dict:
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


def test_fixture_is_pinned_to_the_pre_rolling_commit():
    assert _fixture()["source_commit"] == PINNED_SOURCE_COMMIT


def test_desk_engine_reproduces_the_golden(tmp_path, monkeypatch):
    monkeypatch.setenv("TRADINGBOTV3_RRS_ENGINE", "desk")
    _assert_same(json.loads(json.dumps(build_golden(tmp_path))), _fixture())


if __name__ == "__main__":
    head = subprocess.run(
        ["git", "rev-parse", "HEAD"], cwd=ROOT_DIR, capture_output=True, text=True, check=True
    ).stdout.strip()
    if head != PINNED_SOURCE_COMMIT:
        raise SystemExit(f"refusing to record: HEAD {head} is not the pinned {PINNED_SOURCE_COMMIT}")
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        payload = build_golden(Path(tmp))
    FIXTURE_PATH.write_text(json.dumps(payload, indent=1, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {FIXTURE_PATH}")
