"""N1 - the sidecar completion reads the lake with TIMEZONE-AWARE bounds.

The measured defect (lead, 2026-09-05, read-only reproduction). The one pending
sidecar row - SHW, ``event_id b9344eb372284d7f98f6083b50178e0b`` - stores its
bars as ``{"dt": "2026-09-01T06:30:00"}``: NAIVE, and 06:30 is the RTH open on
this Pacific desk, so the values are DESK-LOCAL wall time. ``created_at`` on the
same file carries ``-07:00``.

Three consequences, all of them live:

* ``_bar_moment`` hands that naive datetime straight back;
* ``_session_close`` does ``moment.replace(hour=16)`` - 16:00 in the bar's own
  zone, i.e. 16:00 PACIFIC, three hours past the real 13:00 PT close;
* ``_lake_bars`` passes the naive pair to ``ResearchStore.read_rows``, whose
  ``interval_start`` is ``timestamp[us, tz=UTC]``. Arrow raises
  ``ArrowInvalid: Cannot compare timestamp with timezone to timestamp without
  timezone``, the blanket ``except`` calls it ``research_store_unreachable``,
  and ``ai_job_ledger.jsonl`` has said "1 research_store_unreachable" every
  night since 2026-09-02. The same read with AWARE bounds returned 78 rows.
  The store is reachable; the bounds are wrong.

Invariants these tests hold to: plan.md sec 5 "timestamps carry explicit
timezones"; the adoption-gate rule "normalize by ATTACHING market-local to the
naive side, never by stripping the aware side"; ``sidecar_schema_version``
stays 1; the original ``m5_bars_ref`` file is never rewritten; a failure is a
counted reason, never a raise.

ONE SEAM, NAMED. A naive desk bar needs a zone attached, and a test that runs
on any machine has to pin which zone that is. The contract these tests hold the
implementation to is a module-level ``desk_zone()`` in BOTH
``ui.annotations.sidecar_completion`` and ``ui.annotations.pass_bars``,
returning the tzinfo naive desk bars are written in, called through the module
global so a test can monkeypatch it. ``test_the_module_names_the_zone_it_uses``
is the test that requires it to exist; the others pin it non-raisingly so their
red is the real defect and not a missing attribute.

The sidecar fixture here is written BY HAND in the live file's exact shape -
naive ``dt``, aware ``created_at`` - and never through
``record_annotation_with_bars``, because item 4 changes what that writer emits
and a fixture generated by the code under test would stop being a naive one the
moment the fix lands.
"""

from __future__ import annotations

import json
import sys
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

import pytest

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

PACIFIC = ZoneInfo("America/Los_Angeles")
NEW_YORK = ZoneInfo("America/New_York")
UTC = timezone.utc

#: The live row, verbatim from
#: ``C:\TradingBotData\trader_annotation_bars\b9344eb372284d7f98f6083b50178e0b.json``
#: (read-only, 2026-09-05): 18 bars, 06:30 -> 07:55 naive Pacific.
LIVE_EVENT_ID = "b9344eb372284d7f98f6083b50178e0b"
LIVE_CREATED_AT = "2026-09-01T08:01:45.228358-07:00"
LIVE_FIRST_DT = "2026-09-01T06:30:00"
LIVE_LAST_DT = "2026-09-01T07:55:00"


def _live_shape_bars() -> list[dict]:
    """18 M5 bars, 06:30 to 07:55 inclusive, naive - the live file's shape."""
    first = datetime(2026, 9, 1, 6, 30)
    bars = []
    for index in range(18):
        moment = first + timedelta(minutes=5 * index)
        price = 337.91 - index * 0.3
        bars.append(
            {
                "dt": moment.isoformat(),
                "open": round(price, 2),
                "high": round(price + 0.2, 2),
                "low": round(price - 0.2, 2),
                "close": round(price - 0.1, 2),
                "volume": 820.0,
            }
        )
    assert bars[0]["dt"] == LIVE_FIRST_DT
    assert bars[-1]["dt"] == LIVE_LAST_DT
    assert "+" not in bars[-1]["dt"], "the live sidecar's bar stamps are naive"
    return bars


def _live_row(tmp_path: Path) -> dict:
    """The annotation row plus its hand-written sidecar, on disk."""
    from ui.annotations.pass_bars import SIDECAR_DIRNAME

    bars = _live_shape_bars()
    payload = {
        "sidecar_schema_version": 1,
        "event_id": LIVE_EVENT_ID,
        "symbol": "SHW",
        "side": "SHORT",
        "interval": "M5",
        "created_at": LIVE_CREATED_AT,
        "bar_count": len(bars),
        "bars": bars,
    }
    folder = tmp_path / SIDECAR_DIRNAME
    folder.mkdir(parents=True, exist_ok=True)
    (folder / f"{LIVE_EVENT_ID}.json").write_text(
        json.dumps(payload, sort_keys=True), encoding="utf-8"
    )
    return {
        "event_id": LIVE_EVENT_ID,
        "symbol": "SHW",
        "side": "SHORT",
        "decision": "like_claim",
        "created_at": LIVE_CREATED_AT,
        "m5_bars_ref": f"{SIDECAR_DIRNAME}/{LIVE_EVENT_ID}.json",
        "m5_bar_count": len(bars),
        "m5_first_bar": LIVE_FIRST_DT,
        "m5_last_bar": LIVE_LAST_DT,
    }


def _pin_desk_zone(monkeypatch, module, zone=PACIFIC) -> None:
    """Pin the zone a naive desk bar is read in, so the test is machine-free.

    ``raising=False`` deliberately: on the unfixed module the seam does not
    exist yet, and the red these tests are written to show is the naive bound,
    not a missing attribute. ``test_the_module_names_the_zone_it_uses`` is what
    requires the seam itself.
    """
    monkeypatch.setattr(module, "desk_zone", lambda: zone, raising=False)


def test_the_module_names_the_zone_it_uses():
    """A naive desk bar is attached ONE named zone, reachable from both modules.

    Without a named seam the zone is whatever the machine happens to be set to,
    which is untestable anywhere but this desk.
    """
    from ui.annotations import pass_bars, sidecar_completion as sc

    assert callable(getattr(sc, "desk_zone", None)), (
        "sidecar_completion must expose desk_zone() - the zone naive desk bars are in"
    )
    assert callable(getattr(pass_bars, "desk_zone", None)), (
        "pass_bars must expose the same desk_zone() seam"
    )
    zone = sc.desk_zone()
    assert zone is not None
    assert datetime(2026, 9, 1, 6, 30, tzinfo=zone).utcoffset() is not None


def test_naive_sidecar_bounds_reach_the_lake_aware(tmp_path, monkeypatch):
    """The live naive sidecar produces AWARE bounds and a market-local close.

    Arrow compares a tz-aware ``interval_start`` against these two values. A
    naive bound is not a narrower query - it is an exception.
    """
    from ui.annotations import sidecar_completion as sc

    _pin_desk_zone(monkeypatch, sc)
    row = _live_row(tmp_path)
    log = tmp_path / "trader_annotations.jsonl"
    seen: dict[str, datetime] = {}

    def _reader(symbol, start, end):
        seen["start"], seen["end"] = start, end
        assert start.tzinfo is not None, (
            f"the lake start bound must be timezone-aware; got {start.isoformat()}"
        )
        assert end.tzinfo is not None, (
            f"the lake end bound must be timezone-aware; got {end.isoformat()}"
        )
        assert start == datetime(2026, 9, 1, 15, 0, tzinfo=UTC), (
            "start is the bar after 07:55 Pacific == 15:00Z"
        )
        in_new_york = end.astimezone(NEW_YORK)
        assert (in_new_york.hour, in_new_york.minute) == (16, 0), (
            f"the close is 16:00 New York; got {in_new_york.isoformat()}"
        )
        assert in_new_york.date() == date(2026, 9, 1)
        assert symbol == "SHW"
        return (
            [
                {
                    "interval_start": datetime(2026, 9, 1, 15, 0, tzinfo=UTC),
                    "open": 332.7, "high": 333.0, "low": 332.4,
                    "close": 332.9, "volume": 1200.0,
                },
                {
                    "interval_start": datetime(2026, 9, 1, 15, 5, tzinfo=UTC),
                    "open": 332.9, "high": 333.4, "low": 332.8,
                    "close": 333.2, "volume": 900.0,
                },
            ],
            "",
        )

    result = sc.complete_sidecar(
        row,
        annotations_path=log,
        lake_reader=_reader,
        now=datetime(2026, 9, 2, 2, 0, tzinfo=PACIFIC),
    )

    assert result["completed"] is True, result
    assert result["added_bars"] == 2
    assert result[sc.COMPLETED_SOURCE_FIELD] == sc.SOURCE_LAKE
    assert seen["start"].tzinfo is not None


def test_read_failure_is_named_not_unreachable(tmp_path, monkeypatch):
    """An Arrow fault and an unreachable share are DIFFERENT absences.

    The ledger has read "1 research_store_unreachable" every night since
    2026-09-02 while the store was reachable the whole time. A reason that
    names the wrong cause sent three days of diagnosis in the wrong direction.
    """
    import pyarrow.lib as pa_lib

    from research_warehouse.store import ResearchStore
    from ui.annotations import sidecar_completion as sc

    assert getattr(sc, "REASON_LAKE_READ_FAILED", None) == "lake_read_failed"
    assert "REASON_LAKE_READ_FAILED" in sc.__all__

    start = datetime(2026, 9, 1, 15, 0, tzinfo=UTC)
    end = datetime(2026, 9, 1, 20, 0, tzinfo=UTC)

    class _Exploding:
        def read_rows(self, *args, **kwargs):
            raise pa_lib.ArrowInvalid(
                "Cannot compare timestamp with timezone to timestamp without timezone"
            )

    monkeypatch.setattr(
        ResearchStore, "open", classmethod(lambda cls, *a, **k: _Exploding())
    )
    rows, reason = sc._lake_bars("SHW", start, end)
    assert rows == []
    assert reason == "lake_read_failed: ArrowInvalid", (
        "a read fault names itself and its exception class"
    )

    def _refuse(cls, *args, **kwargs):
        raise OSError("the share is not mounted")

    monkeypatch.setattr(ResearchStore, "open", classmethod(_refuse))
    rows, reason = sc._lake_bars("SHW", start, end)
    assert rows == []
    assert reason == sc.REASON_STORE_UNREACHABLE, (
        "open() failing is the ONLY thing that means unreachable"
    )


def test_session_close_is_market_local():
    """13:00 Pacific IS the close. 16:00 Pacific is three hours of nothing."""
    from ui.annotations import sidecar_completion as sc

    aware = sc._bar_moment({"dt": "2026-09-01T10:55:00-04:00"})
    close = sc._session_close(aware)
    assert close.tzinfo is not None
    assert close == datetime(
        2026, 9, 1, 16, 0, tzinfo=timezone(timedelta(hours=-4))
    ), f"a 10:55-04:00 bar closes at 16:00-04:00; got {close.isoformat()}"
    assert close.astimezone(PACIFIC).hour == 13, "== 13:00 Pacific"

    naive = sc._bar_moment({"dt": LIVE_LAST_DT})
    naive_close = sc._session_close(naive)
    assert naive_close.tzinfo is not None, (
        f"a close derived from a naive desk bar is still aware; got {naive_close!r}"
    )
    in_new_york = naive_close.astimezone(NEW_YORK)
    assert (in_new_york.hour, in_new_york.minute) == (16, 0), (
        f"16:00 New York, whatever zone the desk writes in; got {in_new_york.isoformat()}"
    )


def test_pass_bars_writes_offset():
    """New sidecars carry the offset, so tomorrow's reader needs no convention."""
    from ui.annotations import pass_bars

    assert pass_bars.SIDECAR_SCHEMA_VERSION == 1, "attaching an offset is additive"

    written = pass_bars._serialisable_bar(
        {"dt": datetime(2026, 9, 1, 6, 30), "open": 337.91, "high": 337.91,
         "low": 332.27, "close": 334.0, "volume": 820}
    )["dt"]
    parsed = datetime.fromisoformat(written)
    assert parsed.tzinfo is not None, (
        f"a naive desk bar is written WITH its offset; got {written!r}"
    )
    assert parsed.replace(tzinfo=None) == datetime(2026, 9, 1, 6, 30), (
        "the zone is ATTACHED to the wall time, never converted onto it"
    )
    assert written.startswith("2026-09-01T06:30:00")

    already = pass_bars._serialisable_bar(
        {"dt": datetime(2026, 9, 1, 6, 30, tzinfo=PACIFIC)}
    )["dt"]
    assert datetime.fromisoformat(already) == datetime(
        2026, 9, 1, 6, 30, tzinfo=PACIFIC
    ), "an already-aware bar is the same instant"

    assert pass_bars._serialisable_bar({"dt": date(2026, 9, 1)})["dt"] == "2026-09-01"


def test_aware_dt_is_never_stripped(tmp_path, monkeypatch):
    """Attach to the naive side; never strip the aware one."""
    from ui.annotations import sidecar_completion as sc

    _pin_desk_zone(monkeypatch, sc)

    aware = sc._bar_moment({"dt": "2026-09-01T06:30:00-07:00"})
    assert aware == datetime(2026, 9, 1, 13, 30, tzinfo=UTC)
    assert aware.utcoffset() == timedelta(hours=-7), "not converted, not stripped"

    zulu = sc._bar_moment({"dt": "2026-09-01T13:30:00Z"})
    assert zulu == datetime(2026, 9, 1, 13, 30, tzinfo=UTC)

    from_lake = sc._bar_moment(
        {"interval_start": datetime(2026, 9, 1, 15, 0, tzinfo=UTC)}
    )
    assert from_lake == datetime(2026, 9, 1, 15, 0, tzinfo=UTC)

    attached = sc._bar_moment({"dt": LIVE_FIRST_DT})
    assert attached is not None and attached.tzinfo is not None, (
        f"a naive desk bar gains a zone; got {attached!r}"
    )
    assert attached == datetime(2026, 9, 1, 6, 30, tzinfo=PACIFIC)


def test_the_completed_payload_bars_are_aware_isoformat_strings(tmp_path, monkeypatch):
    """Every bar in the completed file carries an offset - and the ORIGINAL does not.

    The snapshot records what the desk held at the click. It is not ours to
    edit, so it stays byte-identical with its naive stamps; the completed file
    is the one that has to be readable without a convention.
    """
    from ui.annotations import sidecar_completion as sc

    _pin_desk_zone(monkeypatch, sc)
    row = _live_row(tmp_path)
    log = tmp_path / "trader_annotations.jsonl"
    original = (log.parent / row["m5_bars_ref"]).read_bytes()

    def _reader(symbol, start, end):
        return (
            [
                {
                    "interval_start": datetime(2026, 9, 1, 15, 0, tzinfo=UTC),
                    "open": 332.7, "high": 333.0, "low": 332.4,
                    "close": 332.9, "volume": 1200.0,
                }
            ],
            "",
        )

    result = sc.complete_sidecar(
        row,
        annotations_path=log,
        lake_reader=_reader,
        now=datetime(2026, 9, 2, 2, 0, tzinfo=PACIFIC),
    )
    assert result["completed"] is True, result

    completed = json.loads(
        (log.parent / result[sc.COMPLETED_REF_FIELD]).read_text(encoding="utf-8")
    )
    assert completed["sidecar_schema_version"] == 1
    assert len(completed["bars"]) == 19
    for bar in completed["bars"]:
        moment = datetime.fromisoformat(bar["dt"])
        assert moment.tzinfo is not None, (
            f"every completed bar stamp carries an offset; got {bar['dt']!r}"
        )
    assert datetime.fromisoformat(completed["bars"][0]["dt"]) == datetime(
        2026, 9, 1, 6, 30, tzinfo=PACIFIC
    )
    assert datetime.fromisoformat(completed["bars"][-1]["dt"]) == datetime(
        2026, 9, 1, 15, 0, tzinfo=UTC
    )
    assert (log.parent / row["m5_bars_ref"]).read_bytes() == original


def test_a_naive_row_is_no_longer_counted_as_unreachable(tmp_path, monkeypatch):
    """The whole night's ledger line, end to end, with a real Arrow comparison.

    A fake reader that only checks ``tzinfo`` would still pass if the bounds
    were aware in the wrong zone. This one does what Arrow does: it raises when
    the bound is naive and filters when it is not.
    """
    from ui.annotations import sidecar_completion as sc

    _pin_desk_zone(monkeypatch, sc)
    row = _live_row(tmp_path)
    log = tmp_path / "trader_annotations.jsonl"
    lake = [
        datetime(2026, 9, 1, 15, 0, tzinfo=UTC) + timedelta(minutes=5 * step)
        for step in range(36)  # 08:00 -> 10:55 Pacific
    ]

    def _arrow_like(symbol, start, end):
        try:
            kept = [stamp for stamp in lake if start <= stamp < end]
        except TypeError as exc:  # what pyarrow raises, in Python's own words
            return [], f"{sc.REASON_LAKE_READ_FAILED}: {type(exc).__name__}"
        return (
            [
                {"interval_start": stamp, "open": 1.0, "high": 1.0,
                 "low": 1.0, "close": 1.0, "volume": 1.0}
                for stamp in kept
            ],
            "",
        )

    outcome = sc.complete_sidecars(
        [row], annotations_path=log, lake_reader=_arrow_like,
        now=datetime(2026, 9, 2, 2, 0, tzinfo=PACIFIC),
    )

    assert outcome["reasons"] == {}, (
        f"the store is reachable and the row completes; got {outcome['reasons']}"
    )
    assert LIVE_EVENT_ID in outcome["completed"]
    assert sc.COMPLETED_REF_FIELD in outcome["completed"][LIVE_EVENT_ID]


if __name__ == "__main__":  # pragma: no cover - convenience only
    raise SystemExit(pytest.main([__file__, "-q"]))
