"""TJ-1 item 5 - "Paste daily forecast…": the reader, and the per-session write.

Two halves, both RED before the builder starts:

* ``scripts/forecast_brief.py`` - a deterministic, heading-matched reader over the
  brief the trader's scheduled ChatGPT prompt produces. The golden input is the
  one they actually pasted on 2026-09-17,
  ``tests/fixtures/day_review/forecast_2026-09-17.md``. **Heading match only, no
  model, no guessing:** anything the document does not say is empty, never
  inferred.
* ``MarketJournalService.import_daily_forecast`` - the forecast is filed against
  the SESSION it is about (not a week), and a second paste for the same session
  SUPERSEDES the first, so the page's External forecast block shows one.

Nothing here reads the forecast during the session except the page's own block:
these tests exercise the reader and the writer, never a detector, score or alert.
"""

from __future__ import annotations

import dataclasses
import sys
from pathlib import Path

import pytest

ROOT_DIR = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT_DIR / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

FIXTURE = Path(__file__).resolve().parent / "fixtures" / "day_review" / "forecast_2026-09-17.md"

#: The session the fixture brief is about, from its own first heading
#: ("Thursday, September 17, 2026"). Never from the clock.
FIXTURE_SESSION = "2026-09-17"

#: The two Intraday-playbook paragraphs, verbatim from the fixture. Pinned by
#: hand from the file the trader pasted - not generated by the reader.
BULLISH_PARAGRAPH = (
    "The **bullish continuation** requires the 10-year to remain below 5%, Brent "
    "to stay below roughly $104 and NVDA/SMH to hold their opening strength. If "
    "IWM and banks participate, the rally becomes much healthier because it is no "
    "longer simply another mega-cap squeeze."
)
BEARISH_PARAGRAPH = (
    "The **bearish reversal** is equally clear: Brent snaps back above $105, the "
    "10-year retakes 5%, and semiconductors lose VWAP. If all three happen "
    "together, I would treat today's gap higher as a relief rally that failed "
    "rather than chase dip buys."
)
#: The third paragraph of the same section. It belongs to NEITHER field: a reader
#: that returns "the section" rather than "the two paragraphs" fails here.
SCHEDULE_PARAGRAPH_FRAGMENT = "pending-home-sales data provide the next scheduled"


def _fixture_text() -> str:
    """The brief as a Qt paste would deliver it: newlines translated."""
    return FIXTURE.read_text(encoding="utf-8")


def _fixture_text_crlf() -> str:
    """The same brief with Windows line endings.

    Built rather than read, so the test does not depend on how git checked the
    file out. A reader that splits on ``"\\n\\n"`` without normalising sees one
    paragraph where this text has two.
    """
    return _fixture_text().replace("\r\n", "\n").replace("\n", "\r\n")


# ---------------------------------------------------------------------------
# 0. the fixture itself
# ---------------------------------------------------------------------------
def test_the_fixture_is_the_brief_the_trader_pasted():
    """Guard, not a packet item: the golden input has not been edited away."""
    text = _fixture_text()
    assert text.startswith("# Market Morning Brief")
    assert "Thursday, September 17, 2026" in text
    assert "## Intraday playbook" in text
    assert "### Bottom line" in text
    assert "\r\n" in _fixture_text_crlf(), "the fixture is a Windows-newline file"


# ---------------------------------------------------------------------------
# 1. the golden parse
# ---------------------------------------------------------------------------
def test_the_brief_is_a_frozen_dataclass_nothing_can_edit_after_the_parse():
    import forecast_brief

    brief = forecast_brief.parse(_fixture_text())
    assert dataclasses.is_dataclass(brief)
    with pytest.raises(dataclasses.FrozenInstanceError):
        brief.title_date = "2026-01-01"  # type: ignore[misc]


def test_the_title_date_comes_from_the_first_heading_and_not_the_clock():
    import forecast_brief

    assert forecast_brief.parse(_fixture_text()).title_date == FIXTURE_SESSION


def test_the_two_playbook_paragraphs_are_read_whole_and_kept_apart():
    import forecast_brief

    brief = forecast_brief.parse(_fixture_text())
    assert brief.playbook_bullish == BULLISH_PARAGRAPH
    assert brief.playbook_bearish == BEARISH_PARAGRAPH
    # The section has a THIRD paragraph. It is neither condition.
    assert SCHEDULE_PARAGRAPH_FRAGMENT not in brief.playbook_bullish
    assert SCHEDULE_PARAGRAPH_FRAGMENT not in brief.playbook_bearish


def test_the_ranked_signals_line_is_split_on_the_arrow_in_the_order_written():
    """Five signals, first `10-year yield`. A set would lose the ranking."""
    import forecast_brief

    signals = tuple(forecast_brief.parse(_fixture_text()).ranked_signals)
    assert len(signals) == 5, signals
    assert signals[:4] == ("10-year yield", "Brent", "NVDA/SMH", "breadth")
    assert signals[4].startswith("USD/JPY")


def test_every_turbulence_score_is_an_int_in_document_order():
    """`~8/10 through tomorrow, then ... 6–7/10` is three numbers: 8, 6, 7.

    The two-week line says "around September 29–30" and carries NO `/10`, so
    29 and 30 are not turbulence scores. A reader that scrapes every number on
    a Turbulence line fails here.
    """
    import forecast_brief

    scores = tuple(forecast_brief.parse(_fixture_text()).turbulence)
    assert scores == (8, 6, 7), scores
    assert all(type(value) is int for value in scores), scores


def test_the_bottom_line_is_its_own_section_and_borrows_nothing_from_above():
    import forecast_brief

    body = forecast_brief.parse(_fixture_text()).bottom_line
    assert "Today's setup has improved materially" in body
    assert "10-year yield → Brent" in body
    # The sections above it stay above it.
    assert "Turbulence" not in body
    assert "September 29" not in body
    assert "pending-home-sales" not in body


def test_windows_line_endings_parse_to_the_same_brief():
    import forecast_brief

    assert forecast_brief.parse(_fixture_text_crlf()) == forecast_brief.parse(_fixture_text())


def test_the_source_hash_is_stable_for_one_text_and_moves_with_it():
    import forecast_brief

    text = _fixture_text()
    first = forecast_brief.parse(text).source_hash
    assert first, "a stored forecast needs an identity"
    assert forecast_brief.parse(text).source_hash == first
    assert forecast_brief.parse(text + "\n\nOne more sentence.").source_hash != first


# ---------------------------------------------------------------------------
# 2. it never guesses
# ---------------------------------------------------------------------------
def test_a_text_with_no_headings_parses_to_empty_fields():
    import forecast_brief

    brief = forecast_brief.parse(
        "SPY looks heavy to me and I think oil is the thing to watch today."
    )
    assert brief.title_date == ""
    assert brief.playbook_bullish == ""
    assert brief.playbook_bearish == ""
    assert brief.bottom_line == ""
    assert tuple(brief.ranked_signals) == ()
    assert tuple(brief.turbulence) == ()
    # The text still has an identity: it was stored, it just said nothing.
    assert brief.source_hash


def test_a_playbook_heading_with_neither_condition_named_stays_empty():
    """"Anything not found is null, never guessed" (plan.md §12.4 TJ-1 item 5)."""
    import forecast_brief

    brief = forecast_brief.parse(
        "# Market Morning Brief — Thursday, September 17, 2026\n\n"
        "## Intraday playbook\n\n"
        "Watch the tape and do not chase.\n"
    )
    assert brief.title_date == FIXTURE_SESSION
    assert brief.playbook_bullish == ""
    assert brief.playbook_bearish == ""


def test_a_heading_with_no_date_leaves_the_title_date_empty():
    import forecast_brief

    brief = forecast_brief.parse("# Market Morning Brief\n\nSome commentary.\n")
    assert brief.title_date == ""


def test_the_heading_match_is_case_insensitive():
    import forecast_brief

    brief = forecast_brief.parse(
        "# BRIEF — Thursday, September 17, 2026\n\n"
        "## INTRADAY PLAYBOOK\n\n"
        "The **BULLISH CONTINUATION** needs rates lower.\n\n"
        "The **Bearish Reversal** needs oil higher.\n\n"
        "### BOTTOM LINE\n\n"
        "Rates first.\n"
    )
    assert brief.playbook_bullish == "The **BULLISH CONTINUATION** needs rates lower."
    assert brief.playbook_bearish == "The **Bearish Reversal** needs oil higher."
    assert "Rates first." in brief.bottom_line


def test_the_reader_calls_no_model_and_opens_no_socket(monkeypatch):
    import socket

    import forecast_brief

    def _refuse(*_args, **_kwargs):  # pragma: no cover - the point is it is not hit
        raise AssertionError("the forecast reader is deterministic; it fetches nothing")

    monkeypatch.setattr(socket.socket, "connect", _refuse)
    monkeypatch.setattr(socket, "create_connection", _refuse)
    assert forecast_brief.parse(_fixture_text()).title_date == FIXTURE_SESSION


# ---------------------------------------------------------------------------
# 3. import_daily_forecast: the session, the sidecar, the supersede
# ---------------------------------------------------------------------------
@pytest.fixture()
def journal(tmp_path, monkeypatch):
    """A MarketJournalService over a temp ledger and a temp thesis sidecar."""
    pytest.importorskip("PySide6", reason="the journal service is a QObject")
    import project_paths

    theses = tmp_path / "market_theses.jsonl"
    monkeypatch.setattr(project_paths, "RUNTIME_DATA_DIR", tmp_path, raising=False)
    monkeypatch.setattr(project_paths, "MARKET_THESES_FILE", theses, raising=False)

    from ui.services.market_journal_service import MarketJournalService

    service = MarketJournalService()
    yield service, theses


def _forecast_rows(path: Path) -> list[dict]:
    import market_thesis

    return [
        row
        for row in market_thesis.read_rows(path)
        if str(row.get("kind") or "") == market_thesis.KIND_FORECAST
    ]


def test_a_pasted_brief_is_filed_against_the_session_it_is_about(journal):
    """The trader may paste at 08:45 for today, or at 21:00 for today. The
    entry's session is the SESSION ARGUMENT, never the paste moment."""
    import market_journal

    service, theses = journal
    result = service.import_daily_forecast(
        text=_fixture_text(),
        target_session=FIXTURE_SESSION,
        source_model="chatgpt",
    )

    assert result.get("ok"), result
    entry = result["entry"]
    assert entry["session_date"] == FIXTURE_SESSION
    assert entry["origin"] == market_journal.ORIGIN_EXTERNAL_FORECAST
    assert entry["timeframe"] == market_journal.TIMEFRAME_D1
    # Stored whole: the reader is a view over the text, never a replacement.
    assert entry["text"].strip() == _fixture_text().strip()


def test_the_sidecar_names_the_target_session_and_the_source_model(journal):
    service, theses = journal
    service.import_daily_forecast(
        text=_fixture_text(),
        target_session=FIXTURE_SESSION,
        source_model="chatgpt",
    )

    rows = _forecast_rows(theses)
    assert len(rows) == 1, rows
    assert rows[0]["target_session"] == FIXTURE_SESSION
    assert rows[0]["source_model"] == "chatgpt"
    # `target_week` is kept for the rows written before this packet; a DAILY
    # paste does not invent one.
    assert "target_week" in rows[0]


def test_nobody_typed_a_creation_time_so_none_is_claimed(journal):
    """Unchanged from WISHLIST 10K: `created_at_claimed` stays `unknown` rather
    than becoming the moment of the paste."""
    import market_thesis

    service, theses = journal
    service.import_daily_forecast(
        text=_fixture_text(), target_session=FIXTURE_SESSION, source_model="chatgpt"
    )
    assert _forecast_rows(theses)[0]["created_at_claimed"] == market_thesis.UNKNOWN


def test_a_second_paste_for_the_same_session_supersedes_the_first(journal):
    """Two pastes, one forecast on the page - and both rows still on disk."""
    import market_journal

    service, _theses = journal
    first = service.import_daily_forecast(
        text=_fixture_text(), target_session=FIXTURE_SESSION, source_model="chatgpt"
    )
    second = service.import_daily_forecast(
        text=_fixture_text() + "\n\nUpdate: the 10-year just took 5% back.",
        target_session=FIXTURE_SESSION,
        source_model="chatgpt",
    )

    assert first.get("ok") and second.get("ok")
    assert second["entry"]["supersedes"] == first["entry"]["entry_id"]

    # The ledger keeps both rows; the READ shows the newer one alone.
    current = service.entries_about(FIXTURE_SESSION)
    forecasts = [
        row
        for row in current
        if str(row.get("origin") or "") == market_journal.ORIGIN_EXTERNAL_FORECAST
    ]
    assert len(forecasts) == 1, forecasts
    assert forecasts[0]["entry_id"] == second["entry"]["entry_id"]
    assert "the 10-year just took 5% back" in forecasts[0]["text"]


def test_a_paste_for_a_different_session_supersedes_nothing(journal):
    service, _theses = journal
    first = service.import_daily_forecast(
        text=_fixture_text(), target_session=FIXTURE_SESSION, source_model="chatgpt"
    )
    other = service.import_daily_forecast(
        text="A different day's brief entirely.",
        target_session="2026-09-16",
        source_model="chatgpt",
    )
    assert other["entry"]["supersedes"] == ""
    assert other["entry"]["session_date"] == "2026-09-16"
    assert len(service.entries_about(FIXTURE_SESSION)) == 1
    assert service.entries_about(FIXTURE_SESSION)[0]["entry_id"] == first["entry"]["entry_id"]


def test_the_weekly_name_survives_one_release_as_a_deprecated_alias(journal):
    """`import_weekly_forecast` still writes: an old caller is not broken by a
    rename. It is MARKED deprecated so the next packet can delete it."""
    import market_journal

    service, _theses = journal
    result = service.import_weekly_forecast(
        text=_fixture_text(), source_model="chatgpt", session_date=FIXTURE_SESSION
    )
    assert result.get("ok"), result
    assert result["entry"]["origin"] == market_journal.ORIGIN_EXTERNAL_FORECAST
    doc = (type(service).import_weekly_forecast.__doc__ or "").lower()
    assert "deprecat" in doc, "the alias says it is on its way out"
