"""Packet WS-AI1 - trustworthy overnight output (WISHLIST 10K step 1 + 5C).

Written RED, before any fix exists. Every test here drives a real path: the
enrichment pass's own entry point, `map_reduce.run_map_reduce` with an injected
`request`, `briefs.run_daily_summary`'s publish decision, the System Health
row's own builder, the Journal Trades tab's `_show_trade`, and
`ai_summary.build_evidence_package`. No test asserts on source text.

**The defect, reproduced at code level (2026-09-12).**
`ai_summary.AI_SUMMARY_JSON_SCHEMA` is `additionalProperties: False` over
`executive_summary` + `MODEL_SUMMARY_SECTIONS`
(`what_is_working`, `what_is_not_working`, `best_candidates`,
`lessons_for_tomorrow`, `risk_notes`). `enrichment._proposed_tags` reads
`tags` / `setups` / `families` and `enrichment._summary_text` reads
`headline` / `summary` / `what_worked` / `lessons`. **Not one of those keys can
survive validation**, so every `ai_trade_enrichment` row the nightly job writes
is blank while the job reports `ok` - and `_trades_for_session` then treats that
blank row as "already done" forever.

Two tests below are deliberate PINS that pass on the current code
(`test_a_validated_session_summary_response_enriches_nothing_today` is the 10K
reproduction; the slot-order and no-live-writer guards are the invariants the
builder may not break). Every other test fails on the current code, and the
first line of each failure is recorded in the commit message.
"""

from __future__ import annotations

import csv
import json
import os
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

ROOT_DIR = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT_DIR / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from ai_jobs import enrichment  # noqa: E402

NOW = datetime(2026, 9, 12, 6, 0, tzinfo=timezone.utc)

#: The session the fixtures below belong to. A Friday, and a real trading day.
SESSION = "2026-09-11"


# ---------------------------------------------------------------------------
# shared fixtures - all hand-written, none generated by the code under test
# ---------------------------------------------------------------------------


def _session_summary_response() -> dict[str, object]:
    """A response that is VALID under `AI_SUMMARY_JSON_SCHEMA`, and only that.

    Shaped the way a real validated night looks: every model-owned section
    present (PRESENT and empty where the model had nothing, never absent), each
    item carrying the three required keys. This is exactly what the live
    provider path can return today, which is the whole point.
    """
    item = {
        "statement": "AVWAP reclaims held into the close on 3 of 4 names.",
        "evidence_refs": ["setups.master_avwap_tier_outcomes"],
        "confidence": "medium",
    }
    return {
        "executive_summary": "A quiet session; the reclaim family carried it.",
        "what_is_working": [item],
        "what_is_not_working": [],
        "best_candidates": [],
        "lessons_for_tomorrow": [],
        "risk_notes": [],
    }


def _validate_against(payload, schema) -> None:
    """A small structural validator - `jsonschema` is not a dependency here.

    Checks exactly the three things that matter for this packet: every
    ``required`` key is present, no key outside ``properties`` is present when
    ``additionalProperties`` is False, and a string ``enum`` is honoured.
    """
    assert isinstance(payload, dict), "a validated response is an object"
    properties = dict(schema.get("properties") or {})
    for key in schema.get("required") or ():
        assert key in payload, f"the schema requires {key!r} and it is absent"
    if schema.get("additionalProperties") is False:
        extra = sorted(set(payload) - set(properties))
        assert not extra, f"keys the schema forbids: {extra}"
    for key, spec in properties.items():
        if key not in payload:
            continue
        allowed = spec.get("enum")
        if allowed is not None:
            assert payload[key] in allowed, (
                f"{key!r}={payload[key]!r} is outside {allowed}"
            )


def _journal_with_one_closed_trade(path: Path):
    """A journal holding ONE closed trade on `SESSION`, and nothing else."""
    from journal_store import JournalStore

    store = JournalStore(path)
    with store.connection() as conn:
        conn.execute(
            "INSERT INTO trades(trade_id, broker, account_number, account_label, "
            "symbol, security_type, currency, direction, status, opened_at, "
            "closed_at, trade_date, updated_at) VALUES('T-AI1','QUESTRADE','1',"
            "'TFSA','AAPL','STK','USD','LONG','CLOSED',"
            f"'{SESSION}T09:31:00-07:00','{SESSION}T12:04:00-07:00','{SESSION}','x')"
        )
        # An old row carries its trader-owned annotation PRESENT and empty.
        conn.execute(
            "INSERT INTO trade_annotations(trade_id, setup_tags, notes, updated_at) "
            "VALUES('T-AI1','','','x')"
        )
    return store


def _gate_is_met(monkeypatch) -> None:
    """Phase 2's gate is not what these tests are about.

    `tests/test_ai_enrichment_and_policy_draft.py` already proves the refusal
    below the gate, and re-building ten clean digest packs plus an audit
    approval file inside every test here would test that again and nothing else.
    """
    monkeypatch.setattr(
        enrichment,
        "gate_state",
        lambda *args, **kwargs: {
            "gate_met": True,
            "window_met": True,
            "audit_recorded": True,
            "sessions_consecutive_clean": 10,
            "sessions_required": 10,
            "first_gap_session": "",
            "audit_packs_required": 3,
        },
    )


def _provider_returns(monkeypatch, summary, *, model="gemma3:12b"):
    """Point the enrichment's provider seam at a fixed validated response."""
    import ai_summary

    monkeypatch.setattr(ai_summary, "local_provider_enabled", lambda: True)
    monkeypatch.setattr(ai_summary, "local_model", lambda tier="medium": model)
    monkeypatch.setattr(
        ai_summary,
        "request_ai_summary",
        lambda **kwargs: {
            "schema_version": "ai_summary_result_v1",
            "status": "validated",
            "provider": "local",
            "model": model,
            "summary": dict(summary),
        },
    )


# ---------------------------------------------------------------------------
# Item 1 - the enrichment reads what the model can return
# ---------------------------------------------------------------------------


def test_a_validated_session_summary_response_enriches_nothing_today():
    """The 10K reproduction, PINNED: the defect, stated as a passing fact.

    A response the live provider path validates and returns carries none of the
    keys the extraction seam reads, so the seam yields an empty summary and no
    tags - which is exactly the six blank rows written over 2026-09-09..11 while
    the ledger said `ok`. This test is expected to pass BEFORE the fix and to
    keep passing after it: the session summary's schema is not the enrichment's,
    and a fix that made this response produce text would be reading the wrong
    document.
    """
    import ai_summary

    response = _session_summary_response()
    _validate_against(response, ai_summary.AI_SUMMARY_JSON_SCHEMA)

    assert enrichment._summary_text(response) == "", (
        "a validated session-summary response has no key the summary extractor reads"
    )
    assert enrichment._proposed_tags(response) == [], (
        "a validated session-summary response has no key the tag extractor reads"
    )


def test_the_enrichment_declares_its_own_schema_the_extractors_can_read():
    """Item 1: the per-trade pass gets its own contract, not the summary's.

    Five fields, `additionalProperties` closed, and - the load-bearing part -
    the keys `_summary_text` and `_proposed_tags` read must be keys this schema
    PERMITS. A schema that forbids them is the defect with a new name.
    """
    import ai_summary

    schema = getattr(enrichment, "ENRICHMENT_JSON_SCHEMA", None)
    assert schema is not None, "the enrichment pass has no schema of its own"
    assert schema is not ai_summary.AI_SUMMARY_JSON_SCHEMA
    assert schema != ai_summary.AI_SUMMARY_JSON_SCHEMA

    properties = dict(schema.get("properties") or {})
    assert set(properties) == {
        "summary", "tags", "confidence", "sources", "unknowns"
    }, "the packet names exactly these five fields"
    assert schema.get("additionalProperties") is False, (
        "an open schema lets the model invent a field the extractors never read"
    )
    assert properties["summary"].get("type") == "string"
    assert properties["tags"].get("type") == "array"
    assert properties["unknowns"].get("type") == "array"
    assert properties["sources"].get("type") == "array"
    assert sorted(properties["confidence"].get("enum") or []) == [
        "high", "low", "medium"
    ]

    # The seam the packet keeps: whatever this schema calls the summary and the
    # tags, the two extractors must be able to reach them.
    assert enrichment._summary_text({"summary": "a sentence"}) == "a sentence"
    assert enrichment._proposed_tags({"tags": ["avwap_reclaim"]}) == ["avwap_reclaim"]


def test_a_response_validated_against_the_enrichment_schema_yields_text_and_tags(
    tmp_path, monkeypatch
):
    """Item 1, through the real `_enrich_one`: text out, vocabulary tags out.

    The response is checked against the enrichment's OWN schema first, so this
    test cannot pass by the model returning something the contract forbids. The
    invented family is dropped and counted - the vocabulary still decides.
    """
    schema = getattr(enrichment, "ENRICHMENT_JSON_SCHEMA", None)
    assert schema is not None, "the enrichment pass has no schema of its own"

    vocabulary = enrichment.setup_vocabulary()
    assert vocabulary, "the setup documents define the vocabulary"
    known = vocabulary[0]

    response = {
        "summary": "Bought the reclaim of the anchored VWAP and held to the close.",
        "tags": [known, "a_family_nobody_defined"],
        "confidence": "medium",
        "sources": ["journal.trade"],
        "unknowns": [],
    }
    _validate_against(response, schema)
    _provider_returns(monkeypatch, response)

    result = enrichment._enrich_one(
        trade={"trade_id": "T-AI1", "symbol": "AAPL", "direction": "LONG",
               "status": "CLOSED", "trade_date": SESSION},
        vocabulary=vocabulary,
        review_rows=[],
        session_date=SESSION,
    )

    assert result["summary"].startswith("Bought the reclaim"), (
        "the enrichment must read the summary its own schema asks for"
    )
    assert result["tags"] == [known]
    assert result["dropped_tags"] == ["a_family_nobody_defined"]
    assert str(result.get("confidence") or "") == "medium"


# ---------------------------------------------------------------------------
# Item 2 - refuse empty success
# ---------------------------------------------------------------------------


def test_an_empty_validated_response_is_saved_abstained_and_never_as_a_blank_ok(
    tmp_path, monkeypatch
):
    """Item 2: an empty answer is an ANSWER, and it is labelled one.

    One trade, one validated response with nothing in it. The row must carry
    `status = "abstained"` and the model's own `unknowns` as the reason, and the
    ledger line must count it apart from a real enrichment. `A + B == N` with
    C == 0, so the slot is still OK - it did not fail, it declined.
    """
    _gate_is_met(monkeypatch)
    store = _journal_with_one_closed_trade(tmp_path / "j.sqlite3")
    _provider_returns(
        monkeypatch,
        {
            "summary": "",
            "tags": [],
            "confidence": "low",
            "sources": [],
            "unknowns": ["no review evidence for AAPL on this session"],
        },
    )

    result = enrichment.run_journal_enrichment(
        session_date=SESSION, now=NOW, store=store, review_rows=[],
    )

    rows = store.list_ai_enrichment("T-AI1")
    assert len(rows) == 1, "an abstention is recorded, not skipped"
    assert rows[0]["status"] == "abstained", (
        "a blank row with no status is the legacy defect; this one says why"
    )
    assert "no review evidence" in str(rows[0].get("reason") or ""), (
        "the reason is the model's own `unknowns`"
    )
    assert "enriched 0, abstained 1, failed 0 of 1" in result["reason"]
    assert result["status"] == "ok", "declining is not failing"


def test_a_provider_failure_is_saved_failed_and_the_ledger_status_is_not_ok(
    tmp_path, monkeypatch
):
    """Item 2: a provider/validation failure is a row AND a degraded ledger.

    Today the exception is swallowed into a `failure(s)` suffix and NOTHING is
    written, so the next night's `_trades_for_session` re-reads the trade as
    fresh and the record of the failure lives only in the ledger's prose.
    """
    import ai_summary

    _gate_is_met(monkeypatch)
    store = _journal_with_one_closed_trade(tmp_path / "j.sqlite3")
    monkeypatch.setattr(ai_summary, "local_provider_enabled", lambda: True)
    monkeypatch.setattr(ai_summary, "local_model", lambda tier="medium": "gemma3:12b")

    def _blows_up(**kwargs):
        raise RuntimeError("endpoint refused the connection")

    monkeypatch.setattr(ai_summary, "request_ai_summary", _blows_up)

    result = enrichment.run_journal_enrichment(
        session_date=SESSION, now=NOW, store=store, review_rows=[],
    )

    rows = store.list_ai_enrichment("T-AI1")
    assert len(rows) == 1, "a failure is recorded against the trade it happened to"
    assert rows[0]["status"] == "failed"
    assert "RuntimeError" in str(rows[0].get("reason") or "") or "RuntimeError" in str(
        rows[0].get("error") or ""
    ), "the error CLASS travels, not just a sentence"
    assert "enriched 0, abstained 0, failed 1 of 1" in result["reason"]
    assert result["status"] != "ok", "C > 0 is never OK"


# ---------------------------------------------------------------------------
# Item 3 - supersede the blank rows
# ---------------------------------------------------------------------------


def test_a_legacy_blank_row_is_superseded_once_and_only_once_in_a_night(
    tmp_path, monkeypatch
):
    """Item 3: the six blank rows are repairable, and the retry is bounded.

    The legacy row is modelled the way the live table holds it - `summary` and
    `tags` PRESENT and EMPTY, `status` absent - because that is what six nights
    of the current code wrote. `_trades_for_session` must stop reading it as
    done; the repair appends a new row naming the one it replaces; and a second
    firing of the same night must not append a third.
    """
    _gate_is_met(monkeypatch)
    store = _journal_with_one_closed_trade(tmp_path / "j.sqlite3")
    store.save_ai_enrichment(
        trade_id="T-AI1", session_date=SESSION, summary="", tags=[], evidence=[],
        model="gemma3:12b", now="2026-09-12T02:00:00+00:00",
    )
    legacy = store.list_ai_enrichment("T-AI1")
    assert len(legacy) == 1 and legacy[0]["summary"] == "" and legacy[0]["tags"] == ""
    assert not str(legacy[0].get("status") or ""), "the legacy blank carries no status"
    legacy_id = legacy[0]["enrichment_id"]

    assert enrichment._trades_for_session(store, SESSION), (
        "a blank row is not a finished trade"
    )

    known = enrichment.setup_vocabulary()[0]
    _provider_returns(
        monkeypatch,
        {
            "summary": "Held the reclaim into the close.",
            "tags": [known],
            "confidence": "high",
            "sources": ["journal.trade"],
            "unknowns": [],
        },
    )

    first = enrichment.run_journal_enrichment(
        session_date=SESSION, now=NOW, store=store, review_rows=[],
    )
    assert first["status"] == "ok"

    rows = store.list_ai_enrichment("T-AI1")
    assert len(rows) == 2, "append-only: the blank row is superseded, never rewritten"
    assert rows[0]["summary"] == "", "history is kept"
    assert rows[1]["summary"] == "Held the reclaim into the close."
    assert str(rows[1].get("supersedes_row_id") or "") == str(legacy_id)

    # One retry per night per trade: firing the slot again in the same window
    # must find the trade done and add nothing.
    second = enrichment.run_journal_enrichment(
        session_date=SESSION, now=NOW, store=store, review_rows=[],
    )
    assert len(store.list_ai_enrichment("T-AI1")) == 2, (
        f"a second firing wrote another row ({second['reason']})"
    )


# ---------------------------------------------------------------------------
# Item 4 - honest completion status for the main summary
# ---------------------------------------------------------------------------


def _map_reduce_package(sources):
    """An evidence package shaped the way `plan_chunks` reads one."""
    return {
        "schema_version": "ai_evidence_package_v2",
        "generated_at": f"{SESSION}T20:00:00-07:00",
        "session_date": SESSION,
        "package_id": "pkg0000000000000",
        "evidence_hash": "0" * 64,
        "sources": [
            {"source_id": sid, "label": sid, "status": "available", "content": content}
            for sid, content in sources
        ],
        "coverage": {"counts": {"requested": len(sources), "usable": len(sources),
                                "stale": 0, "truncated": 0}},
    }


def _slice_summary(statement, refs):
    base = {
        name: []
        for name in (
            "what_is_working", "what_is_not_working", "best_candidates",
            "lessons_for_tomorrow", "risk_notes",
        )
    }
    base["executive_summary"] = "a slice"
    base["what_is_working"] = [
        {"statement": statement, "evidence_refs": list(refs), "confidence": "medium"}
    ]
    return base


def test_map_reduce_names_its_completion_when_the_synthesis_falls_back():
    """Item 4: `unsynthesized_fallback` is a WORD in the result, not a flag.

    The 900 s synthesis timeouts on 2026-09-10/11 produced exactly this shape -
    `status: "validated"` with `map_reduce.synthesized = False` - and the only
    reader that could have told them apart was a boolean nested two levels down.
    """
    from ai_jobs import map_reduce

    evidence = _map_reduce_package([("a.one", ["x"]), ("b.two", ["y"])])
    calls = {"n": 0}

    def _map_ok_reduce_times_out(**kwargs):
        calls["n"] += 1
        package = kwargs["evidence"]
        if package["sources"][0]["source_id"] == map_reduce.FINDINGS_SOURCE_ID:
            raise TimeoutError("read timed out after 900s")
        return {"summary": _slice_summary(f"finding {calls['n']}",
                                          [package["sources"][0]["source_id"]])}

    result = map_reduce.run_map_reduce(
        evidence=evidence, model="m", chars=10, request=_map_ok_reduce_times_out,
    )

    assert result["map_reduce"]["synthesized"] is False
    assert result.get("completion") == "unsynthesized_fallback", (
        "a reader must not have to infer the completion from a nested boolean"
    )


def test_map_reduce_names_a_partial_read_when_a_slice_fails():
    """Item 4: some slices lost is `partial`, not `synthesized`."""
    from ai_jobs import map_reduce

    evidence = _map_reduce_package([("a.one", ["x"]), ("b.two", ["y"])])

    def _one_slice_dies(**kwargs):
        package = kwargs["evidence"]
        sid = package["sources"][0]["source_id"]
        if sid == "b.two":
            raise RuntimeError("slice refused")
        return {"summary": _slice_summary("finding", [sid])}

    result = map_reduce.run_map_reduce(
        evidence=evidence, model="m", chars=10, request=_one_slice_dies,
    )

    assert result["map_reduce"]["slices_failed"], "one slice really did fail"
    assert result.get("completion") == "partial"


def test_map_reduce_says_synthesized_when_nothing_was_lost():
    """Item 4: the happy path names itself too, so "" is never the answer."""
    from ai_jobs import map_reduce

    evidence = _map_reduce_package([("a.one", ["x"]), ("b.two", ["y"])])

    def _all_fine(**kwargs):
        package = kwargs["evidence"]
        return {"summary": _slice_summary("finding",
                                          [package["sources"][0]["source_id"]])}

    result = map_reduce.run_map_reduce(
        evidence=evidence, model="m", chars=10, request=_all_fine,
    )

    assert result["map_reduce"]["synthesized"] is True
    assert result.get("completion") == "synthesized"


def test_the_daily_summary_refuses_ok_for_an_unsynthesized_fallback(
    tmp_path, monkeypatch
):
    """Item 4: `briefs.py` publishes OK only for `synthesized`.

    `briefs.py:279` returns `STATUS_OK` for the chunked branch whatever the
    reason says, so two nights that timed out at 900 s were ledgered `ok` with
    `; NOT synthesized` buried at the end of the sentence. The document is still
    published - losing it would be worse - but the ledger must not call it a
    clean night, and the reason must name the completion word.
    """
    import ai_summary
    from ai_jobs import briefs, ledger, map_reduce
    from ai_jobs import store as ai_store

    monkeypatch.setenv(ai_store.AI_STORE_DIR_ENV, str(tmp_path / "ai_store"))
    evidence = _map_reduce_package([("a.one", ["x"])])
    monkeypatch.setattr(ai_summary, "local_provider_enabled", lambda: True)
    monkeypatch.setattr(ai_summary, "local_model", lambda tier="medium": "gemma3:12b")
    monkeypatch.setattr(map_reduce, "map_reduce_enabled", lambda *a, **k: True)
    monkeypatch.setattr(
        ai_summary, "build_evidence_package", lambda *a, **k: evidence
    )
    monkeypatch.setattr(
        ai_summary, "export_ai_summary",
        lambda result, package, output_dir=None: {"markdown": "x.md"},
    )
    monkeypatch.setattr(
        map_reduce, "run_map_reduce",
        lambda **kwargs: {
            "schema_version": "ai_summary_result_v1",
            "status": "validated",
            "model": "gemma3:12b",
            "summary": _slice_summary("finding", ["a.one"]),
            "completion": "unsynthesized_fallback",
            "citation_drops": [],
            "map_reduce": {
                "slices_planned": 4, "slices_read": 4, "slices_failed": [],
                "sources": 1, "chunk_chars": 10, "synthesized": False,
                "synthesis_error": "TimeoutError: read timed out after 900s",
                "synthesis_stop_reason": "", "synthesis_retry": "",
                "slices_retried": [], "coverage_statement": "read in slices",
            },
        },
    )

    result = briefs.run_daily_summary(session_date=SESSION)

    assert result["outputs"], "the findings are still published, never lost"
    assert result["status"] != ledger.STATUS_OK, (
        "a fallback document is not a clean night"
    )
    assert "unsynthesized_fallback" in result["reason"]
    assert "900" in result["reason"], "the timeout that caused it is named"


def test_the_health_strips_ai_row_shows_the_completion_word(tmp_path, monkeypatch):
    """Item 4: the desk can see it without opening the ledger file.

    `operations_audit._ai_jobs_check` is the row's own builder and the strip is
    a pure renderer over it, so this is the real seam.
    """
    import operations_audit as audit

    store = tmp_path / "ai_store"
    (store / "logs").mkdir(parents=True)
    ledger_path = store / "logs" / audit.AI_JOB_LEDGER_NAME
    rows = [
        {
            "job": "ai_summary",
            "status": "degraded_no_narrative",
            "session_date": SESSION,
            "completion": "unsynthesized_fallback",
            "reason": "summary for 2026-09-11 read as 4 of 4 slice(s); "
                      "completion=unsynthesized_fallback after a 900s timeout",
            "ts": (NOW - timedelta(hours=6)).isoformat(),
        },
    ]
    ledger_path.write_text(
        "\n".join(json.dumps(row) for row in rows) + "\n", encoding="utf-8"
    )
    monkeypatch.setenv(audit.AI_STORE_DIR_ENV, str(store))

    check = audit._ai_jobs_check(NOW, timezone.utc)

    blob = check["summary"] + " " + json.dumps(check.get("details") or {})
    assert "unsynthesized_fallback" in blob, (
        "the AI row shows the completion word, not just a timestamp"
    )
    assert check["status"] != audit.STATUS_HEALTHY, (
        "a degraded night is not a healthy row"
    )


# ---------------------------------------------------------------------------
# Item 5 - a reader for the enrichment
# ---------------------------------------------------------------------------


@pytest.mark.qt
def test_the_trades_detail_shows_the_latest_non_superseded_enrichment(
    tmp_path, monkeypatch
):
    """Item 5: the trader can see the advice, marked advisory.

    10K found no consumer of `ai_trade_enrichment` anywhere; a grep of
    `scripts/` and `ui/` confirms only `journal_store` and `enrichment` name the
    table. This drives the tab's own detail read path - `_show_trade` - against
    a temp journal, and reads what the render left on the widgets.
    """
    pytest.importorskip("PySide6", reason="the Qt desk needs PySide6")
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
    from PySide6.QtWidgets import QApplication, QWidget

    from ui.models.journal import JournalTrade
    from ui.panels.journal.trades_tab import TradesTab
    from ui.services import journal_feed

    store = _journal_with_one_closed_trade(tmp_path / "j.sqlite3")
    # The superseded blank, then the row the trader should actually read.
    store.save_ai_enrichment(
        trade_id="T-AI1", session_date=SESSION, summary="", tags=[], evidence=[],
        model="gemma3:12b", now="2026-09-12T02:00:00+00:00",
    )
    blank_id = store.list_ai_enrichment("T-AI1")[0]["enrichment_id"]
    store.save_ai_enrichment(
        trade_id="T-AI1", session_date=SESSION,
        summary="Held the anchored-VWAP reclaim into the close.",
        tags=["avwap_reclaim"], evidence=[], model="gemma3:12b",
        now="2026-09-12T03:00:00+00:00",
        status="enriched", confidence="high", supersedes_row_id=blank_id,
    )
    monkeypatch.setattr(journal_feed, "_STORE", store, raising=False)

    application = QApplication.instance() or QApplication([])
    tab = TradesTab(header=None)
    trade = JournalTrade.from_mapping(dict(store.get_trade("T-AI1")))
    tab._show_trade(trade)
    application.processEvents()

    texts: list[str] = []
    for child in tab.findChildren(QWidget):
        for getter in ("text", "toPlainText"):
            reader = getattr(child, getter, None)
            if callable(reader):
                try:
                    texts.append(str(reader()))
                except TypeError:
                    pass
    for index in range(getattr(tab, "auto_tags").count()):
        texts.append(tab.auto_tags.item(index).text())
    blob = "\n".join(texts)

    assert "Held the anchored-VWAP reclaim into the close." in blob, (
        "the latest non-superseded enrichment summary is shown"
    )
    assert "avwap_reclaim" in blob
    assert "advisory" in blob.lower(), "the tags are marked advisory"
    assert "high" in blob.lower(), "the confidence is shown"
    assert "2026-09-12" in blob, "written_at is shown"
    tab.deleteLater()
    application.processEvents()


# ---------------------------------------------------------------------------
# Item 6 (5C) - the preference summary in the nightly package
# ---------------------------------------------------------------------------

#: Three statements said on the session before the package's, so their
#: `statement_window_end` (10 SESSIONS out) has not arrived: still open, not a
#: miss. Everything else was said in June and its window closed long ago.
_OPEN_SESSION = "2026-09-11"
_CLOSED_SESSION = "2026-06-01"


def _preference_csv(path: Path) -> dict[str, int]:
    """25 statement rows, written by hand with the report's own column names.

    The arithmetic the test asserts:

    * 25 statement rows -> ``n_statements`` 25
    * 6 rows traded, over 5 DISTINCT ``trade_id`` (two rows name ``TR-2``)
      -> ``n_trades_matched`` 5, because ST5 counts a trade once
    * 19 rows with no trade -> ``n_trades_unmatched`` 19
    * of those 19, 3 were said on 2026-09-11 and their 10-session window is
      still open -> ``window_open`` 3, ``no_match_after_window`` 16
    * the journal was readable -> ``journal_unavailable`` 0

    The RECENCY trap: one June row carries ``journal_r`` 9.90, better than every
    other row in the file. A selection that ranks by result puts it in the
    examples; a selection by recency cannot.
    """
    from preference_trade_outcomes import COLUMNS

    rows: list[dict[str, object]] = []

    def _row(**values):
        row = {column: "" for column in COLUMNS}
        row["schema"] = "preference_trade_outcomes_v1"
        row["generated_at"] = f"{SESSION}T20:00:00-07:00"
        row.update(values)
        rows.append(row)

    # The better OLD row - the one a ranking by result would surface.
    _row(
        session_date=_CLOSED_SESSION, symbol="NVDA", side="LONG", channel="journal",
        statement="liked the reclaim", statement_id="S-OLD-BEST", traded="yes",
        trade_id="TR-1", trade_opened_at=f"{_CLOSED_SESSION}T09:45:00-07:00",
        match_confidence="0.9", match_basis="symbol+side+same_session",
        journal_r="9.90", journal_net_pnl="9900.00",
    )
    # Five more traded rows, two of them about the SAME trade.
    for index, (symbol, trade_id) in enumerate(
        [("AAPL", "TR-2"), ("AAPL", "TR-2"), ("MSFT", "TR-3"),
         ("AMD", "TR-4"), ("TSLA", "TR-5")],
        start=1,
    ):
        _row(
            session_date=f"2026-08-{10 + index:02d}", symbol=symbol, side="LONG",
            channel="journal", statement=f"watching {symbol}",
            statement_id=f"S-TRADED-{index}", traded="yes", trade_id=trade_id,
            trade_opened_at=f"2026-08-{10 + index:02d}T09:45:00-07:00",
            match_confidence="0.7", match_basis="symbol+side+window",
            journal_r="0.40", journal_net_pnl="120.00",
        )
    # Sixteen untraded statements whose windows have closed.
    for index in range(1, 17):
        _row(
            session_date=_CLOSED_SESSION, symbol=f"SYM{index:02d}", side="LONG",
            channel="market_journal", statement=f"note {index}",
            statement_id=f"S-CLOSED-{index:02d}", traded="no",
            match_confidence="0.0", match_basis="no match",
        )
    # Three untraded statements said yesterday: the window is still OPEN.
    for index in range(1, 4):
        _row(
            session_date=_OPEN_SESSION, symbol=f"OPEN{index}", side="SHORT",
            channel="market_journal", statement=f"fresh note {index}",
            statement_id=f"S-OPEN-{index}", traded="no",
            match_confidence="0.0", match_basis="no match",
        )

    assert len(rows) == 25
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=COLUMNS, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    return {"n_statements": 25, "n_trades_matched": 5, "n_trades_unmatched": 19,
            "window_open": 3, "no_match_after_window": 16, "journal_unavailable": 0}


def _preference_section(package):
    """The section, found by what it CONTAINS rather than by a chosen id."""
    for source in package.get("sources") or ():
        content = source.get("content")
        if isinstance(content, dict) and "n_statements" in content:
            return content
        if isinstance(content, dict):
            nested = content.get("preference_to_trade")
            if isinstance(nested, dict):
                return nested
    return None


def test_the_nightly_package_carries_the_preference_to_trade_section(
    tmp_path, monkeypatch
):
    """Item 6: four counts, the window named in SESSIONS, and coverage.

    `ai_summary.SCOPE_LABELS` has ten scopes today and none of them is this one,
    so `build_evidence_package` raises on the name. The reader must resolve
    `preference_trade_outcomes.REPORT_FILE` at CALL time, which is how this test
    points it at a fixture instead of the live report.
    """
    import ai_summary
    import preference_trade_outcomes

    report = tmp_path / "preference_trade_outcomes.csv"
    expected = _preference_csv(report)
    monkeypatch.setattr(preference_trade_outcomes, "REPORT_FILE", report)

    assert "preference_to_trade" in ai_summary.SCOPE_LABELS, (
        "the nightly package has no preference_to_trade scope"
    )

    overrides = {
        source_id: report
        for source_id, _label, _path in (
            ai_summary._source_specs().get("preference_to_trade") or []
        )
    }
    package = ai_summary.build_evidence_package(
        ["preference_to_trade"],
        session_date=SESSION,
        now=NOW,
        source_overrides=overrides,
    )

    section = _preference_section(package)
    assert section is not None, "the package carries no preference_to_trade section"
    assert section["n_statements"] == expected["n_statements"]
    assert section["n_trades_matched"] == expected["n_trades_matched"], (
        "a trade named by two statements is ONE trade (ST5's grain)"
    )
    assert section["n_trades_unmatched"] == expected["n_trades_unmatched"]
    assert "10 sessions" in str(section.get("window") or ""), (
        "the window carries its unit; 10 calendar days is a different number"
    )

    coverage = section.get("coverage") or {}
    assert coverage.get("window_open") == expected["window_open"], (
        "a statement whose 10-session window is still open is not a miss"
    )
    assert coverage.get("no_match_after_window") == expected["no_match_after_window"]
    assert coverage.get("journal_unavailable") == expected["journal_unavailable"]
    assert (
        coverage["window_open"] + coverage["no_match_after_window"]
        + coverage["journal_unavailable"]
    ) == expected["n_trades_unmatched"], "the coverage counts account for every miss"


def test_the_preference_examples_are_the_newest_not_the_best(tmp_path, monkeypatch):
    """Item 6: selection is by RECENCY, and it is bounded at 20.

    The June row carries `journal_r` 9.90 - the best in the file by a factor of
    twenty - and it is also the oldest. A section that ranks by result shows it;
    a section that takes the newest twenty cannot. Every example carries a
    pointer back to the row it came from.
    """
    import ai_summary
    import preference_trade_outcomes

    report = tmp_path / "preference_trade_outcomes.csv"
    _preference_csv(report)
    monkeypatch.setattr(preference_trade_outcomes, "REPORT_FILE", report)

    assert "preference_to_trade" in ai_summary.SCOPE_LABELS, (
        "the nightly package has no preference_to_trade scope"
    )
    overrides = {
        source_id: report
        for source_id, _label, _path in (
            ai_summary._source_specs().get("preference_to_trade") or []
        )
    }
    package = ai_summary.build_evidence_package(
        ["preference_to_trade"],
        session_date=SESSION,
        now=NOW,
        source_overrides=overrides,
    )
    section = _preference_section(package)
    assert section is not None, "the package carries no preference_to_trade section"

    examples = list(section.get("examples") or ())
    assert len(examples) == 20, "at most 20, and here there are 25 to choose from"
    ids = [str(row.get("statement_id") or "") for row in examples]
    assert "S-OLD-BEST" not in ids, (
        "the best row is the oldest; selecting it means selecting by result"
    )
    # The three 2026-09-11 statements are the newest in the file and must all
    # be present.
    for index in range(1, 4):
        assert f"S-OPEN-{index}" in ids
    assert all(str(row.get("row_id") or row.get("statement_id") or "") for row in examples), (
        "every example points back at the row it was read from"
    )


# ---------------------------------------------------------------------------
# Guards the builder may not break
# ---------------------------------------------------------------------------


def test_the_runner_slot_order_is_unchanged_by_this_packet():
    """Decision 0018: a later phase appends inside its stage, never reorders.

    Pinned here as well as in `tests/test_ai_jobs_runner.py` so a change made
    for this packet fails in the packet's own file.
    """
    from ai_jobs.runner import default_slots

    from test_ai_jobs_runner import EXPECTED_SLOT_ORDER

    assert tuple(slot.name for slot in default_slots()) == EXPECTED_SLOT_ORDER
    assert "weekly_synthesis" not in EXPECTED_SLOT_ORDER, (
        "the weekly synthesis slot stays optional and unscheduled"
    )


def test_the_enrichment_module_can_reach_nothing_that_writes_a_live_decision():
    """The model writes advice and nothing else - checked by walking the code.

    Wider than the existing guard in
    `tests/test_ai_enrichment_and_policy_draft.py`: the watchlist writer, the
    Focus store, the review policy and the alert paths are named here too,
    because this packet gives the enrichment a new provider call and a new
    write, and a new import is exactly how one of those would arrive.
    """
    import ast

    tree = ast.parse(Path(enrichment.__file__).read_text(encoding="utf-8"))
    imported: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imported.add(node.module)

    forbidden = (
        "bounce_bot", "autopilot_core", "master_avwap", "technical_integrity",
        "price_alert", "d1_level_feed", "focus_pick_store", "candidate_registry",
        "review_learning", "regime_pause_focus", "m5_signal_engines",
        "focus_adoption_gate", "journal_bulk_tag",
    )
    for name in imported:
        assert not name.startswith(forbidden), (
            f"the enrichment module reached live decision code: {name}"
        )

    # String constants that could BE a path. Prose is excluded on purpose: the
    # module's own docstring names `review_policy.json` in the sentence that
    # forbids writing it, and a filename has no spaces.
    tokens = [
        node.value for node in ast.walk(tree)
        if isinstance(node, ast.Constant)
        and isinstance(node.value, str)
        and node.value.strip()
        and not any(character.isspace() for character in node.value)
    ]
    for token in tokens:
        assert not token.endswith(
            ("review_policy.json", "longs.txt", "shorts.txt",
             "swinglongs.txt", "shortswings.txt", "focus_auto_picks.json")
        ), f"the enrichment module names {token} as a path"
