"""WS-PT4 - the AWAY digest ranks its swing picks by POINTS when the switch is on.

WISHLIST item 4 (points), block 4, in the trader's words: *"rank the AWAY
digest's swing picks by points too (today it ranks by the family's Wilson
bound)"*. The lead's ruling: the digest ranks by points ONLY when the EXISTING
Points switch (`setup_points.rank_enabled`, local setting
`rank_setups_by_points`, read AT SORT TIME) is on; off keeps today's order
exactly. Same switch, same weights, same `RANKED_BUCKETS` rule as the desk's
setups table - one scorer, two callers.

The golden `tests/fixtures/ws_pt4_away_digest_switch_off.txt` was pinned from
the code BEFORE this packet (a fixture generated by the code it is meant to pin
is a self-portrait), so the switch-off test is a characterization of the whole
digest text and not of the new ordering.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT / "scripts") not in sys.path:
    sys.path.insert(0, str(ROOT / "scripts"))

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

import pytest  # noqa: E402

import autopilot_core as core  # noqa: E402
import setup_points  # noqa: E402
from swing_headline import wilson_lower_bound  # noqa: E402

GOLDEN_PATH = ROOT / "tests" / "fixtures" / "ws_pt4_away_digest_switch_off.txt"

#: A tracker record where the graded families disagree with the point system.
RECORDS = {
    "avwape_retest": {"wins": 33, "losses": 7},      # lower bound ~0.68
    "first_dev_hold": {"wins": 56, "losses": 34},    # lower bound ~0.52
    "thin_thing": {"wins": 3, "losses": 0},          # lower bound ~0.44
}

RECORD_LINE = (
    "favorable_direction_scanrow_v1 over 5 scan rows, last 20 sessions "
    "(2026-06-02..2026-06-30): 94 eligible / 0 pending / 1 excluded (stale_horizon 1)"
)


def _pick(symbol, *, bucket, family, expected_r, raw=None, side="LONG",
          d1_vs_sector=None, d1_vs_industry=None, key_level="123.45"):
    return {
        "symbol": symbol,
        "side": side,
        "bucket": bucket,
        "expected_r": expected_r,
        "family": family,
        "key_level": key_level,
        "raw": dict(raw or {}),
        "d1_vs_sector": d1_vs_sector,
        "d1_vs_industry": d1_vs_industry,
    }


def _picks():
    """Arrival order. The Wilson order and the points order are different."""
    return [
        # A clean, bouncing favourite of the best-graded family.
        _pick(
            "AAA",
            bucket="favorite_setup",
            family="avwape_retest",
            expected_r=0.9,
            d1_vs_sector=3.0,
            d1_vs_industry=2.0,
            raw={
                "expected_r": 0.9,
                "setup_family": "avwape_retest",
                "daily_relative_strength_score": 4.0,
                "has_bounce_event_today": True,
                "previous_close": 100.0,
                "atr20": 2.0,
            },
        ),
        # A near-favourite with the best expected R and a blocked path.
        _pick(
            "BBB",
            bucket="near_favorite_zone",
            family="first_dev_hold",
            expected_r=1.2,
            d1_vs_sector=-2.0,
            d1_vs_industry=-1.0,
            raw={
                "expected_r": 1.2,
                "setup_family": "first_dev_hold",
                "daily_relative_strength_score": -3.0,
                "hv_level_blocking_count": 2,
                "hv_level_nearby_count": 1,
                "cloud_level_nearby_count": 1,
                "trendline_note": "descending trendline overhead",
                "previous_close": 50.0,
                "atr20": 1.0,
                "ema21": 50.6,
                "hv_level_nearest_distance_atr": 0.2,
            },
        ),
        # A thin family on a clean path - the Wilson bound punishes n=3.
        _pick(
            "CCC",
            bucket="high_conviction",
            family="thin_thing",
            expected_r=0.5,
            d1_vs_sector=1.0,
            d1_vs_industry=1.0,
            raw={
                "expected_r": 0.5,
                "setup_family": "thin_thing",
                "daily_relative_strength_score": 1.0,
                "previous_close": 20.0,
                "atr20": 0.5,
            },
        ),
        # NOT a ranked bucket: it sits high under the Wilson order and must
        # fall behind every ranked row when the points switch is on.
        _pick(
            "DDD",
            bucket="watch",
            family="avwape_retest",
            expected_r=0.2,
            d1_vs_sector=5.0,
            d1_vs_industry=5.0,
            raw={
                "expected_r": 0.2,
                "setup_family": "avwape_retest",
                "daily_relative_strength_score": 5.0,
                "has_bounce_event_today": True,
                "previous_close": 10.0,
                "atr20": 0.5,
            },
        ),
        # Every points input missing: no raw, no RS, an ungraded family.
        _pick("EEE", bucket="favorite_setup", family="no_such_family", expected_r=0.3, raw={}),
    ]


def _payload(**extra):
    body = {
        "generated_at": "2026-09-12 10:00:00",
        "enabled": True,
        "auto_mode": "AWAY",
        "ib_status": "connected",
        "regime": "trend_up",
        "longs": ["AAA", "BBB"],
        "shorts": ["ZZZ"],
        "swing_picks": _picks(),
        "swing_family_records": dict(RECORDS),
        "swing_family_record_line": RECORD_LINE,
        "swing_data_current": True,
        "swing_data_line": "Swing data: current session 2026-09-12 (focus)",
        "alerts": [],
        "slots_done": [],
        "next_slot": "",
        "log_lines": [],
    }
    body.update(extra)
    return body


def _pick_by_symbol(symbol):
    for pick in _picks():
        if pick["symbol"] == symbol:
            return pick
    raise AssertionError(f"no fixture pick {symbol}")


def _switch(monkeypatch, enabled):
    """The ONE seam: `setup_points.rank_enabled`, never a copied settings key."""
    monkeypatch.setattr(setup_points, "rank_enabled", lambda: bool(enabled))
    monkeypatch.setattr(setup_points, "active_weights", dict)


def _pick_order(text):
    """The symbols of the numbered swing lines, in printed order."""
    order = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped or not stripped[0].isdigit() or ". " not in stripped:
            continue
        head, rest = stripped.split(". ", 1)
        if not head.isdigit():
            continue
        symbol = rest.split(" ", 1)[0]
        if symbol.isalpha() and symbol.isupper():
            order.append(symbol)
    return order


def _with_order_clause(golden, label):
    """The golden text with the order named on its ONE `Ranked on:` line."""
    lines = golden.splitlines(keepends=True)
    hits = [i for i, line in enumerate(lines) if line.startswith("Ranked on: ")]
    assert len(hits) == 1, "the golden must carry exactly one `Ranked on:` line"
    index = hits[0]
    body = lines[index].rstrip("\n")
    tail = lines[index][len(body):]
    lines[index] = f"{body} | {label}{tail}"
    return "".join(lines)


# ---------------------------------------------------------------------------
# Item 2 - the switch decides the order, and the digest says which it used
# ---------------------------------------------------------------------------
def test_ws_pt4_switch_off_leaves_the_digest_as_the_golden_pinned_it(monkeypatch):
    """OFF is today's digest, byte for byte, plus the label naming the order.

    The golden was written by the code BEFORE this packet. Every byte of the
    switch-off digest is accounted for here: the only difference the packet
    allows is the ` | order: Wilson bound` clause on the existing `Ranked on:`
    line, which the gate asks the trader to read on the desk.
    """
    _switch(monkeypatch, False)
    text = core.render_away_report(_payload())
    golden = GOLDEN_PATH.read_text(encoding="utf-8")
    assert text == _with_order_clause(golden, "order: Wilson bound")
    # And the pick lines themselves are untouched: same names, same order.
    assert _pick_order(text) == _pick_order(golden)


def test_ws_pt4_switch_on_ranks_the_ranked_buckets_by_points(monkeypatch):
    """ON: favourite / near / high-conviction by total, everything else after."""
    _switch(monkeypatch, False)
    wilson_order = _pick_order(core.render_away_report(_payload()))
    _switch(monkeypatch, True)
    text = core.render_away_report(_payload())
    points_order = _pick_order(text)

    assert "order: points (switch on)" in text
    assert "order: Wilson bound" not in text
    assert sorted(points_order) == sorted(wilson_order), "nothing is dropped or added"
    assert points_order != wilson_order, "the fixture must actually re-order"

    totals = {
        pick["symbol"]: core.swing_pick_points(pick, RECORDS).total for pick in _picks()
    }
    ranked = [
        symbol
        for symbol in points_order
        if _pick_by_symbol(symbol)["bucket"] in setup_points.RANKED_BUCKETS
    ]
    rest = [symbol for symbol in points_order if symbol not in ranked]
    assert ranked == sorted(ranked, key=lambda s: -totals[s])
    assert points_order == ranked + rest, "every other pick comes after the ranked ones"
    # The rest keep the order they had - the Wilson order is the tiebreak.
    assert rest == [symbol for symbol in wilson_order if symbol in rest]


def test_ws_pt4_the_order_label_is_read_through_rank_enabled_and_nothing_else(monkeypatch):
    """The switch is `setup_points.rank_enabled()`, read at SORT time."""
    calls = []

    def _fake():
        calls.append(1)
        return True

    monkeypatch.setattr(setup_points, "rank_enabled", _fake)
    monkeypatch.setattr(setup_points, "active_weights", dict)
    text = core.render_away_report(_payload())
    assert calls, "the renderer must ask setup_points, never a copied key"
    assert "order: points (switch on)" in text


# ---------------------------------------------------------------------------
# Item 1 / 2 - one scorer, two callers
# ---------------------------------------------------------------------------
def test_ws_pt4_the_digest_total_is_setup_points_score_row_on_the_same_row():
    """The digest scores with the DESK's scorer over the desk's own fields."""
    for pick in _picks():
        entry = RECORDS.get(pick["family"]) or {}
        wins = int(entry.get("wins") or 0)
        losses = int(entry.get("losses") or 0)
        record = core.swing_family_points_record(RECORDS, pick["family"])
        # The same Wilson bound the Wilson ORDER uses, under the same key the
        # desk panel's `family_headline_rows` writes.
        assert record.get("win_rate_lb") == wilson_lower_bound(wins, wins + losses)
        expected = setup_points.score_row(
            pick["raw"],
            side=pick["side"],
            family_record=record,
            d1_vs_sector=pick["d1_vs_sector"],
            d1_vs_industry=pick["d1_vs_industry"],
            weights={},
        )
        assert core.swing_pick_points(pick, RECORDS, weights={}).total == expected.total


def test_ws_pt4_the_report_projection_carries_the_four_points_inputs():
    """Item 1: the digest's pick rows carry what the scorer reads."""
    from ui.models.setup import SetupRow

    row = SetupRow(
        symbol="FFF",
        side="SHORT",
        bucket="favorite_setup",
        expected_r=0.4,
        key_level="88.00",
        d1_vs_sector=-1.5,
        d1_vs_industry=-2.5,
        raw={
            "setup_family": "avwape_retest",
            "hv_level_blocking_count": 2,
            "has_bounce_event_today": True,
        },
    )
    projected = core.swing_pick_projection(row)
    assert projected["symbol"] == "FFF"
    assert projected["side"] == "SHORT"
    # The phone prints the LABEL; `setup_points.RANKED_BUCKETS` matches the KEY.
    assert projected["bucket"] == "Favorite"
    assert projected["bucket_key"] == "favorite_setup"
    assert projected["family"] == "avwape_retest"
    assert projected["key_level"] == "88.00"
    assert projected["d1_vs_sector"] == -1.5
    assert projected["d1_vs_industry"] == -2.5
    assert projected["raw"]["hv_level_blocking_count"] == 2
    assert projected["raw"]["has_bounce_event_today"] is True


def test_ws_pt4_the_ranked_buckets_are_matched_on_the_key_not_the_display_label(monkeypatch):
    """The real digest prints `Favorite`, not `favorite_setup`.

    `setup_points.RANKED_BUCKETS` holds the row's own bucket keys, so a digest
    that matched on the printed label would rank NOTHING and silently fall back
    to arrival order - the failure this test exists to catch.
    """
    _switch(monkeypatch, True)
    # The best BOUND and the worst points; it leads under the Wilson order, so
    # a ranking that quietly matched nothing would leave it leading.
    weak = _pick(
        "LOW",
        bucket="Favorite",
        family="avwape_retest",
        expected_r=0.0,
        d1_vs_sector=-5.0,
        d1_vs_industry=-5.0,
        raw={
            "expected_r": 0.0,
            "setup_family": "avwape_retest",
            "daily_relative_strength_score": -5.0,
            "hv_level_blocking_count": 3,
        },
    )
    strong = _pick(
        "HIGH",
        bucket="Favorite",
        family="first_dev_hold",
        expected_r=1.0,
        d1_vs_sector=4.0,
        d1_vs_industry=4.0,
        raw={
            "expected_r": 1.0,
            "setup_family": "first_dev_hold",
            "daily_relative_strength_score": 4.0,
            "has_bounce_event_today": True,
        },
    )
    for pick in (weak, strong):
        pick["bucket_key"] = "favorite_setup"
    text = core.render_away_report(_payload(swing_picks=[weak, strong]))
    assert _pick_order(text) == ["HIGH", "LOW"]


def test_ws_pt4_the_report_writer_uses_the_one_projection():
    """The service must not keep a second, narrower copy of the pick fields."""
    from ui.services import autopilot_service

    source = Path(autopilot_service.__file__).read_text(encoding="utf-8")
    assert "core.swing_pick_projection(" in source


# ---------------------------------------------------------------------------
# Item 3 - a missing input scores 0 with the note, and is never dropped
# ---------------------------------------------------------------------------
def test_ws_pt4_a_pick_missing_every_points_input_is_scored_not_dropped(monkeypatch):
    _switch(monkeypatch, True)
    text = core.render_away_report(_payload())
    assert "EEE" in _pick_order(text)

    points = core.swing_pick_points(_pick_by_symbol("EEE"), RECORDS, weights={})
    assert points.setup == 0.0
    notes = " | ".join(points.notes)
    assert "family ungraded" in notes
    assert "RS vs SPY unmeasured" in notes
    assert "RS vs sector unmeasured" in notes
    assert "RS vs industry unmeasured" in notes


def test_ws_pt4_an_absent_family_record_still_ranks_and_still_says_so(monkeypatch):
    """No tracker record at all: the points order still applies and is named."""
    _switch(monkeypatch, True)
    text = core.render_away_report(_payload(swing_family_records={}))
    assert "order: points (switch on)" in text
    assert len(_pick_order(text)) == 5


# ---------------------------------------------------------------------------
# The near cap is applied AFTER the ranking, exactly as today
# ---------------------------------------------------------------------------
def _near(symbol, *, rs, bounce=False):
    return _pick(
        symbol,
        bucket="near_favorite_zone",
        family="first_dev_hold",
        expected_r=0.5,
        d1_vs_sector=rs,
        d1_vs_industry=rs,
        raw={
            "expected_r": 0.5,
            "setup_family": "first_dev_hold",
            "daily_relative_strength_score": rs,
            "has_bounce_event_today": bounce,
            "previous_close": 30.0,
            "atr20": 1.0,
        },
    )


@pytest.mark.parametrize("enabled", [False, True])
def test_ws_pt4_the_near_cap_is_applied_after_the_ranking(monkeypatch, enabled):
    _switch(monkeypatch, enabled)
    near_picks = [
        _near("NA", rs=-4.0),
        _near("NB", rs=4.0, bounce=True),
        _near("NC", rs=0.0),
        _near("ND", rs=3.0, bounce=True),
        _near("NE", rs=-2.0),
    ]
    text = core.render_away_report(_payload(swing_picks=near_picks))
    shown = _pick_order(text)
    assert len(shown) == core.AWAY_REPORT_MAX_NEAR_ROWS
    assert "(+2 more near-favorite rows hidden" in text
    if enabled:
        # What is hidden is the weakest by POINTS, never the best one.
        totals = {p["symbol"]: core.swing_pick_points(p, RECORDS).total for p in near_picks}
        assert shown == sorted(totals, key=lambda s: -totals[s])[:3]
