"""WS-SN2 - fetch new M5 bars only (WISHLIST item 4, required result 2).

Written BEFORE the fix; every test here must FAIL on the pre-SN2 code.

Today ``BounceBot.request_and_detect_bounce``
(``scripts/bounce_bot_lib/legacy.py``) asks IB for ``durationStr="5 D"`` of
5-minute bars for EVERY symbol on EVERY cycle - ~390 bars / ~206 KB a symbol,
586 symbol scans a cycle, ~120 MB fetched and ~230,000 rows parsed every 25
minutes, all on the interpreter lock the GUI needs (trader, 2026-09-08).

SN2 fetches the five days ONCE per symbol per day, keeps the frame, and then
asks only for the bars since the last COMPLETED one.  The thing that must not
change is the frame: **what the detectors read after a delta fetch is
byte-for-byte what a fresh full fetch would have produced**, dtypes and index
included.  That is what the golden fixture pins.

The three faults these tests exist for:

* a FORMING bar that slipped into the cache must force a whole-window refetch,
  never a merge (a merged forming bar is a detector reading a preview as a
  state transition - ``plan.md`` sec 5);
* a delta that does not line up with the cache (the overlap bar's dt or close
  moved - a revision, a corporate action, a halt) must force a whole-window
  refetch;
* a symbol that leaves the scanned set must not keep its frame in memory.

The seam the builder is expected to add (used by the last test):
``BounceBot.cached_bounce_frame(symbol)`` returns whatever the SN2 cache is
holding for that symbol - any shape the builder likes - or ``None`` when
nothing is retained.  These tests only ever ask whether it is ``None``.

Nothing here touches a live store or a socket: the bars are a recorded
synthetic series and IB is a fake that answers ``reqHistoricalData`` the way
TWS does (honouring ``durationStr`` and ``endDateTime``, completed bars only
unless the test asks for a forming one).

Trap the builder should know about before reading the failures: the existing
``if len(all_bars) < 10: return`` guard is about the WHOLE window.  A realistic
delta is five bars (one 25-minute cycle), so that guard must move to the merged
result or the delta path returns early and builds no frame at all.
"""

from __future__ import annotations

import json
import os
import random
import subprocess
import sys
import threading
from datetime import date, datetime, timedelta
from pathlib import Path
from types import SimpleNamespace

import pandas as pd
import pytest
from pandas.testing import assert_frame_equal

ROOT_DIR = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT_DIR / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import bounce_bot  # noqa: E402
from market_session import get_market_local_timezone  # noqa: E402

FIXTURE_PATH = Path(__file__).resolve().parent / "fixtures" / "ws_sn2_fresh_frames.json"

# The LAST commit before any SN2 code change.  A golden fixture regenerated by
# the code it is meant to pin is a self-portrait; change the code, not this.
PINNED_SOURCE_COMMIT = "b8bdec24e7a3b1b673d821d788a849b11bddc540"

SERIES_VERSION = "ws_sn2_synthetic_v1"

SYMBOL = "AAA"
OTHER_SYMBOL = "BBB"

#: Six exchange sessions, so a "5 D" request on the sixth drops the first.
SESSION_DATES = (
    date(2026, 6, 1),
    date(2026, 6, 2),
    date(2026, 6, 3),
    date(2026, 6, 4),
    date(2026, 6, 5),
    date(2026, 6, 8),
)
SESSION_OPEN_HOUR = 6  # market-local (Pacific) wall clock, as the desk's bars are
SESSION_OPEN_MINUTE = 30
BARS_PER_SESSION = 78  # 06:30 .. 12:55 inclusive
BAR_MINUTES = 5

FULL_WINDOW_DURATION = "5 D"
FULL_WINDOW_DAYS = 5

# The cycle clock.  A real scan cycle measured ~25 minutes on 2026-09-08, so a
# delta is five 5-minute bars - deliberately fewer than the ten-bar guard.
CYCLE_1_NOW = datetime(2026, 6, 5, 9, 0)
CYCLE_2_NOW = datetime(2026, 6, 5, 9, 25)
CYCLE_3_NOW = datetime(2026, 6, 5, 9, 50)
CYCLE_4_NOW = datetime(2026, 6, 5, 10, 15)

# The day roll: last cycle of Friday, first two cycles of Monday.
FRIDAY_LAST_NOW = datetime(2026, 6, 5, 13, 5)
MONDAY_FIRST_NOW = datetime(2026, 6, 8, 7, 0)
MONDAY_SECOND_NOW = datetime(2026, 6, 8, 7, 30)

# A forming bar: 09:22 is inside the 09:20 bar, which does not close until 09:25.
FORMING_NOW = datetime(2026, 6, 5, 9, 22)

SERIES_RECIPE = {
    SYMBOL: (2026, 148.0, 0.021),
    OTHER_SYMBOL: (5905, 61.5, -0.013),
}

IB_TIME_FORMAT = "%Y%m%d  %H:%M:%S"  # two spaces, as TWS sends with formatDate=1


# --------------------------------------------------------- the recorded bars


def _session_bar_starts(session_date, count=BARS_PER_SESSION):
    start = datetime(
        session_date.year,
        session_date.month,
        session_date.day,
        SESSION_OPEN_HOUR,
        SESSION_OPEN_MINUTE,
    )
    return [start + timedelta(minutes=BAR_MINUTES * i) for i in range(count)]


def recorded_series(symbol=SYMBOL):
    """A deterministic OHLCV walk honouring ``low <= open, close <= high``.

    Rows are the raw dicts ``historicalData`` appends, so what the fake serves
    is exactly what the real callback would have.
    """
    seed, price, drift = SERIES_RECIPE[symbol]
    rng = random.Random(seed)
    starts = []
    for session_date in SESSION_DATES:
        starts.extend(_session_bar_starts(session_date))
    rows = []
    for index, bar_start in enumerate(starts):
        open_ = price
        step = drift + rng.uniform(-0.35, 0.35) * (open_ * 0.002)
        close = round(open_ + step, 4)
        span = abs(open_ * 0.0012) + abs(step) * 0.6 + 0.01
        high = round(max(open_, close) + rng.uniform(0.05, 1.0) * span, 4)
        low = round(min(open_, close) - rng.uniform(0.05, 1.0) * span, 4)
        rows.append(
            {
                "start": bar_start,
                "time": bar_start.strftime(IB_TIME_FORMAT),
                "open": round(open_, 4),
                "high": high,
                "low": low,
                "close": close,
                "volume": 10_000 + index,
            }
        )
        price = close
    return rows


def revise_close_of_bar_starting(rows, bar_start, new_close):
    """A revised print on an already-served bar - the fault the identity check
    exists for.  Returns a new series; the original is untouched."""
    revised = []
    found = False
    for row in rows:
        if row["start"] == bar_start:
            row = dict(row)
            row["close"] = new_close
            row["high"] = max(row["high"], new_close)
            row["low"] = min(row["low"], new_close)
            found = True
        revised.append(row)
    assert found, "no bar starts at %s; the revision test proves nothing" % (bar_start,)
    return revised


# ------------------------------------------------------------------ fake IB


def duration_seconds(duration_text):
    """IB duration string -> seconds.  Unknown units fail loudly."""
    parts = str(duration_text or "").strip().split()
    if len(parts) != 2:
        raise AssertionError("unreadable durationStr %r" % (duration_text,))
    size = int(parts[0])
    unit = parts[1].upper()
    if unit == "S":
        return size
    if unit == "D":
        return size * 86_400
    if unit == "W":
        return size * 7 * 86_400
    raise AssertionError(
        "durationStr %r uses a unit this fake does not serve; SN2 should ask "
        "in seconds or days" % (duration_text,)
    )


def is_whole_window_request(request):
    """A request for the full five days, however it is spelled."""
    return duration_seconds(request.duration) >= 86_400


class FakeIb:
    """Answers ``reqHistoricalData`` from a recorded series, the way TWS does.

    * ``endDateTime=""`` means "up to now"; an explicit stamp is honoured.
    * ``durationStr`` in days selects that many SESSIONS ending at the end
      stamp (this is what makes "5 D" slide across a day roll and drop the
      oldest session); a duration in seconds selects a wall-clock window.
    * Only COMPLETED bars are served (``bar_start + 5 min <= end``) unless
      ``serve_forming_bar`` is on - that switch is how the partial-last-bar
      fault is injected.
    """

    def __init__(self, bot, series):
        self.bot = bot
        self.series = list(series)
        self.now = CYCLE_1_NOW
        self.serve_forming_bar = False
        self.requests = []  # every request, in order
        self.cycle_index = -1
        self._next_req_id = 1000

    # -- harness ----------------------------------------------------------

    def start_cycle(self, now):
        self.cycle_index += 1
        self.now = now

    def requests_in_cycle(self, cycle_index):
        return [req for req in self.requests if req.cycle == cycle_index]

    def bars_served_in_cycle(self, cycle_index):
        return sum(req.served for req in self.requests_in_cycle(cycle_index))

    # -- the IB seam ------------------------------------------------------

    def get_req_id(self):
        self._next_req_id += 1
        return self._next_req_id

    def req_historical_data(self, **kwargs):
        req_id = kwargs["reqId"]
        end_text = str(kwargs.get("endDateTime") or "").strip()
        end = self.now if not end_text else _parse_end_stamp(end_text)
        duration = kwargs.get("durationStr")
        record = SimpleNamespace(
            cycle=self.cycle_index,
            symbol=getattr(kwargs.get("contract"), "symbol", None),
            duration=duration,
            bar_size=kwargs.get("barSizeSetting"),
            end=end_text,
            served=0,
        )
        self.requests.append(record)

        for row in self._rows_for(duration, end):
            record.served += 1
            self.bot.historicalData(
                req_id,
                SimpleNamespace(
                    date=row["time"],
                    open=row["open"],
                    high=row["high"],
                    low=row["low"],
                    close=row["close"],
                    volume=row["volume"],
                ),
            )
        self.bot.historicalDataEnd(req_id, "", "")

    def _rows_for(self, duration, end):
        span = timedelta(minutes=BAR_MINUTES)
        if self.serve_forming_bar:
            visible = [row for row in self.series if row["start"] <= end]
        else:
            visible = [row for row in self.series if row["start"] + span <= end]
        if not visible:
            return []
        seconds = duration_seconds(duration)
        if seconds >= 86_400:
            sessions = sorted({row["start"].date() for row in visible})
            kept = set(sessions[-(seconds // 86_400):])
            return [row for row in visible if row["start"].date() in kept]
        floor = end - timedelta(seconds=seconds)
        return [row for row in visible if row["start"] >= floor]


def _parse_end_stamp(text):
    cleaned = text.replace("  ", " ").strip()
    for fmt in ("%Y%m%d %H:%M:%S", "%Y%m%d-%H:%M:%S", "%Y%m%d"):
        try:
            return datetime.strptime(cleaned, fmt)
        except ValueError:
            continue
    raise AssertionError("unreadable endDateTime %r" % (text,))


# ------------------------------------------------------------------ the bot


class Harness:
    """A real ``BounceBot`` whose fetch path is real and whose IB is fake.

    Real: ``request_and_detect_bounce``, ``historicalData``,
    ``historicalDataEnd``, ``_bars_to_ib``, ``_dedupe_bars``, the DataFrame
    build and ``_prune_latest_bars_for_cycle``.  Stubbed: the socket, the
    evidence emitters, and the Focus/watchlist file readers.
    """

    def __init__(self, monkeypatch, series=None, symbol=SYMBOL):
        bot = object.__new__(bounce_bot.BounceBot)
        bot.data_lock = threading.Lock()
        bot.data = {}
        bot.data_ready_events = {}
        bot.latest_bars = {}
        bot.symbol_metrics = {}
        bot.pending_bounce_outcomes = {}
        bot.longs = [SYMBOL, OTHER_SYMBOL]
        bot.shorts = []
        bot.auto_longs = []
        bot.auto_shorts = []
        bot.master_avwap_d1_watchlist = {}
        bot.master_avwap_focus_map = {}

        self.bot = bot
        self.frames = []  # every frame the detectors were handed, in order
        self.series_by_symbol = {}
        base = recorded_series(symbol) if series is None else list(series)
        self.series_by_symbol[symbol] = base
        self.ib = FakeIb(bot, base)

        bot.reqHistoricalData = self._req
        bot.create_stock_contract = lambda sym: SimpleNamespace(symbol=sym)
        bot.getReqId = self.ib.get_req_id

        # Capture point: the full frame every downstream reader is built from.
        def _capture(sym, df):
            self.frames.append((self.ib.cycle_index, sym, df))

        bot._update_pending_bounce_outcomes = _capture
        bot.emit_master_avwap_intraday_trigger_flags = lambda *a, **k: None
        bot.emit_master_avwap_zone_arm_flags = lambda *a, **k: None
        bot.emit_master_avwap_tier_flip_flags = lambda *a, **k: None
        bot._human_focus_side_for_symbol = lambda sym: ""
        bot._auto_watch_symbols = lambda side: set()

        market_tz, _name = get_market_local_timezone()
        self._market_tz = market_tz
        monkeypatch.setattr(
            bounce_bot,
            "get_market_local_now",
            lambda *args, **kwargs: self.ib.now.replace(tzinfo=market_tz),
        )

    def add_symbol(self, symbol):
        self.series_by_symbol[symbol] = recorded_series(symbol)

    def _req(self, **kwargs):
        symbol = getattr(kwargs.get("contract"), "symbol", None)
        self.ib.series = self.series_by_symbol[symbol]
        self.ib.req_historical_data(**kwargs)

    # -- driving ----------------------------------------------------------

    def cycle(self, now, symbols=(SYMBOL,)):
        """One scan cycle: the clock moves, then each symbol is scanned once."""
        self.ib.start_cycle(now)
        for symbol in symbols:
            self.bot.request_and_detect_bounce(symbol, scan_for_new_bounces=False)
        return self.ib.cycle_index

    def frame_for(self, symbol, cycle_index):
        """The frame handed to the detectors for ``symbol`` in THAT cycle.

        A cycle that built no frame is a failure, not an empty result: the
        ten-bar short-data guard swallowing a five-bar delta would otherwise
        read as "nothing to compare".
        """
        matches = [
            df for cycle, sym, df in self.frames if sym == symbol and cycle == cycle_index
        ]
        assert matches, (
            "cycle %s built no frame for %s at all - the detectors were handed "
            "nothing that cycle (requests: %s)"
            % (
                cycle_index,
                symbol,
                [
                    (req.duration, req.served)
                    for req in self.ib.requests_in_cycle(cycle_index)
                    if req.symbol == symbol
                ],
            )
        )
        assert len(matches) == 1, (
            "cycle %s built %s frames for %s; one scan is one frame"
            % (cycle_index, len(matches), symbol)
        )
        return matches[0]


def fresh_full_fetch_frame(monkeypatch, now, series=None):
    """What one fresh ``5 D`` fetch produces at ``now`` - the golden reference."""
    harness = Harness(monkeypatch, series=series)
    harness.cycle(now)
    frame = harness.frame_for(SYMBOL, 0)
    only = harness.ib.requests
    assert len(only) == 1 and only[0].duration == FULL_WINDOW_DURATION, (
        "the reference fetch must be one whole-window request, got %s"
        % ([req.duration for req in only],)
    )
    return frame


# --------------------------------------------------- the golden fixture I/O


def frame_to_record(frame):
    """Columns, dtypes and rows - so the reader rebuilds the frame EXACTLY,
    dtypes included.  A fixture that loses ``volume``'s int64 cannot catch a
    merge that turned it into a float."""
    columns = list(frame.columns)
    rows = []
    for row in frame.itertuples(index=False, name=None):
        rows.append(
            [
                value.isoformat() if isinstance(value, pd.Timestamp) else value
                for value in row
            ]
        )
    return {
        "columns": columns,
        "dtypes": {name: str(dtype) for name, dtype in frame.dtypes.items()},
        "rows": rows,
    }


def record_to_frame(record):
    frame = pd.DataFrame(record["rows"], columns=record["columns"])
    return frame.astype(record["dtypes"])


def load_fixture():
    if not FIXTURE_PATH.exists():  # pragma: no cover - only before generation
        pytest.fail("golden fixture missing: %s" % (FIXTURE_PATH,))
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


def golden(name):
    return record_to_frame(load_fixture()["frames"][name])


REVISED_BAR_START = datetime(2026, 6, 5, 8, 55)
REVISED_CLOSE = 999.25


def _revised_series():
    return revise_close_of_bar_starting(
        recorded_series(SYMBOL), REVISED_BAR_START, REVISED_CLOSE
    )


@pytest.mark.skipif(
    not os.environ.get("WS_SN2_WRITE_FIXTURE"),
    reason="fixture recording is a one-off on the PRE-SN2 code (WS_SN2_WRITE_FIXTURE=1)",
)
def test_record_the_fresh_fetch_golden_fixture(monkeypatch):
    """One-off recorder.  Never part of the red/green loop."""
    commit = subprocess.check_output(
        ["git", "rev-parse", "HEAD"], cwd=str(ROOT_DIR), text=True
    ).strip()
    frames = {
        "intraday_cycle_2": fresh_full_fetch_frame(monkeypatch, CYCLE_2_NOW),
        "intraday_cycle_3": fresh_full_fetch_frame(monkeypatch, CYCLE_3_NOW),
        "intraday_cycle_4": fresh_full_fetch_frame(monkeypatch, CYCLE_4_NOW),
        "monday_first": fresh_full_fetch_frame(monkeypatch, MONDAY_FIRST_NOW),
        "monday_second": fresh_full_fetch_frame(monkeypatch, MONDAY_SECOND_NOW),
        "revised_cycle_2": fresh_full_fetch_frame(
            monkeypatch, CYCLE_2_NOW, series=_revised_series()
        ),
    }
    payload = {
        "generated_from_commit": commit,
        "series_version": SERIES_VERSION,
        "provider_assumptions": (
            "Synthetic RTH 5-minute bars, no provider call; six sessions "
            "2026-06-01..2026-06-08, market-local session open 06:30, completed "
            "bars only (bar_start + 5 min <= now)."
        ),
        "frames": {name: frame_to_record(frame) for name, frame in frames.items()},
    }
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_PATH.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def test_the_golden_fixture_was_recorded_before_the_fix():
    """A fixture generated by the code it pins is a self-portrait."""
    fixture = load_fixture()
    assert fixture["generated_from_commit"] == PINNED_SOURCE_COMMIT
    assert fixture["series_version"] == SERIES_VERSION
    # The recording has to be a real window, not a stub: five sessions of
    # 5-minute bars with the sixth session's completed bars on the end.
    monday = record_to_frame(fixture["frames"]["monday_first"])
    sessions = sorted(monday["datetime"].dt.date.unique())
    assert len(sessions) == FULL_WINDOW_DAYS, sessions
    assert sessions[0] == date(2026, 6, 2), (
        "a 5 D window on the sixth session must have dropped the first session"
    )
    assert sessions[-1] == date(2026, 6, 8)


def test_the_golden_fixture_still_matches_a_fresh_fetch_of_the_current_code(monkeypatch):
    """The fixture is only worth anything while it still describes a fresh
    fetch.  This is the characterization: change the fetch path's OUTPUT and
    this fails, whatever the cache is doing."""
    for name, now, series in (
        ("intraday_cycle_2", CYCLE_2_NOW, None),
        ("intraday_cycle_3", CYCLE_3_NOW, None),
        ("intraday_cycle_4", CYCLE_4_NOW, None),
        ("monday_first", MONDAY_FIRST_NOW, None),
        ("monday_second", MONDAY_SECOND_NOW, None),
        ("revised_cycle_2", CYCLE_2_NOW, _revised_series()),
    ):
        assert_frame_equal(
            fresh_full_fetch_frame(monkeypatch, now, series=series), golden(name)
        )


# ------------------------------------------------------------- the packet's tests


def test_the_frame_built_from_cache_plus_delta_is_identical_to_a_fresh_fetch(monkeypatch):
    """SN2's whole promise: after the first cycle the symbol costs a delta, and
    what the detectors read is still exactly the fresh five-day frame."""
    harness = Harness(monkeypatch)
    harness.cycle(CYCLE_1_NOW)
    harness.cycle(CYCLE_2_NOW)

    assert_frame_equal(harness.frame_for(SYMBOL, 1), golden("intraday_cycle_2"))
    assert harness.bot.latest_bars[SYMBOL] == bounce_bot._dedupe_bars(
        bounce_bot._bars_to_ib(golden("intraday_cycle_2").to_dict(orient="records"))
    ), "the RRS bar cache must carry the same bars as the frame"

    whole_window = [req for req in harness.ib.requests if is_whole_window_request(req)]
    assert len(whole_window) == 1, (
        "the five days must be fetched ONCE per symbol per day; cycle 2 asked "
        "for %s" % ([req.duration for req in harness.ib.requests_in_cycle(1)],)
    )
    assert harness.ib.requests_in_cycle(1)[0].bar_size == "5 mins"


def test_the_day_roll_refetches_the_window_and_the_next_cycle_is_a_delta_again(monkeypatch):
    """A ``5 D`` window slides at the roll - Monday's window has dropped
    Monday-a-week-ago - so the cache cannot be appended to across it.  The roll
    refetches, and the cycle after it is a delta again."""
    harness = Harness(monkeypatch)
    harness.cycle(FRIDAY_LAST_NOW)
    harness.cycle(MONDAY_FIRST_NOW)
    harness.cycle(MONDAY_SECOND_NOW)

    assert any(is_whole_window_request(req) for req in harness.ib.requests_in_cycle(1)), (
        "the first cycle of a new day must refetch the whole window; it asked "
        "for %s" % ([req.duration for req in harness.ib.requests_in_cycle(1)],)
    )
    assert_frame_equal(harness.frame_for(SYMBOL, 1), golden("monday_first"))

    third = harness.ib.requests_in_cycle(2)
    assert third and not any(is_whole_window_request(req) for req in third), (
        "the cycle after the roll must be a delta again, not another five days; "
        "it asked for %s" % ([req.duration for req in third],)
    )
    assert_frame_equal(harness.frame_for(SYMBOL, 2), golden("monday_second"))


def test_a_forming_last_bar_forces_a_whole_window_refetch_and_the_cache_recovers(monkeypatch):
    """The fault the packet names.  A forming bar carries a preview price; a
    delta merged onto it writes that preview into the frame for good.  It must
    force a whole-window refetch, and the cycle after that is a delta again."""
    harness = Harness(monkeypatch)
    harness.ib.serve_forming_bar = True
    harness.cycle(FORMING_NOW)  # cycle 0: the 09:20 bar is still forming
    harness.ib.serve_forming_bar = False

    cached = harness.bot.latest_bars[SYMBOL]
    assert cached[-1].dt == datetime(2026, 6, 5, 9, 20), (
        "the fake must actually have served the forming bar, or this test "
        "proves nothing; last cached bar is %s" % (cached[-1].dt,)
    )

    harness.cycle(CYCLE_3_NOW)  # cycle 1: must NOT merge onto the forming bar
    harness.cycle(CYCLE_4_NOW)  # cycle 2: clean cache, back to a delta

    assert any(is_whole_window_request(req) for req in harness.ib.requests_in_cycle(1)), (
        "a partial last bar in the cache must trigger a whole-window refetch, "
        "never a merge; cycle 1 asked for %s"
        % ([req.duration for req in harness.ib.requests_in_cycle(1)],)
    )
    assert_frame_equal(harness.frame_for(SYMBOL, 1), golden("intraday_cycle_3"))

    third = harness.ib.requests_in_cycle(2)
    assert third and not any(is_whole_window_request(req) for req in third), (
        "after a clean refetch the next cycle must be a delta again; it asked "
        "for %s" % ([req.duration for req in third],)
    )
    assert_frame_equal(harness.frame_for(SYMBOL, 2), golden("intraday_cycle_4"))


def test_a_delta_that_does_not_line_up_with_the_cache_forces_a_whole_window_refetch(monkeypatch):
    """The identity check.  IB revises prints; a revised overlap bar means the
    cache and the delta are not the same series.  The delta request must cover
    the cache's last bar so dt AND close can be compared, and a mismatch must
    throw the cache away rather than splice two different series together."""
    harness = Harness(monkeypatch)
    harness.cycle(CYCLE_1_NOW)

    # 08:55 is the last bar the cache holds; its close is revised behind us.
    harness.series_by_symbol[SYMBOL] = _revised_series()
    harness.cycle(CYCLE_2_NOW)

    second = harness.ib.requests_in_cycle(1)
    assert second, "cycle 2 issued no request"
    assert not is_whole_window_request(second[0]), (
        "cycle 2 must ASK for the delta first - the mismatch is only visible "
        "once the overlap bar comes back; it asked for %s"
        % ([req.duration for req in second],)
    )
    assert duration_seconds(second[0].duration) >= 2 * BAR_MINUTES * 60, (
        "the delta request must reach back over the cache's last bar, or there "
        "is nothing to check the identity against (duration was %r)"
        % (second[0].duration,)
    )
    assert any(is_whole_window_request(req) for req in second), (
        "a mismatched overlap bar must force a whole-window refetch; cycle 2 "
        "only asked for %s" % ([req.duration for req in second],)
    )
    assert_frame_equal(harness.frame_for(SYMBOL, 1), golden("revised_cycle_2"))


def test_after_the_first_cycle_a_symbol_costs_one_delta_request_per_cycle(monkeypatch):
    """The measurement: 1 x "5 D" on the first cycle of the day, then 1 x delta
    a cycle.  ~390 bars a symbol a cycle becomes ~5."""
    harness = Harness(monkeypatch)
    harness.cycle(CYCLE_1_NOW)
    harness.cycle(CYCLE_2_NOW)
    harness.cycle(CYCLE_3_NOW)
    harness.cycle(CYCLE_4_NOW)

    first = harness.ib.requests_in_cycle(0)
    assert len(first) == 1 and first[0].duration == FULL_WINDOW_DURATION
    assert harness.ib.bars_served_in_cycle(0) > 300, (
        "the first cycle of the day is the whole window; it served %s bars"
        % (harness.ib.bars_served_in_cycle(0),)
    )

    for cycle_index in (1, 2, 3):
        requests = harness.ib.requests_in_cycle(cycle_index)
        assert len(requests) == 1, (
            "cycle %s must cost exactly one request per symbol, it made %s (%s)"
            % (cycle_index, len(requests), [req.duration for req in requests])
        )
        assert not is_whole_window_request(requests[0]), (
            "cycle %s refetched the whole five days (%r) instead of the delta"
            % (cycle_index, requests[0].duration)
        )
        served = harness.ib.bars_served_in_cycle(cycle_index)
        assert served <= 12, (
            "a 25-minute cycle is five new 5-minute bars plus an overlap; "
            "cycle %s pulled %s bars" % (cycle_index, served)
        )

    assert_frame_equal(harness.frame_for(SYMBOL, 3), golden("intraday_cycle_4"))


def test_a_symbol_that_leaves_the_scanned_set_frees_its_frame(monkeypatch):
    """~600 symbols x ~390 bars is a bounded cache only while it is bounded BY
    the scanned set.  The cycle-start policy hook is the real seam
    (``_prune_latest_bars_for_cycle``); a symbol it drops must lose its SN2
    frame too, and pay for a whole window when it comes back."""
    harness = Harness(monkeypatch)
    harness.add_symbol(OTHER_SYMBOL)
    harness.cycle(CYCLE_1_NOW, symbols=(SYMBOL, OTHER_SYMBOL))

    assert harness.bot.cached_bounce_frame(OTHER_SYMBOL) is not None, (
        "the first cycle must have retained a frame for %s" % (OTHER_SYMBOL,)
    )

    # A background-keep cycle whose scanned set no longer holds OTHER_SYMBOL.
    harness.bot._prune_latest_bars_for_cycle(False, {SYMBOL})

    assert harness.bot.cached_bounce_frame(OTHER_SYMBOL) is None, (
        "%s left the scanned set; its frame is still held and will never be "
        "freed" % (OTHER_SYMBOL,)
    )
    assert harness.bot.cached_bounce_frame(SYMBOL) is not None, (
        "%s is still scanned; dropping its frame throws away the whole point "
        "of SN2" % (SYMBOL,)
    )

    harness.cycle(CYCLE_2_NOW, symbols=(SYMBOL, OTHER_SYMBOL))
    by_symbol = {}
    for req in harness.ib.requests_in_cycle(1):
        by_symbol.setdefault(req.symbol, []).append(req)
    assert not any(is_whole_window_request(req) for req in by_symbol[SYMBOL]), (
        "the kept symbol must still be a delta; it asked for %s"
        % ([req.duration for req in by_symbol[SYMBOL]],)
    )
    assert any(is_whole_window_request(req) for req in by_symbol[OTHER_SYMBOL]), (
        "the dropped symbol has no frame left and must refetch the window; it "
        "asked for %s" % ([req.duration for req in by_symbol[OTHER_SYMBOL]],)
    )
