"""Packet WS-10E - the Journal uses my setup notes to tag the trades I took.

Written RED, before any fix exists. Every test here drives a REAL path:
`AutoTagger.suggest_for_trade` (the deterministic tagger the Trades tab and the
nightly `journal_auto_tag` slot both go through), `journal_bulk_tag.build_plan`
/ `apply_plan` (the ONE machine writer of `tag_status='provisional'`),
`ai_jobs.enrichment.run_journal_enrichment` (with only the provider seam
stubbed), the Journal Trades tab's `_show_trade`, and Weekend Prep's
`TagWeekPage`. No test asserts on source text except the outcome-blindness
guard, which is explicitly a source guard and says so.

**The gap, reproduced at code level (2026-09-12/13).**
`grep market_journal scripts/journal_analytics.py` returns nothing. The tagger
has three lanes - `trader_capture` (exact event id, 0.90/0.95), the scanner
context rows (fuzzy, 16 calendar days), and `journal_trade_shape` - and not one
of them reads a Market Journal entry. The trader's own written setup claim
about a name, typed while the trade was open, reaches the Journal's Tags column
by no path at all.

**The contract these tests pin** (the builder may add to it, never weaken it):

* the note lane emits a candidate from `AutoTagger.suggest_for_trade` carrying
  ``match_basis == "note:<entry_id>"`` and ``span`` = the quoted text it matched,
  taken verbatim from the entry;
* lane ORDER, never confidence: `trader_capture` before the note lane before
  the setup-family and shape lanes;
* the window is the trade's OWN window with a one-session margin before the
  open, and a date-only broker fill has NO intraday window;
* a note with no explicit setup claim emits NOTHING, and a quick like is
  interest, not a claim;
* nothing here reads an outcome.

**How the fixtures are built.** Market Journal entries go through
`market_journal.build_entry` and a real `EvidenceLedger`, so they carry the real
row shape - including the fact that the ledger OVERWRITES `session_date` with
`market_session_date(now)` and that the entry's own write time lives in
`created_at`. Annotations go through `ui.annotations.store.record_annotation`.
Trade rows are hand-written SQL with the trader-owned annotation row PRESENT and
EMPTY, which is what an old journal row actually looks like.
"""

from __future__ import annotations

import inspect
import json
import os
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

import pytest

ROOT_DIR = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT_DIR / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import journal_analytics  # noqa: E402
import journal_bulk_tag  # noqa: E402
from ai_jobs import enrichment  # noqa: E402


#: A Friday, and a real trading session. 2026-09-10 and 2026-09-09 are the two
#: sessions before it, which is what the "one session before the open" margin
#: is measured against.
SESSION = "2026-09-11"
PRIOR_SESSION = "2026-09-10"
TWO_SESSIONS_BACK = "2026-09-09"

#: Eastern in September is -04:00. Written out rather than computed so the
#: fixture says what a real `opened_at` on this desk looks like.
ET = timezone(timedelta(hours=-4))

OPENED_AT = f"{SESSION}T09:35:00-04:00"
CLOSED_AT = f"{SESSION}T12:04:00-04:00"
#: A broker statement gives a DATE and no clock time; the importer stores that
#: as midnight market-local exactly so `journal_trade_shape.is_date_only` can
#: recognise it (`scripts/journal_trade_shape.py:137`).
DATE_ONLY_AT = f"{SESSION}T00:00:00-04:00"

NOW = datetime(2026, 9, 12, 6, 0, tzinfo=timezone.utc)

#: A family name straight out of `docs/SETUPS_MAJOR.md` ("AVWAP Breakout"),
#: written the way a trader types it into the Market Journal.
CLAIM_TEXT = "Took it long off the AVWAP Breakout - clean reclaim and it held."
CLAIM_SLUG = "avwap_breakout"

#: A real note that names no setup at all. Every word here is deliberately
#: outside the setup vocabulary: the lane must refuse rather than reach.
NO_CLAIM_TEXT = "Felt heavy into the close. Sized down and stayed patient."

#: The trader's OTHER claim, used to prove the capture lane still outranks a
#: note. Also a `docs/SETUPS_MAJOR.md` name.
CAPTURE_CLAIM = "avwap_retest_followthrough"


def _slug(value) -> str:
    return re.sub(r"[^a-z0-9]+", "_", str(value or "").strip().lower()).strip("_")


# ---------------------------------------------------------------------------
# fixtures - hand-built, none generated by the code under test
# ---------------------------------------------------------------------------


@pytest.fixture
def desk(tmp_path, monkeypatch):
    """An isolated Market Journal ledger, annotation file and journal store.

    `evidence_ledger.default_ledger_dir` reads `project_paths.RUNTIME_DATA_DIR`
    at CALL time, and `journal_analytics` imports `TRADER_ANNOTATIONS_FILE` at
    call time too, so pointing both module attributes at a temp tree is the
    real wiring - the tagger is constructed with no arguments in every test
    below, exactly as `JournalStore.refresh_auto_tags` constructs it.
    """
    import project_paths

    runtime = tmp_path / "runtime"
    (runtime / "evidence_ledgers").mkdir(parents=True, exist_ok=True)
    monkeypatch.setattr(project_paths, "RUNTIME_DATA_DIR", runtime, raising=False)
    annotations = tmp_path / "trader_annotations.jsonl"
    monkeypatch.setattr(
        project_paths, "TRADER_ANNOTATIONS_FILE", annotations, raising=False
    )
    # The review-event lane is a different packet's evidence; an empty list
    # keeps every ranking assertion below about the note lane alone.
    import review_events

    monkeypatch.setattr(review_events, "load_review_events", lambda *a, **k: [])
    journal_analytics.clear_context_row_cache()
    yield {
        "runtime": runtime,
        "ledger_dir": runtime / "evidence_ledgers",
        "annotations": annotations,
        "tmp": tmp_path,
    }
    journal_analytics.clear_context_row_cache()


def _write_note(desk, *, text, symbols, written_at: datetime) -> str:
    """One Market Journal entry, through its own builder and a real ledger.

    Returns the `entry_id`. `written_at` is the ACTUAL write time - the field
    the packet's window is measured against - and it is what the ledger also
    derives the row's `session_date` from, so the fixture cannot claim a
    session the write time contradicts.
    """
    import market_journal
    from evidence_ledger import EvidenceLedger, market_session_date

    session = market_session_date(written_at).isoformat()
    entry = market_journal.build_entry(
        text=text,
        session_date=session,
        symbols=symbols,
        origin=market_journal.ORIGIN_DESK_TAB,
        now=written_at,
    )
    ok, reason = market_journal.is_publishable(entry)
    assert ok, reason
    ledger = EvidenceLedger(
        stream=market_journal.STREAM,
        schema=market_journal.SCHEMA_MARKET_JOURNAL_ENTRY,
        directory=desk["ledger_dir"],
    )
    row = ledger.append(entry, now=written_at)
    return str(row["entry_id"])


def _journal(desk, trades):
    """A `JournalStore` holding exactly `trades`, each with an EMPTY annotation.

    An old row has the trader-owned key PRESENT and EMPTY, not absent - which
    is what `apply_provisional_tags`' refusal branch reads.
    """
    from journal_store import JournalStore

    store = JournalStore(desk["tmp"] / "journal.sqlite3")
    with store.connection() as conn:
        for trade in trades:
            conn.execute(
                "INSERT INTO trades(trade_id, broker, account_number, account_label,"
                " symbol, security_type, currency, direction, status, opened_at,"
                " closed_at, trade_date, net_pnl, updated_at)"
                " VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                (
                    trade["trade_id"], "QUESTRADE", "1", "TFSA",
                    trade.get("symbol", "AAPL"), "STK", "USD",
                    trade.get("direction", "LONG"), trade.get("status", "CLOSED"),
                    trade.get("opened_at", OPENED_AT),
                    trade.get("closed_at", CLOSED_AT),
                    trade.get("trade_date", SESSION),
                    trade.get("net_pnl", 125.0), "x",
                ),
            )
            conn.execute(
                "INSERT INTO trade_annotations(trade_id, setup_tags, notes,"
                " updated_at, tag_status) VALUES(?,?,?,?,?)",
                (
                    trade["trade_id"],
                    trade.get("setup_tags", ""),
                    "",
                    "x",
                    trade.get("tag_status", "confirmed"),
                ),
            )
    return store


def _trade_row(store, trade_id: str) -> dict:
    return dict(store.get_trade(trade_id))


def _suggestions(store, trade_id: str) -> list[dict]:
    """What the deterministic tagger says about one trade, in its own order."""
    tagger = journal_analytics.AutoTagger()
    return list(tagger.suggest_for_trade(_trade_row(store, trade_id)))


def _note_candidates(candidates) -> list[dict]:
    return [
        item for item in candidates
        if str(item.get("match_basis") or "").startswith("note:")
    ]


def _annotation(desk, **fields):
    from ui.annotations import store as annotation_store

    row = annotation_store.record_annotation(path=desk["annotations"], **fields)
    assert row is not None, "the annotation fixture did not reach disk"
    return row


def _apply(store):
    plan = journal_bulk_tag.build_plan(store)
    return plan, journal_bulk_tag.apply_plan(store, plan)


def _annotation_row(store, trade_id: str) -> dict:
    with store.connection() as conn:
        row = conn.execute(
            "SELECT setup_tags, tag_status FROM trade_annotations WHERE trade_id = ?",
            (trade_id,),
        ).fetchone()
    return {"setup_tags": row[0], "tag_status": row[1]}


# ---------------------------------------------------------------------------
# Item 1 - the trader_note lane
# ---------------------------------------------------------------------------


def test_a_note_inside_the_trades_window_naming_a_setup_tags_the_trade(desk):
    """Item 1 + item 4: a written claim becomes a provisional tag that cites it.

    The whole packet in one path. A note typed at 10:15 ET while the AAPL trade
    was open names a setup family the tagger knows; the deterministic lane must
    emit it with `match_basis = note:<entry_id>` and the quoted span, and
    `journal_bulk_tag` must carry it over the same threshold every other lane
    is measured against.
    """
    entry_id = _write_note(
        desk,
        text=CLAIM_TEXT,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 11, 10, 15, tzinfo=ET),
    )
    store = _journal(desk, [{"trade_id": "T-NOTE"}])

    notes = _note_candidates(_suggestions(store, "T-NOTE"))
    assert len(notes) == 1, (
        "the note lane emits exactly one candidate for the one claiming note"
    )
    candidate = notes[0]
    assert candidate["match_basis"] == f"note:{entry_id}", (
        "the candidate names the entry it was read from"
    )
    assert _slug(candidate["tag"]) == CLAIM_SLUG, (
        "the tag is the setup the note claimed"
    )
    span = str(candidate.get("span") or "")
    assert span, "the candidate carries the quoted span it matched"
    assert span.lower() in CLAIM_TEXT.lower(), (
        "the span is quoted verbatim out of the note, never paraphrased"
    )
    assert "avwap" in span.lower() and "breakout" in span.lower(), (
        "the span is the claim itself, not an arbitrary slice of the note"
    )

    plan, summary = _apply(store)
    assert summary["applied"] == 1, "the note lane's candidate reaches the writer"
    written = _annotation_row(store, "T-NOTE")
    assert _slug(written["setup_tags"]) == CLAIM_SLUG
    assert written["tag_status"] == "provisional", (
        "a machine tag is provisional until the trader confirms it"
    )
    applied = [item for item in plan.decisions if item.action == "apply"]
    assert entry_id in (applied[0].rationale + applied[0].source), (
        "the plan's own record names the note the tag came from"
    )


def test_a_note_written_outside_the_trades_window_tags_nothing(desk):
    """Item 1: the window is the trade's OWN, with one session of margin.

    Two notes, same words, same symbol. One was written two sessions before the
    open - outside the one-session margin - and the other inside the trade. The
    lane must take the second and refuse the first, which is the difference
    between "what I said about this trade" and "what I once said about this
    ticker".
    """
    stale = _write_note(
        desk,
        text=CLAIM_TEXT,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 9, 10, 15, tzinfo=ET),
    )
    inside = _write_note(
        desk,
        text=CLAIM_TEXT,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 11, 10, 15, tzinfo=ET),
    )
    store = _journal(desk, [{"trade_id": "T-WINDOW"}])

    bases = {str(item["match_basis"]) for item in _note_candidates(_suggestions(store, "T-WINDOW"))}
    assert f"note:{inside}" in bases, "the note inside the window is a candidate"
    assert f"note:{stale}" not in bases, (
        f"the note written on {TWO_SESSIONS_BACK} is outside the trade's window "
        f"(opened {SESSION}, one session of margin reaches {PRIOR_SESSION})"
    )


def test_a_date_only_broker_fill_has_no_intraday_note_window(desk):
    """Item 1: a date-only fill cannot establish an intraday note window.

    Both trades are AAPL on the same session and the same note sits between
    them. The intraday trade's window contains it. The broker-imported trade
    is stamped midnight market-local - `journal_trade_shape.is_date_only` -
    and midnight is not a time a fill can happen at, so its window is UNKNOWN
    and uncertainty emits no tag.
    """
    _write_note(
        desk,
        text=CLAIM_TEXT,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 11, 10, 15, tzinfo=ET),
    )
    store = _journal(
        desk,
        [
            {"trade_id": "T-INTRADAY"},
            {
                "trade_id": "T-BROKER",
                "opened_at": DATE_ONLY_AT,
                "closed_at": DATE_ONLY_AT,
            },
        ],
    )

    assert _note_candidates(_suggestions(store, "T-INTRADAY")), (
        "the control trade with a real clock time does match the note"
    )
    assert _note_candidates(_suggestions(store, "T-BROKER")) == [], (
        "a midnight-stamped broker fill has no intraday window, so no note matches"
    )


def test_a_note_with_no_explicit_setup_claim_emits_no_tag(desk):
    """Item 1: the lane matches a CLAIM, never a mood.

    Two notes inside the same trade's window. One names a setup and one is the
    kind of sentence the Market Journal is mostly made of. Exactly one
    candidate, and it is the claim.
    """
    _write_note(
        desk,
        text=NO_CLAIM_TEXT,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 11, 10, 5, tzinfo=ET),
    )
    claim = _write_note(
        desk,
        text=CLAIM_TEXT,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 11, 11, 40, tzinfo=ET),
    )
    store = _journal(desk, [{"trade_id": "T-CLAIMONLY"}])

    notes = _note_candidates(_suggestions(store, "T-CLAIMONLY"))
    assert [item["match_basis"] for item in notes] == [f"note:{claim}"], (
        "only the note that names a setup produces a tag"
    )


def test_a_claimed_like_in_the_window_outranks_a_note(desk):
    """Item 1: ordering is by LANE. `trader_capture` leads, the note follows.

    The trader claimed one setup on the capture rail and wrote a different one
    in the journal, both inside this trade's window. The rail claim is an
    explicit, structured statement with an event id; the note is prose. The
    rail wins the top slot and the writer takes it.
    """
    _annotation(
        desk,
        event_type="like_claim",
        symbol="AAPL",
        session_date=SESSION,
        side="LONG",
        like_mode="claimed",
        claimed_setup_id=CAPTURE_CLAIM,
    )
    _write_note(
        desk,
        text=CLAIM_TEXT,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 11, 10, 15, tzinfo=ET),
    )
    store = _journal(desk, [{"trade_id": "T-RANK"}])

    ordered = _suggestions(store, "T-RANK")
    positions = {}
    for index, item in enumerate(ordered):
        if str(item.get("source") or "").startswith(
            f"{journal_analytics.TRADER_CAPTURE_SOURCE}:"
        ):
            positions.setdefault("capture", index)
        elif str(item.get("match_basis") or "").startswith("note:"):
            positions.setdefault("note", index)
    assert "capture" in positions, "the claimed like is still a capture candidate"
    assert "note" in positions, "the note lane still produces its candidate"
    assert positions["capture"] < positions["note"], (
        "a claimed like inside the window outranks a written note"
    )

    _apply(store)
    assert _slug(_annotation_row(store, "T-RANK")["setup_tags"]) == CAPTURE_CLAIM, (
        "the writer takes the trader's structured claim, not the prose one"
    )


def test_a_quick_like_is_interest_and_the_note_is_what_names_the_setup(desk):
    """Item 1: a quick like names nothing, so it cannot displace the note.

    P9's quick like carries no `claimed_setup_id` and reaches the tagger as a
    LINK. It must stay a link - and the note lane, ranked under the capture
    lane, must therefore be what supplies the tag.
    """
    _annotation(
        desk,
        event_type="like_claim",
        symbol="AAPL",
        session_date=SESSION,
        side="LONG",
        like_mode="quick",
    )
    _write_note(
        desk,
        text=CLAIM_TEXT,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 11, 10, 15, tzinfo=ET),
    )
    store = _journal(desk, [{"trade_id": "T-QUICK"}])

    _apply(store)
    written = _annotation_row(store, "T-QUICK")
    assert _slug(written["setup_tags"]) == CLAIM_SLUG, (
        "the note's claim is the tag; the quick like named no setup"
    )
    assert "like" not in written["setup_tags"].lower(), (
        "a quick like never becomes a tag"
    )


def test_an_opposite_side_note_never_matches_the_trade(desk):
    """Item 1: the note's OWN words decide its side; ticker alone is not a match.

    One note, two trades, same symbol and same session. The note says it is a
    short. The long trade must not take it; the short trade must.
    """
    short_note = (
        "Short setup on AAPL - the AVWAP Breakout is failing and I am shorting it."
    )
    entry_id = _write_note(
        desk,
        text=short_note,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 11, 10, 15, tzinfo=ET),
    )
    store = _journal(
        desk,
        [
            {"trade_id": "T-LONG", "direction": "LONG"},
            {"trade_id": "T-SHORT", "direction": "SHORT"},
        ],
    )

    assert _note_candidates(_suggestions(store, "T-LONG")) == [], (
        "a short thesis is not evidence about a long trade"
    )
    matched = _note_candidates(_suggestions(store, "T-SHORT"))
    assert [item["match_basis"] for item in matched] == [f"note:{entry_id}"], (
        "the same words DO match the side they were written about"
    )


def test_a_confirmed_tag_is_never_overwritten_by_the_note_lane(desk):
    """Item 4: the store's refusal is untouched, and it is exercised.

    The trade already carries the trader's own confirmed tag. The note lane
    must still produce its candidate - the suggestion is information - and the
    trader-owned row must come out byte-identical.
    """
    _write_note(
        desk,
        text=CLAIM_TEXT,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 11, 10, 15, tzinfo=ET),
    )
    store = _journal(
        desk,
        [{
            "trade_id": "T-MINE",
            "setup_tags": "my_own_answer",
            "tag_status": "confirmed",
        }],
    )

    assert _note_candidates(_suggestions(store, "T-MINE")), (
        "the refusal is only meaningful if the lane had something to refuse"
    )
    before = _annotation_row(store, "T-MINE")
    _apply(store)
    assert _annotation_row(store, "T-MINE") == before, (
        "a confirmed tag is the trader's answer and nothing improves on it"
    )
    assert not store.apply_provisional_tags("T-MINE", CLAIM_SLUG), (
        "JournalStore.apply_provisional_tags still refuses a confirmed row"
    )


def test_a_repeated_night_writes_the_note_lane_tag_once(desk):
    """Item 4: a second run over unchanged evidence is a no-op.

    The bulk tagger's idempotence is what makes it safe to run after every
    scan. A lane that re-proposed its tag every night would append an
    adjustment a night for the life of the journal.
    """
    _write_note(
        desk,
        text=CLAIM_TEXT,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 11, 10, 15, tzinfo=ET),
    )
    store = _journal(desk, [{"trade_id": "T-ONCE"}])

    _, first = _apply(store)
    assert first["applied"] == 1, "the first night writes the tag"
    second_plan, second = _apply(store)
    assert second["applied"] == 0, "the second night writes nothing"
    assert second_plan.to_apply == [], (
        "an unchanged note produces no new decision to apply"
    )
    assert _slug(_annotation_row(store, "T-ONCE")["setup_tags"]) == CLAIM_SLUG


def test_the_note_lane_reads_no_outcome_field(desk):
    """Item 1 / the tagging rules: no tag may come from what the trade did.

    Two trades identical in every way the lane may look at and opposite in the
    one it may not. The candidates they produce must be the same object, field
    for field, apart from nothing at all.

    The second half is the packet's grep-guard, and it is deliberately a SOURCE
    check: it finds the lane by name and reads its inputs, because a behavioural
    test alone cannot prove a field is unreachable, only that today's fixture
    did not reach it.
    """
    _write_note(
        desk,
        text=CLAIM_TEXT,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 11, 10, 15, tzinfo=ET),
    )
    store = _journal(
        desk,
        [
            {"trade_id": "T-WIN", "net_pnl": 1450.0},
            {"trade_id": "T-LOSS", "net_pnl": -1450.0},
        ],
    )

    winner = _note_candidates(_suggestions(store, "T-WIN"))
    loser = _note_candidates(_suggestions(store, "T-LOSS"))
    assert winner and loser, "both trades match the same note"
    assert winner == loser, (
        "the note lane's answer cannot move with the trade's P&L"
    )

    # The grep-guard. The lane is found by name rather than by a hardcoded
    # symbol so the builder may call it what it likes, as long as it says note.
    lane_sources = []
    for holder in (journal_analytics, journal_analytics.AutoTagger):
        for name, member in vars(holder).items():
            if "note" not in name.lower() or not callable(member):
                continue
            try:
                lane_sources.append((name, inspect.getsource(member)))
            except (OSError, TypeError):  # pragma: no cover - defensive
                continue
    assert lane_sources, (
        "journal_analytics exposes a note lane whose inputs can be read"
    )
    forbidden = (
        "net_pnl", "realized", "pnl_cad", "mfe", "r_multiple", "exit_price",
        "outcome", "win_rate",
    )
    for name, source in lane_sources:
        for field in forbidden:
            assert field not in source, (
                f"{name} reads {field!r}; no tag may be derived from an outcome"
            )


# ---------------------------------------------------------------------------
# Item 2 - the AI suggestion path
# ---------------------------------------------------------------------------


def _gate_is_met(monkeypatch) -> None:
    """Phase 2's gate is a different packet's subject.

    `tests/test_ai_enrichment_and_policy_draft.py` already proves the refusal
    below the gate; rebuilding ten clean digest packs here would test that
    again and nothing about the notes.
    """
    monkeypatch.setattr(
        enrichment,
        "gate_state",
        lambda *args, **kwargs: {
            "gate_met": True,
            "window_met": True,
            "audit_recorded": True,
            "sessions_consecutive_clean": 10,
            "sessions_required": 10,
            "first_gap_session": "",
            "audit_packs_required": 3,
        },
    )


def test_the_enrichment_package_carries_the_candidate_notes_and_the_lane_result(
    desk, monkeypatch
):
    """Item 2: the model is given the notes and the deterministic answer.

    Only the provider call is stubbed - `run_journal_enrichment` builds the
    package for real. The captured package must let the model cite the note by
    id (AI1's `sources`), which means the id, the write time and the text all
    have to be in it, and it must say what the deterministic lane already
    concluded so the model is correcting an answer rather than inventing one.
    """
    import ai_summary

    entry_id = _write_note(
        desk,
        text=CLAIM_TEXT,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 11, 10, 15, tzinfo=ET),
    )
    store = _journal(desk, [{"trade_id": "T-PKG"}])
    _gate_is_met(monkeypatch)

    captured: dict = {}

    def _request(**kwargs):
        captured.update(kwargs)
        return {
            "schema_version": "ai_summary_result_v1",
            "status": "validated",
            "provider": "local",
            "model": "gemma3:12b",
            "summary": {
                "summary": "Long AAPL off the anchored-VWAP breakout.",
                "tags": [],
                "confidence": "medium",
                "sources": [f"note:{entry_id}"],
                "unknowns": [],
            },
        }

    monkeypatch.setattr(ai_summary, "local_provider_enabled", lambda: True)
    monkeypatch.setattr(ai_summary, "local_model", lambda tier="medium": "gemma3:12b")
    monkeypatch.setattr(ai_summary, "request_ai_summary", _request)

    enrichment.run_journal_enrichment(
        session_date=SESSION, now=NOW, store=store, review_rows=[]
    )

    assert captured, "the provider seam was reached"
    blob = json.dumps(captured.get("evidence") or {}, default=str)
    assert entry_id in blob, "the package names the candidate note by its id"
    assert "AVWAP Breakout" in blob, "the package carries the note's own text"
    assert "10:15" in blob, "the package carries the note's actual write time"
    assert "deterministic" in blob, (
        "the deterministic lane's result travels with the package, marked as such"
    )
    assert CLAIM_SLUG in blob, "and it says what that lane concluded"


# ---------------------------------------------------------------------------
# Item 3 - the visible recommendation
# ---------------------------------------------------------------------------


def _widget_text(widget) -> str:
    from PySide6.QtWidgets import QWidget

    texts: list[str] = []
    for child in widget.findChildren(QWidget):
        for getter in ("text", "toPlainText"):
            reader = getattr(child, getter, None)
            if callable(reader):
                try:
                    texts.append(str(reader()))
                except TypeError:
                    pass
    return "\n".join(texts)


@pytest.mark.qt
def test_the_trades_detail_shows_the_note_lane_result(desk, monkeypatch):
    """Item 3: all three shapes of the note-lane line, on the real detail path.

    One `TradesTab`, three trades, `_show_trade` each time - the same seam
    AI1's enrichment row renders through. A claim, a window with notes but no
    claim, and a broker fill whose window cannot be established.
    """
    pytest.importorskip("PySide6", reason="the Qt desk needs PySide6")
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
    from PySide6.QtWidgets import QApplication

    from ui.models.journal import JournalTrade
    from ui.panels.journal.trades_tab import TradesTab
    from ui.services import journal_feed

    claim_id = _write_note(
        desk,
        text=CLAIM_TEXT,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 11, 10, 15, tzinfo=ET),
    )
    _write_note(
        desk,
        text=NO_CLAIM_TEXT,
        symbols=["MSFT"],
        written_at=datetime(2026, 9, 11, 10, 20, tzinfo=ET),
    )
    _write_note(
        desk,
        text=CLAIM_TEXT,
        symbols=["NVDA"],
        written_at=datetime(2026, 9, 11, 10, 25, tzinfo=ET),
    )
    store = _journal(
        desk,
        [
            {"trade_id": "T-SHOW-CLAIM", "symbol": "AAPL"},
            {"trade_id": "T-SHOW-QUIET", "symbol": "MSFT"},
            {
                "trade_id": "T-SHOW-BROKER",
                "symbol": "NVDA",
                "opened_at": DATE_ONLY_AT,
                "closed_at": DATE_ONLY_AT,
            },
        ],
    )
    store.refresh_auto_tags()
    monkeypatch.setattr(journal_feed, "_STORE", store, raising=False)

    application = QApplication.instance() or QApplication([])
    tab = TradesTab(header=None)
    try:
        tab._show_trade(JournalTrade.from_mapping(_trade_row(store, "T-SHOW-CLAIM")))
        application.processEvents()
        blob = _widget_text(tab)
        assert "note lane:" in blob.lower(), "the note lane speaks on the detail pane"
        assert claim_id in blob, "it names the note the tag came from"
        assert "AVWAP Breakout" in blob, "and quotes the span it matched"

        tab._show_trade(JournalTrade.from_mapping(_trade_row(store, "T-SHOW-QUIET")))
        application.processEvents()
        blob = _widget_text(tab).lower()
        assert "no explicit claim" in blob, (
            "a window with notes and no claim says so rather than going silent"
        )
        assert "1 candidate note" in blob, "and counts what it looked at"

        tab._show_trade(JournalTrade.from_mapping(_trade_row(store, "T-SHOW-BROKER")))
        application.processEvents()
        blob = _widget_text(tab).lower()
        assert "unmeasured" in blob, "a window that cannot be established is unmeasured"
        assert "date-only" in blob, "and it says why"
    finally:
        tab.deleteLater()
        application.processEvents()


@pytest.mark.qt
def test_tag_week_marks_the_provisional_tags_that_came_from_a_note(desk, monkeypatch):
    """Item 3: the trader can see WHICH proposals came from their own words.

    Two provisional rows in the same table: one the note lane wrote, one that
    did not come from a note. Exactly one is marked, and it is the note's.
    """
    pytest.importorskip("PySide6", reason="the Qt desk needs PySide6")
    os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
    from PySide6.QtWidgets import QApplication

    import project_paths
    from ui.panels import weekend_prep_panel
    from ui.services.weekend_prep_service import WeekendPrepService

    _write_note(
        desk,
        text=CLAIM_TEXT,
        symbols=["AAPL"],
        written_at=datetime(2026, 9, 11, 10, 15, tzinfo=ET),
    )
    store = _journal(
        desk,
        [
            {"trade_id": "T-TW-NOTE", "symbol": "AAPL"},
            {"trade_id": "T-TW-OTHER", "symbol": "MSFT"},
        ],
    )
    _apply(store)
    # The second row's provisional tag comes from somewhere that is not a note,
    # so the marker has something to distinguish itself from.
    assert store.apply_provisional_tags("T-TW-OTHER", "sma_breakout_retest")

    rows = weekend_prep_panel._read_week_tag_rows((SESSION, SESSION), store=store)
    by_id = {str(row.get("trade_id")): row for row in rows}
    assert {"T-TW-NOTE", "T-TW-OTHER"} <= set(by_id), (
        "both provisional rows reach the review list"
    )

    monkeypatch.setattr(
        project_paths, "WEEKEND_PREP_STATE_FILE", desk["tmp"] / "wp.json", raising=False
    )
    application = QApplication.instance() or QApplication([])
    page = weekend_prep_panel.TagWeekPage(WeekendPrepService())
    try:
        page._on_rows_ready({"tags": rows, "missing_risk": [], "coverage": ""})
        application.processEvents()
        rendered = {}
        for index in range(page.table.rowCount()):
            cells = [
                page.table.item(index, column).text()
                if page.table.item(index, column) is not None else ""
                for column in range(page.table.columnCount())
            ]
            line = " | ".join(cells)
            rendered["T-TW-NOTE" if "AAPL" in line else "T-TW-OTHER"] = line.lower()
        assert set(rendered) == {"T-TW-NOTE", "T-TW-OTHER"}
        assert "note" in rendered["T-TW-NOTE"], (
            "the row whose provisional tag came from a journal note is marked"
        )
        assert "note" not in rendered["T-TW-OTHER"], (
            "and a row that did not come from a note is not"
        )
    finally:
        page.shutdown()
        page.deleteLater()
        application.processEvents()
