"""Hand-built fixtures for the TJ-14B red tests. NOT a test module.

Everything here is written by hand or assembled by the REAL journal path
(`manual_execution_from_fields` -> `upsert_executions` -> `rebuild_trades`).
Nothing is generated by the code under test, and nothing touches
`C:\\TradingBotData`: pytest's own `conftest.py` points `TRADINGBOTV3_DATA_DIR`
at a temp directory before anything under `scripts/` is imported.

THE CALENDAR THESE TESTS STAND ON
---------------------------------
`SESSION` is Monday **2026-09-14**. Its previous exchange session is Friday
2026-09-11, and Monday 2026-09-07 is Labor Day, so counting back five sessions
from 2026-09-14 lands on Friday 2026-09-04. Every test that leans on that
asserts `market_calendar.trading_days_between` agrees before it asserts
anything about the Mentor.

THE STATE MAPPING
-----------------
`mentor_questions.pending(state, slot)` is handed a plain mapping. These helpers
build it, and the keys they use are the contract the tester pins:

    session         ISO date of the slot's session
    now             aware datetime (Pacific)
    auto_mode       "DESK" / "AWAY" / "EVENING" / "OFF"
    trades          journal trade rows the card could ask about
    open_positions  journal trade rows still OPEN
    likes           `trader_annotations` rows (`like_claim`), each optionally
                    carrying `matched_trade_id` / `real_miss`
    grader_gaps     rows a deterministic reader raised, each with
                    `question_id`, `options`, `consumer`, `answer_key`
    decisions       the four `trade_origin.planned_state` lanes, by their own
    claims          parameter names. All four empty means every trade with a
    focus_adds      readable first fill is `unplanned`, which is what makes a
    armed           `trade_origin` question fire.
    ai_question     `{"question": str, "options": [...]}` or `{}`
    answered        `{"<kind>:<subject_id>": {"answered_at": "<ISO date>"}}`
    retired         iterable of `"<kind>:<subject_id>"` the trader stopped
    carried         the `carried` tuple returned by the PREVIOUS card
"""

from __future__ import annotations

import sys
from datetime import date, datetime
from pathlib import Path
from typing import Any, Iterable, Mapping
from zoneinfo import ZoneInfo

ROOT_DIR = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT_DIR / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

PACIFIC = ZoneInfo("America/Los_Angeles")

#: A plain Monday, full session, 07-12 Pacific slots.
SESSION = date(2026, 9, 14)
#: The previous exchange session (2026-09-07 is Labor Day).
REVIEWED = "2026-09-11"
#: The Wednesday of the SAME exchange week as `SESSION`.
MID_WEEK = date(2026, 9, 16)
#: The Monday of the NEXT exchange week.
NEXT_WEEK = date(2026, 9, 21)
#: The day after US Thanksgiving 2026 - a 10:00 Pacific close.
EARLY_CLOSE = date(2026, 11, 27)

ACCOUNT = "TJ14B-TEST-ACCOUNT"


def pacific(day: date, hour: int, minute: int = 0) -> datetime:
    return datetime(day.year, day.month, day.day, hour, minute, tzinfo=PACIFIC)


def new_store(tmp_path: Path):
    from journal_store import JournalStore

    return JournalStore(Path(tmp_path) / "journal.sqlite3")


def _execution(
    execution_id: str,
    *,
    symbol: str,
    side: str,
    qty: float,
    price: float,
    timestamp: str,
    security_type: str = "STK",
) -> Any:
    from journal_importers import manual_execution_from_fields

    return manual_execution_from_fields(
        {
            "broker": "MANUAL",
            "account_number": ACCOUNT,
            "symbol": symbol,
            "side": side,
            "quantity": qty,
            "price": price,
            "timestamp": timestamp,
            "security_type": security_type,
            "currency": "USD",
            "commission": 0,
            "fees": 0,
            "execution_id": execution_id,
        }
    )


def add_round_trip(store, symbol: str, *, day: str = REVIEWED, entry_hour: int = 7) -> str:
    """One CLOSED long round trip on `day`, assembled by the real rebuild."""
    store.upsert_executions(
        [
            _execution(
                f"{symbol}-{day}-open",
                symbol=symbol,
                side="BUY",
                qty=100,
                price=10.0,
                timestamp=f"{day}T{entry_hour:02d}:31:00",
            ),
            _execution(
                f"{symbol}-{day}-close",
                symbol=symbol,
                side="SELL",
                qty=100,
                price=11.0,
                timestamp=f"{day}T{entry_hour + 2:02d}:05:00",
            ),
        ]
    )
    store.rebuild_trades(refresh_tags=False)
    for trade in store.list_trades(trade_date=day):
        if str(trade.get("symbol") or "") == symbol:
            return str(trade["trade_id"])
    raise AssertionError(f"{symbol} did not assemble into a trade on {day}")


def add_open_position(store, symbol: str, *, day: str) -> str:
    """One OPEN long, opened on `day` and never closed."""
    store.upsert_executions(
        [
            _execution(
                f"{symbol}-{day}-open",
                symbol=symbol,
                side="BUY",
                qty=100,
                price=10.0,
                timestamp=f"{day}T07:31:00",
            )
        ]
    )
    store.rebuild_trades(refresh_tags=False)
    for trade in store.list_trades(trade_date=day):
        if str(trade.get("symbol") or "") == symbol:
            return str(trade["trade_id"])
    raise AssertionError(f"{symbol} did not assemble into a trade on {day}")


def mark_covered(store, day: str, *, status: str = "COVERED") -> None:
    import journal_coverage

    journal_coverage.mark_range(
        store,
        broker="QUESTRADE",
        account_number=ACCOUNT,
        start=day,
        end=day,
        status=status,
        source="tj14b-test",
    )


def slot_at(session: date, hour: int):
    from trade_mentor_schedule import slots_for_session

    for slot in slots_for_session(session):
        if slot.scheduled_at.hour == hour:
            return slot
    raise AssertionError(f"no {hour:02d}:00 slot on {session}")


def last_slot(session: date):
    from trade_mentor_schedule import slots_for_session

    slots = slots_for_session(session)
    assert slots, f"{session} carries no Mentor slots"
    return slots[-1]


def trade_row(
    trade_id: str,
    *,
    symbol: str,
    day: str,
    direction: str = "LONG",
    status: str = "CLOSED",
    opened_hour: int = 7,
    setup_tags: str = "",
    tag_status: str = "",
) -> dict[str, Any]:
    """A journal trade row shaped exactly as `list_trades` returns one.

    `setup_tags` and `tag_status` are PRESENT AND EMPTY on an untagged trade -
    that is how the live rows read, and an absent key would be a different
    (easier) case than the one the desk actually meets.
    """
    return {
        "trade_id": trade_id,
        "symbol": symbol,
        "direction": direction,
        "status": status,
        "trade_date": day,
        "opened_at": f"{day}T{opened_hour:02d}:31:00-04:00",
        "closed_at": f"{day}T{opened_hour + 2:02d}:05:00-04:00" if status == "CLOSED" else "",
        "setup_tags": setup_tags,
        "tag_status": tag_status,
        "thesis": "",
        "planned_stop": None,
        "planned_target": None,
        "security_type": "STK",
    }


def like_row(
    event_id: str,
    *,
    symbol: str,
    day: str,
    side: str = "long",
    like_mode: str = "quick",
    **extra: Any,
) -> dict[str, Any]:
    """One `like_claim` annotation row, as `load_annotations` yields it.

    `claimed_setup_id` is PRESENT AND EMPTY on a quick like - the live rows read
    that way, and `like_mode_of` treats an ABSENT `like_mode` as `claimed`.
    """
    row = {
        "schema_version": 1,
        "event_id": event_id,
        "event_type": "like_claim",
        "symbol": symbol,
        "side": side,
        "session_date": day,
        "created_at": f"{day}T10:15:00-07:00",
        "source": "chart_review",
        "like_mode": like_mode,
        "claimed_setup_id": "",
        "note": "",
    }
    row.update(extra)
    return row


def state(
    *,
    session: date = SESSION,
    now: datetime | None = None,
    auto_mode: str = "DESK",
    trades: Iterable[Mapping[str, Any]] = (),
    open_positions: Iterable[Mapping[str, Any]] = (),
    likes: Iterable[Mapping[str, Any]] = (),
    grader_gaps: Iterable[Mapping[str, Any]] = (),
    decisions: Iterable[Mapping[str, Any]] = (),
    claims: Iterable[Mapping[str, Any]] = (),
    focus_adds: Iterable[Mapping[str, Any]] = (),
    armed: Iterable[Mapping[str, Any]] = (),
    ai_question: Mapping[str, Any] | None = None,
    answered: Mapping[str, Mapping[str, Any]] | None = None,
    retired: Iterable[str] = (),
    carried: Iterable[Any] = (),
    **extra: Any,
) -> dict[str, Any]:
    payload = {
        "session": session.isoformat(),
        "now": now or pacific(session, 11),
        "auto_mode": auto_mode,
        "trades": list(trades),
        "open_positions": list(open_positions),
        "likes": list(likes),
        "grader_gaps": list(grader_gaps),
        "decisions": list(decisions),
        "claims": list(claims),
        "focus_adds": list(focus_adds),
        "armed": list(armed),
        "ai_question": dict(ai_question or {}),
        "answered": dict(answered or {}),
        "retired": list(retired),
        "carried": tuple(carried),
    }
    payload.update(extra)
    return payload


def keys_of(subjects: Iterable[Any]) -> set[tuple[str, str]]:
    return {(str(item.kind), str(item.subject_id)) for item in subjects}


def kinds_of(subjects: Iterable[Any]) -> list[str]:
    return [str(item.kind) for item in subjects]
