"""Hand-built bar fixtures for the TJ-14A red tests. NOT a test module.

Nothing here is generated by the code under test: every bar is written by hand
from a per-symbol `(m, d)` pair, and every expected number in the tests is
computed from that pair by a formula written independently in the test file.

THE SHAPE OF ONE SYMBOL'S DAY
-----------------------------
Twelve completed regular-session M5 bars, 09:30 -> 10:25 New York on Monday
2026-09-14, read at 10:30 (07:30 Pacific) so 10:25 is the last COMPLETED bar:

    closes = [100.0] * 5 + [m] * 6 + [d]

* `d` is the last completed close, so **the day's change is `d - 100`** exactly
  (the prior session's close is pinned at 100.0 for every symbol);
* `m` is the close 30 minutes earlier, so the existing `m5_change_30m_pct` is
  `(d - m) / m * 100` - deliberately DECOUPLED from the day's change, so a
  builder that ranks "over 30 minutes" by the day's move fails;
* every bar is `high = close + 0.5`, `low = close - 0.5`, `open = close`, and
  volume is identical, so the session VWAP is the plain mean of the closes and
  "above / below VWAP" is decidable by hand;
* the day's range is therefore `[min(closes) - 0.5, max(closes) + 0.5]`.

The prior session (Friday 2026-09-11) closes at 100.0 with a HIGH of 103.0 and
a LOW of 97.0 for every symbol, so "side of the prior day's high and low" is
decided by `d` alone.

A FORMING BAR IS PRESENT ON PURPOSE. `forming=True` appends a 10:30 bar with a
wild close; at 10:30 it is not complete (`10:35 > now`) and no v2 reading may
move because of it.
"""

from __future__ import annotations

import sys
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any, Mapping
from zoneinfo import ZoneInfo

ROOT_DIR = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT_DIR / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

EXCHANGE = ZoneInfo("America/New_York")

#: A plain Monday. Its previous exchange session is Friday 2026-09-11.
SESSION = date(2026, 9, 14)
PRIOR_SESSION = date(2026, 9, 11)
#: 10:30 New York = 07:30 Pacific. The last COMPLETED M5 bar starts 10:25.
NOW = datetime(2026, 9, 14, 10, 30, tzinfo=EXCHANGE)

#: Every symbol's prior close, so a day change is `d - 100` in percent.
PRIOR_CLOSE = 100.0
PRIOR_HIGH = 103.0
PRIOR_LOW = 97.0

#: The eleven SPDR sector ETFs, XLRE included (`group_rrs.SECTOR_ETFS`).
SECTORS = ("XLB", "XLC", "XLE", "XLF", "XLI", "XLK", "XLP", "XLRE", "XLU", "XLV", "XLY")
OFFENSE = ("XLK", "XLY", "XLC")
DEFENSE = ("XLP", "XLU", "XLV")

#: symbol -> (close 30 minutes ago, last completed close).
#:
#: XLE and XLF are TIED at the top of the day (+2.00 each) so the leader list
#: has a real tie to break; XLF is NEGATIVE over 30 minutes while leading the
#: day, and XLRE leads over 30 minutes while sitting eighth on the day.
DAY: dict[str, tuple[float, float]] = {
    "SPY": (100.2, 100.5),
    "RSP": (100.0, 101.0),
    "VXX": (99.0, 98.5),
    "TLT": (100.0, 100.8),
    "USO": (100.0, 97.9),
    "IWM": (100.0, 100.3),
    "QQQ": (100.0, 100.6),
    "XLE": (101.8, 102.0),
    "XLF": (102.4, 102.0),
    "XLK": (100.0, 101.5),
    "XLY": (100.0, 101.2),
    "XLC": (100.0, 100.9),
    "XLI": (100.0, 100.4),
    "XLB": (99.0, 100.1),
    "XLRE": (98.0, 99.8),
    "XLV": (99.0, 99.5),
    "XLU": (100.0, 99.2),
    "XLP": (100.0, 98.9),
}


def closes_for(symbol: str) -> list[float]:
    """The twelve completed closes, oldest first."""
    thirty, last = DAY[symbol]
    return [PRIOR_CLOSE] * 5 + [thirty] * 6 + [last]


def m5_bars(symbol: str, *, forming: bool = False) -> list[dict[str, Any]]:
    return m5_bars_from(closes_for(symbol), forming=forming)


def m5_bars_at(thirty: float, last: float, *, forming: bool = False) -> list[dict[str, Any]]:
    """One symbol's day written directly, for a variant the table does not hold."""
    return m5_bars_from([PRIOR_CLOSE] * 5 + [thirty] * 6 + [last], forming=forming)


def m5_bars_from(closes: list[float], *, forming: bool = False) -> list[dict[str, Any]]:
    start = datetime(SESSION.year, SESSION.month, SESSION.day, 9, 30, tzinfo=EXCHANGE)
    rows: list[dict[str, Any]] = []
    for index, close in enumerate(closes):
        rows.append(
            {
                "dt": start + timedelta(minutes=5 * index),
                "open": close,
                "high": close + 0.5,
                "low": close - 0.5,
                "close": close,
                "volume": 1_000,
            }
        )
    if forming:
        rows.append(
            {
                "dt": start + timedelta(minutes=60),
                "open": 100.0,
                "high": 900.0,
                "low": 1.0,
                "close": 500.0,
                "volume": 1_000,
            }
        )
    return rows


def _sessions_ending(last: date, count: int) -> list[date]:
    import market_calendar

    rows: list[date] = []
    cursor = last
    while len(rows) < count:
        if market_calendar.is_session(cursor):
            rows.append(cursor)
        cursor -= timedelta(days=1)
    return list(reversed(rows))


def d1_bars(_symbol: str) -> list[dict[str, Any]]:
    """Twenty completed sessions ending Friday, the last one with a real range."""
    days = _sessions_ending(PRIOR_SESSION, 20)
    rows: list[dict[str, Any]] = []
    for day in days:
        last = day == days[-1]
        rows.append(
            {
                "dt": day.isoformat(),
                "open": PRIOR_CLOSE,
                "high": PRIOR_HIGH if last else 101.0,
                "low": PRIOR_LOW if last else 99.0,
                "close": PRIOR_CLOSE,
            }
        )
    return rows


def bars(*, drop: tuple[str, ...] = (), forming: bool = False) -> dict[str, dict]:
    """`{"m5": {...}, "d1": {...}}` for every v2 symbol except `drop`."""
    import trade_mentor_context

    names = [name for name in trade_mentor_context.SYMBOLS if name not in drop]
    return {
        "m5": {name: m5_bars(name, forming=forming) for name in names},
        "d1": {name: d1_bars(name) for name in names},
    }


def context(**kwargs) -> dict[str, Any]:
    """The v2 snapshot the fixture describes, through the ONE live builder."""
    from trade_mentor_context import build_context

    payload = bars(**kwargs)
    return build_context(
        now=NOW,
        m5_bars=payload["m5"],
        d1_bars=payload["d1"],
        sources={"m5": "fixture", "d1": "fixture"},
    )


def reading(snapshot: Mapping[str, Any], symbol: str) -> dict[str, Any]:
    return next(row for row in snapshot["readings"] if row["symbol"] == symbol)


# -- the independent formulas the tests assert against ----------------------


def expected_day_change(symbol: str) -> float:
    _thirty, last = DAY[symbol]
    return (last - PRIOR_CLOSE) / PRIOR_CLOSE * 100.0


def expected_thirty_minute_change(symbol: str) -> float:
    thirty, last = DAY[symbol]
    return (last - thirty) / thirty * 100.0


def expected_range_place(symbol: str) -> float:
    values = closes_for(symbol)
    low = min(values) - 0.5
    high = max(values) + 0.5
    return (values[-1] - low) / (high - low)


def expected_session_vwap(symbol: str) -> float:
    values = closes_for(symbol)
    return sum(values) / len(values)
