"""One name per setup: the frozen crosswalk between five naming sites.

Phase 0.13 packet P7. Spec: `docs/ULTIMATE_SETUP_DATABASE_PLAN.md` sec 11 (the
versioned setup registry) and Appendix C (the seed ontology and its required
columns).

**Why this exists.** The same setup is called four or five different things
depending on which file you are in: `AVWAP_BAND_BOUNCE` in the warehouse,
`avwap_band_bounce` in the docs, `band_test_rebound` in the playbook study,
`previous_avwape_bounce` in a legacy alias. Nothing joined them, so a claim the
trader made, an occurrence the scanner wrote and a study row the playbook
produced could describe one setup and never meet. This module is that join, and
nothing else: it is READ-ONLY DATA plus lookups.

**What it is NOT, yet.** It is not authoritative. Nothing in production imports
it, and every row names the packet that makes it authoritative -
`plan.md P4.1`, the identity-graph freeze. Until then it is a description of
what the code already believes, and where the code disagrees with itself that
disagreement is DATA (`known_divergences`), not something this packet resolved:
choosing which of two spellings is identity is exactly the decision P4.1 owns.

**What is deliberately blank.** Appendix C requires supported sides, timeframe
roles, the exact completed-bar trigger and the primary recipe. None of the five
sources establishes them, so every row carries them EMPTY and lists them under
`unestablished`. A guessed side would read as established in exactly the column
a later experiment trusts; a blank one says "not established", which is true.

The frozen JSON is regenerated by `scripts/build_setup_registry.py`, reviewed as
a diff, and committed. It is never rebuilt at import time - a crosswalk that
recomputes itself from five moving sources is a sixth source.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from types import MappingProxyType
from typing import Any, Mapping

REGISTRY_PATH = Path(__file__).resolve().parent / "setup_registry_v1.json"
REGISTRY_VERSION = 1

#: Appendix C's role vocabulary, verbatim.
ROLE_TRADE_SETUP = "TRADE_SETUP"
ROLE_CONTEXT = "CONTEXT"
ROLE_WATCH_STATE = "WATCH_STATE"
ROLE_CONTROL = "CONTROL"
ROLE_FALLBACK = "FALLBACK"
ROLES = (ROLE_TRADE_SETUP, ROLE_CONTEXT, ROLE_WATCH_STATE, ROLE_CONTROL, ROLE_FALLBACK)

#: The fact pack (packet P3) prints `TRADE` where Appendix C writes
#: `TRADE_SETUP`. The registry keeps Appendix C's spelling - it is the spec - and
#: this map exists so the fact pack can read the ONE table without its output
#: text changing. Two vocabularies with one owner beats one vocabulary with two.
FACT_PACK_ROLE_BY_REGISTRY_ROLE = {
    ROLE_TRADE_SETUP: "TRADE",
    ROLE_CONTEXT: "CONTEXT",
    ROLE_WATCH_STATE: "WATCH_STATE",
    ROLE_CONTROL: "CONTROL",
    ROLE_FALLBACK: "FALLBACK",
}


class SetupRegistryError(LookupError):
    """A name that should resolve does not. Never swallowed: an unresolvable
    setup name means two tables are describing different things under one word,
    and a silent default is how that stays invisible."""


@lru_cache(maxsize=1)
def _payload() -> Mapping[str, Any]:
    with REGISTRY_PATH.open("r", encoding="utf-8") as handle:
        return json.load(handle)


@lru_cache(maxsize=1)
def registry() -> Mapping[str, Mapping[str, Any]]:
    """`{setup_id@version: entry}`, frozen.

    Read-only by construction rather than by convention: a caller that mutated a
    shared registry entry would change what every later reader believes a setup
    is, and would do it without a diff.
    """
    entries = {
        key: MappingProxyType(dict(value)) for key, value in _payload()["entries"].items()
    }
    return MappingProxyType(entries)


@lru_cache(maxsize=1)
def known_divergences() -> tuple[Mapping[str, Any], ...]:
    """Where two naming sites disagree, and which packet resolves each one.

    These are FINDINGS, not defects this packet fixed. Each says what the two
    sources believe and leaves the choice to P4.1.
    """
    return tuple(
        MappingProxyType(dict(item)) for item in _payload().get("known_divergences", ())
    )


@lru_cache(maxsize=1)
def _index() -> Mapping[str, str]:
    """Every name that resolves -> its registry key.

    Built once and asserted collision-free: two entries claiming one alias would
    make `resolve` order-dependent, which is the same bug as having no registry.
    """
    index: dict[str, str] = {}

    def claim(name: str, key: str) -> None:
        text = str(name or "").strip()
        if not text:
            return
        lowered = text.lower()
        existing = index.get(lowered)
        if existing is not None and existing != key:
            raise SetupRegistryError(
                f"{text!r} is claimed by both {existing!r} and {key!r}; "
                "one name may name only one setup"
            )
        index[lowered] = key

    for key, entry in registry().items():
        claim(key, key)
        claim(entry["setup_id"], key)
        claim(entry["canonical_setup_id"], key)
        for field in ("docs_key", "playbook_family", "claim_id", "family_tag_key"):
            claim(entry.get(field, ""), key)
        for alias in entry.get("aliases", ()):
            claim(alias, key)
    return MappingProxyType(index)


def resolve(name: str) -> Mapping[str, Any]:
    """The one entry this name refers to, whichever naming site it came from.

    Raises rather than returning a default. A setup name that does not resolve
    is a real finding - some table is writing a name nothing else knows - and a
    quiet fallback to GENERAL would file that finding under "untagged" forever.
    """
    key = _index().get(str(name or "").strip().lower())
    if key is None:
        raise SetupRegistryError(f"no registry entry for {name!r}")
    return registry()[key]


def find(name: str) -> Mapping[str, Any] | None:
    """`resolve` for a caller that legitimately expects misses."""
    key = _index().get(str(name or "").strip().lower())
    return registry()[key] if key is not None else None


def canonical_setup_id(name: str) -> str:
    """The warehouse id for any spelling of this setup."""
    return str(resolve(name)["canonical_setup_id"])


def role(name: str) -> str:
    """Appendix C's role for this setup."""
    return str(resolve(name)["role"])


def fact_pack_role(family: str) -> str:
    """The role in the fact pack's own words - `TRADE`, not `TRADE_SETUP`.

    This is what packet P3's `setup_research.family_role` calls, so the fact
    pack's two-entry role map has one owner instead of being a second, smaller
    ontology that drifts. An UNKNOWN family answers `TRADE`, which is the
    behaviour that map already had: the fact pack must not stop grading a family
    it has never heard of, and a name it cannot resolve is a registry gap rather
    than a reason to reclassify live evidence.
    """
    entry = find(family)
    if entry is None:
        return FACT_PACK_ROLE_BY_REGISTRY_ROLE[ROLE_TRADE_SETUP]
    return FACT_PACK_ROLE_BY_REGISTRY_ROLE.get(
        str(entry["role"]), FACT_PACK_ROLE_BY_REGISTRY_ROLE[ROLE_TRADE_SETUP]
    )


def entries_by_role(wanted: str) -> tuple[Mapping[str, Any], ...]:
    return tuple(entry for entry in registry().values() if entry["role"] == wanted)


def entries_by_status(wanted: str) -> tuple[Mapping[str, Any], ...]:
    return tuple(entry for entry in registry().values() if entry["status"] == wanted)


__all__ = [
    "REGISTRY_PATH",
    "REGISTRY_VERSION",
    "ROLES",
    "ROLE_CONTEXT",
    "ROLE_CONTROL",
    "ROLE_FALLBACK",
    "ROLE_TRADE_SETUP",
    "ROLE_WATCH_STATE",
    "SetupRegistryError",
    "canonical_setup_id",
    "entries_by_role",
    "entries_by_status",
    "fact_pack_role",
    "find",
    "known_divergences",
    "registry",
    "resolve",
    "role",
]
